npx supabase functions deploy ai-orchestrator --no-verify-jwt
npx supabase functions deploy engineering-bom-sow --no-verify-jwt
npx supabase functions deploy engineering-calc-agent --no-verify-jwt
npx supabase functions deploy scheduled-agents --no-verify-jwt
npx supabase functions deploy analytics-orchestrator --no-verify-jwt
npx supabase functions deploy send-report-email --no-verify-jwt
npx supabase functions deploy voice-report-intent --no-verify-jwt
npx supabase functions deploy voice-transcribe --no-verify-jwt
npx supabase functions deploy semantic-search --no-verify-jwt
npx supabase functions deploy embed-entry --no-verify-jwt
npx supabase functions deploy marketplace-checkout --no-verify-jwt
npx supabase functions deploy marketplace-webhook --no-verify-jwt
npx supabase functions deploy marketplace-connect-onboard --no-verify-jwt
npx supabase functions deploy marketplace-release --no-verify-jwt
npx supabase functions deploy marketplace-connect-status --no-verify-jwt
npx supabase functions deploy project-progress --no-verify-jwt
