// WorkHive Service Worker — Phase 2 (multi-page shell, 2026-05-11)
// Enables PWA installability + offline shell across the worker-critical
// surfaces (logbook, inventory, pm-scheduler, hive, asset-hub, shift-brain).
// Closes PRODUCTION_FIXES #54.

const CACHE_NAME  = 'workhive-shell-v135';  // bump 2026-05-21: PHASE A COMPREHENSIVE WIRING — turn-level prompt-anchor wiring across 9 flywheel batches. 24 new per-turn anchors total. SAFETY (T175-T184): INCIDENT GATE + LOTO GATE + HOT WORK GATE + CONFINED SPACE GATE + PPE MATRIX + NEAR-MISS CAPTURE + JSA OFFER. INTEGRATION+AUDIT (T95-T104): SESSION TAG (T100) + STT MANGLED (T102) + SHIFT END HORIZON (T104) + QUIET HOURS (T96). LEARNING (T105-T114): MENTOR HANDOFF (T114). COMPLIANCE (T115-T124): PII SCRUBBED (T115) + CONSENT CHANGE (T116) + ERASURE REQUEST (T118) + SUSPICIOUS ACTIVITY (T120). ACCESSIBILITY (T125-T134): VOICE-ONLY TOGGLE (T133). OPERATIONAL (T135-T144): MEMORY PRESSURE (T140). TEAM COORDINATION (T145-T154): HANDOFF (T146) + SHARED NOTE (T147) + WATCHLIST (T149) + RESOLUTION CAPTURE (T151). SUSTAINABILITY (T195-T204): ENERGY QUERY (T204). MULTI-LANG NLU (T205-T214): TAGALOG IMPERATIVE (T207) + POLITENESS REGISTER (T209). All 9 batch validators extended with wire_* ratchets — 105 checks PASS, 26 AI-companion + dialog validators rc=0. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v134';  // bump 2026-05-21: PHASE A WIRING — turn-level prompt-anchor wiring for the SAFETY + PERMIT-TO-WORK batch (turns #175-#184). Seven new per-turn anchors live in voice-handler.js: INCIDENT GATE (T182, fires first inside the safety block), LOTO GATE (T175, references the energy isolation checklist + zero-energy verification), HOT WORK GATE (T176, requires hot-work permit + fire watch + flammables-cleared radius), CONFINED SPACE GATE (T177, requires 4-gas PH OSHS reading + attendant + rescue plan), PPE MATRIX (T178, flagged authoritative — no LLM improvisation), NEAR-MISS CAPTURE (T179, routes to safety_near_miss), JSA OFFER (T180, 4-step structure). Validator extended with 7 wire_* ratchets (17/17 PASS). Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v133';  // bump 2026-05-21: voice-handler.js Phase 4.207-4.216 twenty-first 10-turn flywheel (turns #205-#214, MULTI-LANGUAGE NLU): Cebuano markers (unsa/asa/kinsa/lagi/bitaw), Ilonggo markers (gid/bala/manami/damo gid), Tagalog imperative detector (i-X mo / X-an mo / pakisuyo), code-switch ratio (PH word coverage of last 10 turns), politeness register classifier (formal po/ho vs casual tol/pre/bro vs mixed), PH time phrases (umaga/tanghali/hapon/gabi/madaling araw), bilingual number words 0-20 (isa/dalawa/usa/duha/one/two), filler suppression (uh/um/eto kasi/ano ba), bilingual stop-word list for retrieval, shop-floor slang→canonical (sira→broken / nag-init→overheat / umiyak→leak). Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v132';  // bump 2026-05-21: voice-handler.js Phase 4.187-4.206 nineteenth + twentieth 10-turn flywheel batches (turns #185-#204). KNOWLEDGE GRAPH (T185-T194): entity extraction (asset_tags + failure_modes + worker mentions), relation extraction (caused/feeds), KG triple builder with allow-listed predicates, RAG context block with citation markers, FNV-1a 32-bit embedding hash + Hamming distance, document chunking (400/50 default), citation build+parse (<view>:<row>:<column>), query rewriter (strips fillers, injects entities), reasoning trace (8-hop bounded localStorage), KB version tracking. ENERGY + SUSTAINABILITY (T195-T204): EnPI (ISO 50001), PH grid carbon factor 0.717 kgCO2e/kWh, peak demand breach + near-miss, 5σ energy anomaly, standby waste, water use breach, compressed-air leak loss estimator (dB→cfm), motor efficiency vs IE3 baseline, sustainability KPI bundle, energy query detector. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v130';  // bump 2026-05-21: voice-handler.js Phase 4.167-4.186 seventeenth + eighteenth 10-turn flywheel batches (turns #165-#184). ADVANCED ANALYTICS (T165-T174): 3σ anomaly detection, Weibull moment fit (Justus closed-form approximation), Pareto top-80%, linear trend regression (rising/falling/flat), seasonal peak index, outlier-trimmed mean, z-score primitive, Pearson correlation, Weibull failure-probability CDF, availability calc. SAFETY + PERMIT-TO-WORK (T175-T184): LOTO intent detector (lockout-tagout / isolation / padlock / de-energize / PH variants), hot-work detector (welding/grinding/cutting torch/brazing), confined-space detector (tank entry / sump / vessel / PH variants), PPE query + matrix (hot_work/confined_space/chemical/electrical/height/default), near-miss capture (close call / muntik na), JSA template builder (4-step task-hazard-control-PPE), gas-test validator (PH OSHS O2 19.5-23.5 / LEL ≤10 / CO ≤35 / H2S ≤10), incident reporter, energy-isolation checklist (electrical/mechanical/hydraulic/pneumatic/chemical/thermal/gravitational), permit expiry check. Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v128';  // bump 2026-05-21: voice-handler.js Phase 4.157-4.166 sixteenth 10-turn flywheel (turns #155-#164, EXTERNAL INTEGRATION): SAP PM webhook receiver (PM01-PM04 validation), Maximo REST poll (oslc.where + oslc.select for COMP work orders), OPC-UA tag parser (Plant1.P203.Vibration_RMS → P-203 + vibration_rms), MQTT topic builder (workhive/<hive>/<asset>/<metric>) + JSON payload parser, Slack webhook sender, email digest body builder (5-line format), Microsoft Teams Adaptive Card builder, calendar ICS event builder, webhook signature constant-time compare (XOR via charCodeAt), outbound retry queue (wh_voice_outbound_queue, capped at 20, drain on online). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v127';  // bump 2026-05-21: voice-handler.js Phase 4.147-4.156 fifteenth 10-turn flywheel (turns #145-#154, TEAM COORDINATION + CROSS-WORKER): active voice worker list (wh_voice_presence query, 5-min activity window), cross-worker handoff ('send this to Mike' + 'ipasa kay Kuya Ben' → companion_handoff table), shared note thread (shared_voice_notes for team broadcast), high-concurrency alert (>5 voice sessions → 'team busy go async'), watchlist subscriptions ('watch P-203' / 'notify me on MX-12' → asset_watchlist), supervisor-only voice broadcast (not_supervisor gate + __broadcast__ marker), resolution detector ('fixed it' / 'ayos na' / 'gumana na' → knowledge sharing nudge), cross-shift continuity (prior-shift open items from v_logbook_truth), buddy mode (per-device wh_voice_buddy_<worker> + 'buddy up with Juan' / 'kasama ko sa shift si Romeo' detector), mention notifications (extends T38 → companion_handoff with status='mention'). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v126';  // bump 2026-05-21: voice-handler.js Phase 4.137-4.146 fourteenth 10-turn flywheel (turns #135-#144, OPERATIONAL EXCELLENCE): health-check ping every 5min to /functions/v1/voice-health (sw_version + ctx), self-test on mount (10 critical helpers verified with console.info), feature flag system (wh_feature_flags table pulled with 5-min cache, per-hive override of build defaults), browser-support banner (mediaDevices/AudioContext/fetch/Promise capability checks + yellow alert banner), network condition adaptation (navigator.connection.effectiveType → lite-payload on slow-2g/2g), memory pressure handler (navigator.deviceMemory + performance.memory with high/medium/low thresholds), server clock drift check (Date header compare, >2min drift exceeded flag), background tab pause (visibilitychange listener), auto-recovery on JS exception (window.onerror catcher scoped to voice-handler / wh-tts), presence heartbeat (60s wh_voice_presence upsert). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v125';  // bump 2026-05-21: voice-handler.js Phase 4.127-4.136 thirteenth 10-turn flywheel (turns #125-#134, MULTI-MODAL + ACCESSIBILITY): camera still capture (getUserMedia environment-facing with no_media_devices fallback), file attachment (image/PDF, 8MB cap, base64 dataUrl), reduced-motion accessibility (prefers-reduced-motion media query + wh_voice_reduced_motion override key), screen-reader aria-live region (polite + atomic + role=status mirroring every reply), keyboard navigation (Escape/Space/Enter/ArrowUp/ArrowDown/Ctrl+H bindings with editable-target guard), color-blind safe palette (red→blue critical, orange→amber high, swappable via data-palette attribute), large-text mode (data-text-size attribute, 1.5x scale), haptic feedback patterns (confirm/success/warning/critical via navigator.vibrate), voice-only mode (UI fades, audio + AT only, PH-aware toggle detector), live captions (visible caption bar overlay, distinct from AT aria-live). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v124';  // bump 2026-05-21: voice-handler.js Phase 4.117-4.126 twelfth 10-turn flywheel (turns #115-#124, COMPLIANCE + DATA GOVERNANCE): PII scrubber ([PHONE]/[EMAIL]/[ID] markers, PH mobile + email + 11-15 digit ID), consent capture (PH Data Privacy Act, wh_voice_consent key, grant/revoke detector), retention enforcement (configurable days, default 180), right-to-erasure (delete-history detector + scoped DELETE + audit log entry), audit CSV export (RFC 4180 quoting + escape), suspicious activity detector (rapid_fire 5-same-intent-in-60s + off_hours_bulk 10+-events-in-quiet-hours), AI disclosure policy (flag + per-session shown tracking + disclosure line), locale-aware date formatting (PH DD/MM/YYYY vs ISO), per-hive monthly cost cap (ai_cost_log aggregate), voice drift advisory (signature record + drift detect — ADVISORY ONLY, never auth). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v123';  // bump 2026-05-21: voice-handler.js Phase 4.107-4.116 eleventh 10-turn flywheel (turns #105-#114, PROACTIVE ASSISTANCE + LEARNING): adaptive PM sync drift detector (logged-PM vs scheduled-next diff), skill-level adaptation (apprentice/standard/senior vocab tiers with RPN/FMEA depth), cross-asset failure-mode pattern detection (>=2 assets in <7d), per-worker intent history (wh_voice_intent_hist_<worker>, 30d rolling, top-3 recurring), session sentiment over time (positive/neutral/negative, 14-day log, persistent-negative escalation), anticipatory asset warm-up (60s cache against v_asset_truth), symptom→failure-mode normalizer (vibration_anomaly/overheat/noise_anomaly/leak/smell/no_start with PH variants), shift-boundary context reset (06/14/22 PHT detector), knowledge-gap logging (ai_knowledge_gap table), mentor-mode handoff (mentor_relay_queue). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v122';  // bump 2026-05-21: voice-handler.js Phase 4.97-4.106 tenth 10-turn flywheel (turns #95-#104, INTEGRATION + AUDIT): audit log emission (ai_audit_log insert on confirmed write actions), quiet hours (22:00-06:00 PHT, non-critical alerts only), action preflight (no_intent / missing_asset_tag / malformed_asset_tag / voice_execute_lock blockers), idle session cleanup (5-min auto-pause via setTimeout), companion-error analytics (per-hive 7-day error counts in wh_voice_errors_<hive>), session tag (per-session label, wh_voice_session_tag_<id>, detector for 'tag this as X'), cross-page deep-link shorthand (<wh-link page=X asset=Y> token build + parse), STT grammar-mangled guess (heuristic flag for 'did you mean'), persona phrase pool (ack/encourage/concern/closing categories, no-repeat-in-a-row), shift-end handover trigger (UTC+8 math against worker shift_end_hour, 30-min margin). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v121';  // bump 2026-05-21: voice-handler.js Phase 4.87-4.96 ninth 10-turn flywheel (turns #85-#94, INPUT NORMALIZATION + ONBOARDING): numeric precision rule (units + 1-decimal cap), asset-tag normalization (pee-two-oh-three → P-203 via _DIGIT_WORDS + _LETTER_WORDS), time-range normalization (this week / yesterday / kahapon / last N days → ISO span), ack-style preference (terse vs warm, persisted to wh_voice_ack_style), forbidden-topic redirect (competitor names + office politics / chismis), mic noise-floor classifier (quiet/normal/spotty/noisy from p50/p90 peaks), conversation pin (per-worker localStorage, capped at 20), help command shortcut (/help and tulungan mo ako), multi-language KPI labels (mtbf/mttr/oee/compliance/availability in Tagalog + Cebuano), new-worker onboarding cue (_isFirstTimeWorker checks voice_journal_entries count + _firstTimeWelcomeLine with 3 sample commands). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v120';  // bump 2026-05-21: voice-handler.js Phase 4.77-4.86 eighth 10-turn flywheel (turns #75-#84, TRUST DEPLOYMENT): toxicity guard (severity 0-1 with severe/mild PH-aware terms, de-escalate anchor), question shape classifier (data/how_to/opinion/troubleshoot/social → reply structure), freshness disclosure ('is this fresh' → last_updated stamp), rate-limit cooldown (per-hive localStorage timestamp, 10-min cap), conversation share link (/voice-journal.html#session=<id>), readback request (TTS replay of prior reply, distinct from T14), scope disclosure (capability list grounded, no inventing), multi-turn correction handler (distinct from T2 negation — redo answer with new info), confidence label tier (high/medium/low from row count + day count), crisis escalation extension (T4 + workplace_violence kind, Safety Officer / HR routing). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v119';  // bump 2026-05-21: flywheel turns 16-25 — index.html auth-form wrapper (password-manager autofill) + 3 explicit button types; achievements.html back-button <a href=javascript:> -> <button>; parts-tracker.html meta-refresh-allow marker; integrations.html Bearer-token password-input-allow; project-manager.html timer-cleanup-allow. Re-prime cache so PWA users get the auth-form + a11y fixes.
// const CACHE_NAME  = 'workhive-shell-v118';  // bump 2026-05-21: voice-handler.js Phase 4.67-4.76 seventh 10-turn flywheel (turns #65-#74, ORCHESTRATION + INTEGRATION): PDF export detector points to Report Sender, per-device pronunciation library, voice-execute safety lock (default OFF), persona portrait animation (idle/listening/thinking/speaking/urgent), cross-hive benchmark RPC fn_cross_hive_benchmark wiring (5-min cache), daily-digest mode (5-line briefing), push notification readiness (capability + permission request), multi-worker concurrency lock (per-hive advisory), accent / voice signature adaptation (tagalog density estimate + persisted pref), streaming SSE indicator. Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v117';  // bump 2026-05-21: voice-handler.js Phase 4.54-4.66 sixth 10-turn flywheel (turns #55-#64, WORKFLOW + PERSONALIZATION): proactive companion turn (open() accepts alert payload), maturity-stair gating (Stair <2 → no predictive promises), per-slot expiry windows (asset_tag 60m / machine_status 30m / time_window 2h), action replay ('same fix on P-205'), language opt-in (tagalog / english / cebuano persisted), brevity preference (brief / full mode), timer follow-up ('remind me in 20 min'), URL-context pre-fill (?asset=P-203 → context_slots), mic quality meter (AnalyserNode warns on low volume), multi-step action queue ('log entry then start PM then notify'). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v116';  // bump 2026-05-21: voice-handler.js Phase 4.44-4.53 fifth 10-turn flywheel (turns #45-#54, RESILIENCE + MEMORY + TRUST OPS): offline degradation tracker, 10-min reply cache (LRU 16), feedback escalation (3+ thumbs-down in 7d → ai_quality_escalation upsert), custom plant terminology fuzzy-match against v_asset_truth, conversation branching stack ('back to the X thing'), multi-modal photo intent (offers Visual Defect Capture), avatar emotion state (urgent/celebratory/concerned/helpful → data-avatar-state attribute), cross-hive anonymised benchmark anchor, summary-on-demand mode, identity drift tracker (warns on worker_name change mid-session). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v115';  // bump 2026-05-21: voice-handler.js Phase 4.34-4.43 fourth 10-turn flywheel (turns #35-#44, COLLABORATION + WELLBEING): action-confirmation detector (write-verb utterances require yes/no before voice-action-router executes), wellbeing nudge on graveyard shift, encouragement anchor for completed PMs / closed logbooks, skill-gap nudge from v_worker_skill_truth, shift-handover mode (structured 4-line block), batch-action parser (log X, Y, Z), explainability anchor (source view + row count + timestamp), co-worker mention detector for logbook tagging, fatigue signal detector (pagod / ayoko / frustrated → softer tone), transcript export detector routes to Report Sender. Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v114';  // bump 2026-05-21: flywheel turns 8 + 12 — logbook.html + inventory.html + dayplanner.html JSON.parse safety wrappers (corrupt localStorage no longer crashes the page); platform-health.html setInterval cleanup on beforeunload + 2 fetch() chains given .catch fallbacks; project-manager.html documented timer-cleanup-allow marker. Re-prime cache so PWA users get the new try/catch wrappers + error handlers.
// const CACHE_NAME  = 'workhive-shell-v113';  // bump 2026-05-21: voice-handler.js Phase 4.24-4.33 third 10-turn flywheel (turns #25-#34, CONTEXT AWARENESS + INTELLIGENCE): shift-context anchor (06:00 / 14:00 / 22:00 PHT with UTC+8 math), repeated-issue surface (chronic machines from v_logbook_truth), standards lookup detector (ISO/SAE/SMRP/IEC/ASHRAE/NFPA), voice command shortcuts (open logbook / show analytics / schedule PM → page nav), AI quality thumbs UI on every reply (persisted to ai_cost_log.quality_rating), worker-discipline biasing in prompt, goodbye detector ('tapos na' / 'yun lang' → clean session end), confidence-calibration anchor (hedge on small samples), long-session pacing (>=10 turns nudges break), proactive-alerts override (critical alerts FIRST sentence). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v112';  // bump 2026-05-20: voice-handler.js + wh-tts.js Phase 4.19-4.23 second 10-turn flywheel (turns #15-#24, TRUST + AUDIO QUALITY + OBSERVABILITY + CROSS-SURFACE): hallucination guard prompt anchor, citation rule, mic-tap interrupts in-flight audio, TTS latency ratchet, ai-gateway rate-limit + fallback UX, acronym SSML spell-out (MTBF/OEE/PM/RPN read as letters), assistant.html cross-surface journal pull, ai_cost_log surfaced, conversation-end ack on overlay close. Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v111';  // bump 2026-05-20: voice-handler.js Phase 4.9-4.18 10-turn flywheel expansion (turns #5-#14): persona-switch utterance, stale-state guard (15-min threshold), topic-interruption signal, thanks/ack short-circuit, asset-context auto-priming from logbook, first-turn greeting, code-switch anchor in prompt, sensitive-topic redirect (HR/legal/financial → supervisor), worker-name personalization with 'kapatid' fallback, repeat-that handler ("ulit nga" replays last reply). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v110';  // bump 2026-05-20: voice-handler.js Phase 4.7 clarification-recovery routing — bare "logbook" / "PM" / "analytics" / "asset hub" replies after the streak-ceiling "what page would help?" prompt now route DIRECTLY to that intent (high confidence, clarification_pending cleared) instead of dead-ending in another clarify loop. Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v109';  // bump 2026-05-20: voice-handler.js Phase 4.5/4.6 dialog continuity — PRIOR TOPIC HANDLE block in the system prompt (pronoun resolution: 'it' / 'that' / 'yan' / 'yun' resolved to the prior intent) + natural-language SLOT ENUMERATION ('You already know: asset tag = P-203') replacing the raw JSON dump. Multi-turn continuity now deterministic. Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v108';  // bump 2026-05-20: voice-handler.js Phase 4.2/4.3/4.4 sister handlers — negation bypass (no / cancel / wala / hindi exits the topic and clears dialog state), noise transcript guard (empty / 1-2 char / "uh" / "um" skips the LLM call and renders "didn't catch that"), clarification-loop ceiling (after 2 consecutive clarifies, switch prompt shape + hard reset). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v107';  // bump 2026-05-20: voice-handler.js Phase 4.1 follow-up affirmation detector ("Yes, the details" bypasses topic-switch UI) + hive.html realtime listeners moved from dead `assets` table to `asset_nodes` + signal-trust fixes (pm-scheduler/index/logbook) + 33 L0 bug-class validators wired. Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v106';  // bump 2026-05-20: canonical drift flywheel turn 11 — 27 v_*_truth views shipped + 70 consumer SELECTs migrated to view reads (HTML + edge fns); inventory.html stockStatus refactored to trust is_low_stock from the view; agent_memory phase-2 collision fixed; voice-handler.js cleared. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v105';  // bump 2026-05-20: AI Prompt Regression L4 — voice-handler.js system prompt now carries the Platform Metric Anchors block (MTBF/MTTR -> ISO 14224, OEE -> ISO 22400-2 / Nakajima, PM -> SMRP, RPN -> IEC 60812, RCM -> SAE JA1011, anomaly -> Z-Score). Re-prime cache for voice answers to be standards-anchored.
// const CACHE_NAME  = 'workhive-shell-v104';  // bump 2026-05-20: Tier-S citation visibility 52% -> 100% — 8 pages now cite their registered standard short_name (marketplace + marketplace-seller-profile + marketplace-seller + skillmatrix + achievements + founder-console + hive maturity-stair). Re-prime cache for the chip text.
// const CACHE_NAME  = 'workhive-shell-v103';  // bump 2026-05-20: massive L2 expansion — 6 dashboards added manifest link (analytics/analytics-report/platform-health/achievements/founder-console/ph-intelligence); asset-hub FMEA cites IEC 60812:2018; hive adoption-risk cites WorkHive Adoption Risk; platform-health verdict cites WorkHive Platform Health. Re-prime cache so PWA users see the chip + manifest fixes.
// const CACHE_NAME  = 'workhive-shell-v102';  // bump 2026-05-20: drift wiring — index.html ops-home Today's One Thing now reads v_amc_truth + v_sensor_truth + v_alert_truth; hive.html pattern-alerts panel + asset-hub anomaly banner now read truth views. Re-prime cache so PWA users see the canonical-wired renderers.
// const CACHE_NAME  = 'workhive-shell-v101';  // 3 truth-view wrappers + OEE RPC
// const CACHE_NAME  = 'workhive-shell-v100';  // bump 2026-05-19: Calm Dashboard hideZeroStat wiring pass — stat-update sites now dim 0/— values across hive (welcome + members + pulse), alert-hub (AMC briefing setStat), asset-hub (asset-360 strip), predictive (4 risk-tier counts), achievements (3 XP stats), founder-console (setStat), platform-health (health-num + streak)
const SHELL_FILES = [
  // Original report-sender shell
  '/report-sender.html',
  '/report-sender-manifest.json',
  // Shared chrome
  '/nav-hub.js',
  '/button-lock.js',
  '/offline-banner.js',
  '/brand_assets/workhive-logo-transparent.png',
  // Phase 2 resilience helpers (shared across worker-critical surfaces)
  '/offline-queue.js',
  '/connectivity-widget.js',
  '/form-autosave.js',
  '/session-timeout.js',
  '/device-fingerprint.js',
  '/onboarding.js',
  '/wh-help.js',
  // Persona Contract Phase 3+4 shared helpers
  '/wh-persona.js',
  '/wh-tts.js',
  // Voice Companion handler (Phase 1-11 orchestrator)
  '/voice-handler.js',
  // Companion Streamline Step B: persona portraits (compressed JPEGs;
  // 12KB each; full-res source PNGs are at /brand_assets/{James,Rosa}.png).
  // Filenames retain the original "james"/"rosa" suffixes after the
  // 2026-05-20 Hezekiah/Zaniah rename — same artwork, same files.
  '/brand_assets/james-256.jpg',
  '/brand_assets/rosa-256.jpg',
  // Worker-critical pages (offline-capable on cached page-shell)
  '/logbook.html',
  '/inventory.html',
  '/pm-scheduler.html',
  '/parts-tracker.html',
  '/shift-brain.html',
  '/asset-hub.html',
  '/hive.html',
];

self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE_NAME).then(cache => cache.addAll(SHELL_FILES))
  );
  self.skipWaiting();
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k)))
    )
  );
  self.clients.claim();
});

// Network-first for API and font requests; cache-first for shell
self.addEventListener('fetch', e => {
  const url = e.request.url;
  if (url.includes('supabase.co') || url.includes('fonts.goog') || url.includes('fonts.gstatic')) {
    e.respondWith(fetch(e.request).catch(() => new Response('', { status: 503 })));
    return;
  }
  e.respondWith(
    caches.match(e.request).then(cached => cached || fetch(e.request))
  );
});
