// WorkHive Service Worker — Phase 2 (multi-page shell, 2026-05-11)
// Enables PWA installability + offline shell across the worker-critical
// surfaces (logbook, inventory, pm-scheduler, hive, asset-hub, shift-brain).
// Closes PRODUCTION_FIXES #54.

const CACHE_NAME  = 'workhive-shell-v283';  // bump 2026-09-04 (38th): whClockSkew now HEADs the SITE ORIGIN (200 + date header) instead of the Supabase REST root -> removes the "401" console error on every page load. Verified locally (HEAD -> /?_clk=, 0 4xx). Supersedes v282's apikey attempt, which did NOT work (the publishable key is not accepted as a bare apikey on the PostgREST root).
// const CACHE_NAME  = 'workhive-shell-v282';  // bump 2026-09-04 (37th): utils.js whClockSkew health-ping - anon apikey attempt (INEFFECTIVE, superseded by v283); the publishable key is not accepted as a bare apikey on the PostgREST root, so the 401 persisted.
// const CACHE_NAME  = 'workhive-shell-v281';  // bump 2026-09-03 (36th): 102-dim rubric fix-wave batch 2 (Ian: 'do the 102-dim') - B3 readability: 6 over-20-word sentences split to <20w each across hive, skillmatrix, community, achievements, ai-quality (+ integrations wizard intro in v280). Objective long-sentence findings from the live family_rubric_sweep, fixed at source.
// const CACHE_NAME  = 'workhive-shell-v280';  // bump 2026-09-03 (35th): 102-dim rubric fix-wave (Ian: 'do the 102-dim') - integrations wizard intro split from one 29-word sentence into three <20w (B3); logbook 'Log Your First Repair' CTA to 44px min-height (F1). Vehicle-lane rubric findings from the family_rubric_sweep, fixed at source.
// const CACHE_NAME  = 'workhive-shell-v279';  // bump 2026-09-03 (34th): VD12/13 fn hardening (deployed via edge, shell unchanged but bump keeps clients aligned) - the SheetJS xlsx path (VD12) no longer emits CSV-fragment noise parts ('Oil Filter,90915'): coerce drops comma-split cells + PART_TOKEN now catches digit-leading OEM numbers (90915-YZZE1); live walk 14-noisy -> 8-clean parts. docx/mammoth path (VD13) extracts prose intervals exactly.
// const CACHE_NAME  = 'workhive-shell-v278';  // bump 2026-09-03 (33rd): assistant.html (shell) - VP-G walk: a fresh vehicle owner (car + PM schedule, no logbook entry yet) was told 'you don't have any records yet'; the grounding check counted only v_logbook_truth. Now counts assets + PM scope (solo lane included), and a positive signal wins over an unknown logbook read -> 'I can see your job records' with grounded prompts.
// const CACHE_NAME  = 'workhive-shell-v277';  // bump 2026-09-03 (32nd): VP-A solo-lane fix batch - logbook '1 asset(s)' singular; dayplanner 'Due from your assets' (plant said to a car owner); public-feed CTA/subtitle now ask the session (signed-in was told to sign in); hive return-banner shows the passive intent line pre-membership (the Continue link only looped); index signed-in CTA swap (inert on the settled page - the flash was pre-session paint); RPC get_pm_compliance_smrp gains the solo lane (migration 20260903000001).
// const CACHE_NAME  = 'workhive-shell-v276';  // bump 2026-09-03 (31st): integrations.html (shell) - VD15's fleet-lane fix: number-less doc parts no longer 23505 the whole create in a hive (the (part_number,hive_id) unique index saw two '' as duplicates; NULL is refused by NOT NULL; partial index would break the import upsert) - the part NAME stands in as the number, visible and editable, notes say so.
// const CACHE_NAME  = 'workhive-shell-v275';  // bump 2026-09-03 (30th): integrations.html (shell) - VD11's walk finding: the doc-upload zero-case no longer says "Found 0 ... review them in the next steps" (nothing to review); it says what to DO ("upload just the maintenance-schedule or parts-list pages - the template below still works"). Also this wave's fn hardening (model-row sanePmText guards, dedup, folding) verified across three live uploads: 30 junk rows -> 5 (3 perfect).
// const CACHE_NAME  = 'workhive-shell-v274';  // bump 2026-09-03 (29th): logbook.html (shell) - THE IDLE STORM: yesterday's T9 goal-bar repaint (updateStatPills -> renderEntries(false)) closed a cycle with renderEntries' pre-existing tail call back into updateStatPills, firing the two head-count queries at ~90 req/s forever in mine-mode (6,700 idle requests in 75s, measured quiet). fromStatPills param breaks the new edge; idle-network now 12 requests TOTAL across 8 pages.
// const CACHE_NAME  = 'workhive-shell-v273';  // bump 2026-09-03 (28th): analytics.html (shell) - dialog-floor 320: the diagnostic failure-signature header row gains flex-wrap so the nowrap "N machines - M occurrences" count pill drops whole to its own line instead of overflowing the 282px panel by 3.3px (42/42 dialogs now fit the floor).
// const CACHE_NAME  = 'workhive-shell-v272';  // bump 2026-09-03 (27th): integrations.html (shell) - VD wave: doc-path rows that arrived in MILES render their provenance beside the converted km ("your document says every 7,500 mi; converted") - the fn's new interval_unit/interval_orig fields, exercised by the LEAF fixture; envelope-aware response parse (fn adopted _shared/envelope.ts; legacy flat shape still parses so a cached shell cannot break).
// const CACHE_NAME  = 'workhive-shell-v271';  // bump 2026-09-03 (26th): hive + inventory (shells) - fast-suite coherence wave: hive roster filter gains its role-check-allow annotation (member DB field, not ambient role); inventory's out-branch lead/low notes drop their em-dashes (ratchet back to 0). Non-shell same wave: ToS em-dash, marketplace-admin oldest-draft order gains .order('id') tiebreaker (limit(1) totality).
// const CACHE_NAME  = 'workhive-shell-v270';  // bump 2026-09-03 (25th): hive + inventory (shells) - CI domain-truth retired from red-by-design to PASS (25 stated / 0 missing): hive's stock tile number now matches the 'low on stock' label it carries (inventory's low definition; the F5 union still drives the amber state + verdict, out-of-stock named on the CTA line) -> CI8 agree 2=2; inventory's out-branch action (which WINS whenever anything is out) now names the reorder threshold for the low remainder and the real longest lead time (or says none is recorded) -> CI1+CI2 stated.
// const CACHE_NAME  = 'workhive-shell-v269';  // bump 2026-09-03 (24th): logbook.html (shell) - the entry cards (list + open-entries rail) are REAL controls now: role=button + tabindex + Enter/Space open + aria-label naming the entry. The modal-escape prover measured Escape-close working but focus falling to BODY - the opener was an unfocusable div, so whModalA11y's lastFocus never held it; a keyboard user could not even reach the cards. Focus now returns to the exact card (prover: 10/10 focus-restores).
// const CACHE_NAME  = 'workhive-shell-v268';  // bump 2026-09-03 (23rd): integrations + asset-hub + hive + utils.js (shells) - ratchet wave 2: wizard labels wired for= + scope radios aria-labeled (ux-contract 0 unlabeled), wizard radii -> var(--wh-radius-sm) via .veh-box/.veh-chip (design-tokens 260=baseline), asset-hub head-counts + pending chain carry in-chain .limit (unbounded 0), utils whEmbedEntry fallback fetch wrapped (fetch-ratchet 0), hive amc -> v_amc_truth. canonical_registry regenerated (vehicle_meta/interval_km/trigger fns now known: query-column + trigger-existence PASS).
// const CACHE_NAME  = 'workhive-shell-v267';  // bump 2026-09-03 (22nd): board-red wave fixes across 7 shells - em-dash purge (21 displayed literals -> plain dashes, ratchet 0/0), wizard failure copy routed through whWriteError/whReadError (taxonomy held 19), vehUndoCreate gains the cascade-naming whConfirm (T139 held 0), asset-hub km/L reads v_logbook_truth + hive amc count reads v_amc_truth (canonical L2 + KPI + calm all green), pm-scheduler km-line dash. md twins rebuilt (62) + substrate rebuilt (578 chunks) ride along.
// const CACHE_NAME  = 'workhive-shell-v266';  // bump 2026-09-03 (21st): integrations.html (shell) - #toast moved FIRST in .page (position-fixed, so order is invisible): the wizard's role=alert validation line was shadowing the probes' 'querySelector(#toast,.toast,[role=alert])' contract - the import-undo prover read '' where the real toast held the removed-rows count. Also analytics.html (shell): the generated d.insight paragraph gains max-width:70ch (the width gate caught a 78ch generated line running the card's full width).
// const CACHE_NAME  = 'workhive-shell-v265';  // bump 2026-09-03 (20th): project-manager + shift-brain + voice-journal (shells) - counted-noun ratchet reds from the board: 5 new bare-plural sites gained singular branches ('1 item', '1 progress log', '1 asset is', '1 entry'); ratchet lowered 16->14.
// const CACHE_NAME  = 'workhive-shell-v264';  // bump 2026-09-02 (19th): integrations.html (shell) - VEHICLE SEED VM2: the doc-upload path opens BEHIND the measured accuracy gate (vehicle-extract-accuracy: 12/12 exact intervals, 8/8 exact part numbers, injection stripped, on the deterministic miner floor). Scoped-pages upload (pdf/docx/xlsx/csv/txt, resume.html's client extraction) -> vehicle-doc-extract proposes -> rows land BADGED 'FROM YOUR DOC' in the same editable checklists (extraction proposes, the person confirms); km-only manual rows seed interval_kind 'meter' so a 100,000-km service gets no false yearly calendar half; honest status line reports partial reads + stripped injection lines + miner-only fallback.
// const CACHE_NAME  = 'workhive-shell-v263';  // bump 2026-09-02 (18th): integrations.html (shell) - VEHICLE SEED VM10 sweep fixes: 44px label-wrapped checklist checkboxes + 44px scope radios + Cancel width (tap-target floor, measured at true 390px); whRequireOnline guard on Create (a 4-table seed has no offline queue - say so up front); pre-paint .wh-nonsup role class kills the console-strip layout shift (CLS 0.17 -> 0.001 measured, battery 0 defects 0 major).
// const CACHE_NAME  = 'workhive-shell-v262';  // bump 2026-09-02 (17th): integrations+pm-scheduler+asset-hub (shells) - VEHICLE SEED VM9 two-home: the wizard gains a fleet/personal scope choice for hive members (workers lock to personal - pm_assets_insert_guard refuses worker hive-inserts, so the choice would fail at Create); pm-scheduler and asset-hub hive modes carry the member's OWN personal vehicles alongside (.or hive,null - the logbook precedent; RLS keeps other members' personal rows out); asset-hub scopeHive same, so a personal car's 360 stats/timeline read its hive-less history in hive mode.
// const CACHE_NAME  = 'workhive-shell-v261';  // bump 2026-09-02 (16th): asset-hub.html (shell) - VEHICLE SEED iteration 2 (VM5): the Vehicle 360 card computes FUEL ECONOMY from the vehicle's own fuel logs (full-to-full: distance between consecutive fills / litres at the later fill, averaged; pill appears only with >=2 complete fills - one fill claims nothing, honest-empty).
// const CACHE_NAME  = 'workhive-shell-v260';  // bump 2026-09-02 (15th): pm-scheduler.html (shell) - VEHICLE SEED iteration 2 (VM4): the due sentence gains its METER half ('due at 20,500 km · 7,450 km away · whichever comes first'; red when over, yellow within 500 km, honest 'no odometer reading yet' when meter unknown) + completions stamp meter_at_completion so next_due_km advances (without it a completed km-PM re-reads overdue at the old mark). The view already OR'd km into the badges - now the label explains the alarm.
// const CACHE_NAME  = 'workhive-shell-v259';  // bump 2026-09-02 (14th): logbook.html (shell) - VEHICLE SEED iteration 2: SOLO lane through the hive gate (signed-in owner without a hive passes - mine-mode was already worker-scoped, asset picker had the solo branch since Phase 5; session required so a stale worker name without auth still gates) + the 'Vehicle' discipline category unlocking the odometer_km/fuel_l reading templates that roll the vehicle meter. Also covers integrations.html post-v257 honesty edits (undo reports partial failures; yearAgo UTC fix).
// const CACHE_NAME  = 'workhive-shell-v258';  // bump 2026-09-02 (13th): asset-hub.html (shell) - VEHICLE SEED iteration 1: the SOLO lane (a hive-less signed-in owner sees their own assets - scopeNodes/scopeHive swap the scope key, hive gate no longer walls solo, hive-industrial panels stay dark) + the Vehicle 360 card (vehicle_meta pills: plate/VIN/odometer/renewals). Walked live: gate gone, Ranger 360 complete, 0 console errors. Without this bump installed PWAs keep the hive-wall for solo owners.
// const CACHE_NAME  = 'workhive-shell-v257';  // bump 2026-09-02 (12th): integrations.html (shell) - VEHICLE SEED iteration 1: the Add-a-Vehicle wizard (Ford Ranger 2026 XLT preset -> editable schedule/parts checklist -> seeds pm_asset('Vehicles') + asset_node(+vehicle_meta) + km scope items + starter inventory, with receipt + undo). Lives INSIDE .page but OUTSIDE the supervisor gate, which now spares #vehicle-add instead of nuking <main> - solo car owners are never supervisors.
// const CACHE_NAME  = 'workhive-shell-v256';  // bump 2026-09-02 (11th): pm-scheduler.html (shell) - VEHICLE SEED iteration 1: the 'Vehicles' PM category + its 14-task template block (Ian's manufacturer-interval table: daily walk-around, 5k general, 10k oil/filter, 20k major, 40k transmission/brake, 100k major, tires/battery/registration/insurance). A car is an asset - lane, not silo. Without this bump installed PWAs keep a scheduler with no vehicle vocabulary.
// const CACHE_NAME  = 'workhive-shell-v255';  // bump 2026-09-02 (10th): logbook.html (shell) - T32 lineage chip: a PM-echo entry's detail now carries 'from PM Schedule -> view tasks' linking pm-scheduler.html?asset=<machine> (was a non-interactive 'via PM Scheduler' marker; verified live -> ?asset=BLR-001). An auditor can hop echo -> schedule without hand-searching.
// const CACHE_NAME  = 'workhive-shell-v254';  // bump 2026-09-02 (9th): hive.html + index.html + logbook.html (all shell) - three S2 fixes: T20 dwell-age on approval cards ('N days waiting' past a week; a 44-day CRITICAL approval no longer looks fresh), T19 the Risk Alerts tile deep-links alert-hub.html?kind=risk (filter context carried, was a bare page), T15 team search term-ANDs multi-word queries ('bearing temperature' now finds 3 where it found 0 - each term matches any field, chained ors AND). Without this bump installed PWAs keep all three old behaviors.
// const CACHE_NAME  = 'workhive-shell-v253';  // bump 2026-09-02 (8th): pm-scheduler.html — SHELL — T10 Q2 a11y fix: same-model assets now carry DISTINCT accessible names (the tag - unique per hive - or location joins the card's aria-label; verified live: 0 duplicate labels, 'Open PM details for Donaldson Torit DFO 4-32, tag DC-001'). A screen-reader user can finally tell two physical units apart.
// const CACHE_NAME  = 'workhive-shell-v252';  // bump 2026-09-02 (7th): utils.js + pm-scheduler.html (both shell) - T10 AI4 fix: whEmbedEntry retries a failed RAG-index write once then queues it persistently (wh_embed_retry, drained on a later load; verified live against the down edge runtime: double-fail queued the payload intact, mocked-ok drain sent without re-queueing); pm-scheduler's fault-mirror routes through it. A 500 during a save no longer silently loses the entry from the assistant's recall.
// const CACHE_NAME  = 'workhive-shell-v251';  // bump 2026-09-02 (6th): pm-scheduler.html — SHELL — T21 category-prefill fix: TYPE_TO_CATEGORY now speaks the data's REAL iso_class vocabulary (Mechanical/Electrical/Pneumatic/Instrumentation/Hydraulic + legacy case via the _typeToCategory resolver; the old machine-word keys matched nothing, so pick-from-registered left the required Category empty for ~every asset). Verified in-page across the whole vocabulary. Without this bump an installed PWA keeps the always-empty prefill.
// const CACHE_NAME  = 'workhive-shell-v250';  // bump 2026-09-02 (5th): hive.html — SHELL — the approval badge now counts ALL pending decision types (assets/parts + FMEA modes + strategies + pending AMC shift briefings, each linked to its review surface; verified live: badge=34 where the T20 walk saw 4-of-34). Without this bump an installed supervisor keeps the undercounting board.
// const CACHE_NAME  = 'workhive-shell-v249';  // bump 2026-09-02 (4th): utils.js — precached SHELL dep — gained whModalHistory (T42: hardware Back now closes an open modal in place instead of leaving the page and losing the worker's form; inventory's part-modal is the first wired consumer, verified live both directions). Without this bump an installed PWA keeps the v248 utils.js where Back exits the page mid-form.
// const CACHE_NAME  = 'workhive-shell-v248';  // bump 2026-09-02 (3rd): pm-scheduler.html — a SHELL file — changed after the v247 bump (T10 stale-render fix: completing a PM now refetches v_pm_scope_items_truth and repaints the detail from the fresh row, so a just-completed task stops reading '39d overdue'; verified live 'Last done: Sep 2 - Next due: Sep 9'). Without this bump an installed PWA keeps the v247 copy whose detail repaints stale in-memory dates after a completion.
// const CACHE_NAME  = 'workhive-shell-v251';  // bump 2026-09-02 (5th): logbook.html (T9 cap-as-total: 'Jobs closed out' bar now uses TRUE worker-scoped count:exact totals, not the ~200-row load window that read '200 of 200' for a 314-entry worker) + the inventory ledger actor-attribution is a DB fn (no shell change).   // bump 2026-09-02 (4th): hive.html again (T56: a supervisor leaving a hive that KEEPS another active supervisor now gets an honest one-tap confirm naming the co-supervisor, instead of a forced hand-over modal whose premise - 'without a supervisor, no one can manage' - was false in the co-sup case). Same batch: the branch reads window._memberRoster (membersData was loader-local - caught live as a ReferenceError before banking).
// const CACHE_NAME  = 'workhive-shell-v248';  // bump 2026-09-02 (3rd): shell batch - hive.html (T65: a past-horizon prediction no longer headlines as live forecast - 'was predicted to fail by <date> - past due; check recent entries and rerun' + the C12 whole-load approval badge), logbook.html (C7 toast queue + L2 FIL guidance labels + T49 mine-export filter parity), index.html (T46 plant-clock greeting), utils.js (T42 modal-back contract, C11 reconciler auto-wire, T39 neutral quota voice). Without this bump an installed PWA keeps v247 copies - my own walk just proved it: the T65 fix was served by the web server but the SW kept handing out the cached page.
// const CACHE_NAME  = 'workhive-shell-v247';  // bump 2026-09-02 (2nd): utils.js — a precached SHELL dep — changed after the v246 bump: the AI rate-limit voice is now audience-neutral ('The AI is at its limit right now' replaces 'You have hit the AI rate limit' in EN+FIL, all three retry-window variants) because the exhausted window is usually the GLOBAL platform budget and the old voice blamed the worker for platform demand (critic walk T39). Without this bump an installed PWA keeps the v246 utils.js and never receives the corrected voice. Same batch: logbook.html T9 cap-as-total fix (the 'Jobs closed out' strip now counts the TRUE worker totals from count:exact, not the row-capped loaded window) and the goal-gradient strip wiring it rides on. Same batch: logbook.html (shell) mine-branch CSV export now honors the active filter bar exactly as the team branch does (T49 - the same button no longer behaves two ways). And utils.js again: whModalA11y now traps hardware-Back (T42 - Back dismisses the open modal instead of exiting the page mid-form; every wired modal inherits it). And hive.html (shell): the approval badge now counts the WHOLE review load (assets+parts+FMEA+strategies, 4->32 for Lucena) with an 'Also awaiting your review in Asset Hub' line - C12's board half.
// const CACHE_NAME  = 'workhive-shell-v246';  // bump 2026-09-02: hive.html — a SHELL file — changed after the v245 bump (T186 quiet-workers drift panel added to the team-pulse board: a supervisor's roster now names workers with no logged activity for 7+ days instead of leaving retention drift invisible; same batch: one displayed em-dash in the maturity how-it-works copy became a colon for the Arc-P ratchet); logbook.html T29 chain-break fix (supervisor re-init no longer wipes a deep-linked team search; browse-only 7-day default); Cluster-1 clock fixes (logbook formatDate one-clock, index shift line plant-anchored PHT). Without this bump an INSTALLED PWA keeps serving the v245 hive.html and never receives either.
// const CACHE_NAME  = 'workhive-shell-v245';  // bump 2026-08-31: three SHELL files changed after the v244 bump date (gate-determined by parsing SHELL_FILES mtimes, not memory): inventory.html now DECLARES the canonical global HIVE_NAME (`let HIVE_NAME = localStorage.getItem('wh_hive_name')||''`) alongside HIVE_ID/HIVE_ROLE — it had been used typeof-guarded but never declared, which dom-refs flags as an undefined-canonical-global; pm-scheduler.html and report-sender.html also changed earlier 2026-08-31. Without this bump an INSTALLED PWA keeps the v244 copies and never receives them.
// const CACHE_NAME  = 'workhive-shell-v244';  // bump 2026-08-28 (T149/T144/T126): nav-hub.js — a SHELL file — changed again AFTER the v243 bump, three times. (1) T149: the community badge counted FLAGGED posts, which RLS hands to a member but the feed refuses to show, so a moderated post kept advertising itself as unread to every worker; the count is now role-aware. (2) T144: the badge was computed once per page load and never again, so a worker who read the posts in one tab kept being told they were new in another; a debounced `storage` listener converges it. (3) T126: `online` repainted only the connectivity pill, so a display that lost and regained its link kept an hours-old count; reconnect now re-checks. Without this bump an INSTALLED user keeps serving the v243 copy and gets none of them — the April stale-nav incident's exact shape.
// const CACHE_NAME  = 'workhive-shell-v243';  // bump 2026-08-28 (T55/T189): two SHELL files changed after v242. nav-hub.js — the seller's own dashboard (marketplace-seller.html) had NO registry entry at all, so it was missing from the All Tools grid AND unfindable by search, which reads this same registry; "My Listings" is now registered, and for a supplier that page is their whole platform. voice-handler.js — the companion's plant grounding was blind to SKIPPED PMs (the compliance view had been counting them as completions), so it answered "how are we doing on PMs?" with a strictly rosier plant than exists; it now carries an explicit PM SKIPS block stating that a skip is recorded non-performance. Determined by parsing SHELL_FILES rather than by memory: of the twelve files edited this turn exactly these two are precached (asset-hub.html and pm-scheduler.html appear elsewhere in this worker but are NOT in the 31-entry list, and search-overlay.js is not precached either). Without this bump an installed device keeps a nav that cannot reach the seller dashboard and a companion that cannot see a skipped PM.
// const CACHE_NAME  = 'workhive-shell-v242';  // bump 2026-08-28 (T160/T44): the SHELL was carrying ~4.2 MB of images to render small avatars and a 260px logo. brand_assets/hezekiah.png and zaniah.png are 1254x1254 masters (2016 KB + 1997 KB) and BOTH were precached - wh-persona.js's own comment had described 256x256 progressive JPEGs 'at 12KB each' since the beginning, but those files were never created, and a 2026-07-03 fix for the resulting 404 repointed at the masters instead. They exist now (9.6 KB + 9.8 KB, no alpha in the source so JPEG was always right) and the shell precaches THEM. The logo went 1024px/229 KB -> 640px/81 KB, still 2.5x its largest real display (260px, found by scanning every sized render rather than assuming the 80px hero was the biggest). Net: ~4.05 MB off every PWA install. Without this bump an installed device keeps precaching the masters and never sees the derivatives.
// const CACHE_NAME  = 'workhive-shell-v241';  // bump 2026-08-27 (T23): report-sender.html — the ONE app page in SHELL_FILES — now states each report's WINDOW on its chip ("Shift Handover · last 8 hours", "Predictive · last 90 days"). An installed PWA serves the CACHED copy, so without this bump the people most likely to send a weekly pack would keep choosing blind. Caught by checking which edited files are in the shell rather than by remembering.
// const CACHE_NAME  = 'workhive-shell-v240';  // bump 2026-08-26 (T105): notificationclick now honours the push's DESTINATION - it matched an open tab on PATH only and returned focus, so a push aimed at ?tab=services landed a provider on whatever tab they already had open. Without this bump installed PWAs keep the worker that drops the deep link. Prior note (v239, 2026-08-25, T44): nav-hub.js (SHELL) now registers THIS service worker centrally with a derived root ('/workhive/' local, '/' prod). Before it, exactly ONE root-scope register() existed — on report-sender.html, a supervisor page — so a worker who installed the PWA from index got NO shell precache, NO offline-fallback navigation shell, and `serviceWorker.ready` hung forever on every other page (the marketplace-seller push-alerts hang was this hole). marketplace-seller's own hardcoded '/workhive/sw.js' registration (a 404 in prod, where the prefix does not exist) now derives the same root. Without this bump an installed PWA keeps the nav-hub that never registers the worker.
// const CACHE_NAME  = 'workhive-shell-v238';  // bump 2026-08-24 (T2/T8): session-timeout.js (SHELL) now carries ?return=<current page+params> on the idle hard-clear redirect, so a re-auth after expiry lands the person back on the page they were working — index's resolver + both submit paths honor the param (T1). Without this bump an installed PWA keeps the build that dumps every expired session on the dashboard with the task lost. (The same release's 38 per-page identity-gate redirects got the same contract via utils.js whSignInWall — utils.js is NOT precached, so the bump is for session-timeout.js alone.)
// const CACHE_NAME  = 'workhive-shell-v237';  // bump 2026-08-23: report-sender.html (the one SHELL page in this release) now composes its contacts-read failure through whReadError - a 401 says "session expired, sign in again", a 429 says wait, instead of blaming the connection for all three - and its _rsReadFailed flag carries the ERROR OBJECT so the taxonomy has something to read. Without this bump an installed PWA keeps the build whose failure copy prescribes the wrong remedy on the one page whose primary action is outward and irreversible.
// const CACHE_NAME  = 'workhive-shell-v236';  // bump 2026-08-10: inventory.html closes the two surfaces its earlier fix did not reach. The hero tiles and verdict were already honest under a failed read ("Stock levels are unknown right now, not zero"), but stat-total / stat-low / stat-out still printed "0 parts / 0 low / 0 out" beside that sentence, and the part-modal's asset linker still said "No assets registered. Register assets in the Logbook first." while the assets read was merely PENDING - an instruction to go and duplicate an asset register that already exists. Now: those three pills dash on a failed read, #empty-state ships hidden so only a successful render may claim "No parts in inventory yet", and the asset linker distinguishes three states (loading / could-not-load / genuinely empty) using a new _assetsReadFailed + _assetsLoaded pair, since _assetReadErr was captured at the load site but only console.warn'd. CORRECTION, same as v234: inventory.html is not in SHELL_FILES either, so this bump re-primes nothing that was stale. The fixes are real and verified in the browser; only the cache justification was wrong.
// const CACHE_NAME  = 'workhive-shell-v235';  // bump 2026-08-10: report-sender.html stops reporting a failed contacts read as "0 contacts". It already fell back to the localStorage copy on error but never SAID so, and when that copy was empty the surface read "Saved contacts 0 · No contacts saved yet, add one above" beside rs-reports-hero=0 / rs-recipients-hero=0 / rs-contacts-hero=0 — on the one page in the roster whose primary action is outward and irreversible, where "0 recipients" invites a duplicate contact or the conclusion that a finished report has nowhere to go. Now: the three heroes ship as an em dash, a failed read with an empty backup says "Could not load your contacts — this is a connection problem, not an empty contact list" with a working Retry, and a fallback that IS used is LABELLED "Showing your saved copy — could not reach the server". Without this bump an installed PWA keeps the build that silently presents a stale copy as live truth.
// const CACHE_NAME  = 'workhive-shell-v234';  // bump 2026-08-10: logbook.html no longer tells a worker with 516 entries that they have none. Measured offline with this very cache warm — the render aborted, the markup defaults survived, and the page showed "0 entries · 0 machines · 0 open" beside "No entries yet. Log your first repair to get started."; an injected 500 produced the same screen. Three changes: the three stat pills now SHIP as an em dash instead of 0 (an unknown count is not zero), #empty-state now ships HIDDEN so only a successful render may assert it, and a persistent #read-failed-state with a working Retry (renderEntries(true) re-issues the read) replaces the toast that dismissed ~154ms after load. Also fixes updateStatPills' `?? _allEntries.length` fallback, which invented a number because supabase-js RESOLVES a failed request rather than throwing, so the catch never ran. CORRECTION, verified after the fact: logbook.html is NOT in SHELL_FILES (30 entries; of the nine pages edited this turn only report-sender.html is precached), so this bump was not required and an installed PWA was never serving a cached logbook. The page in the offline reading came from the browser's HTTP cache, not this worker's precache - the 516-to-0 measurement stands, the mechanism first attributed to it did not. Kept as a no-op re-prime rather than rewritten, because renumbering a shipped CACHE_NAME is worse than an over-cautious bump.
// const CACHE_NAME  = 'workhive-shell-v233';  // bump 2026-08-06: the live-MCP walk's fixes touched four SHELL pages and utils.js, so an installed PWA would keep serving the broken versions. community.html (the Announcement lock now states WHY it is locked and releases the forced "share publicly" tick when the reason lifts — without this bump a supervisor keeps the build where a hive-only post silently publishes to every hive); platform-actions.html (the GCash top-up button announces itself mid-write and restores on every path, plus the admin gate stops showing a database table name to someone who is not an admin); marketplace.html + marketplace-seller.html + utils.js (whQueryTimeout wired into the three surfaces that had NO read timeout, so a hung read ends in "Couldn't load…" with a retry instead of an eternal skeleton); public-feed.html (what-happens-next copy, EN + FIL). Also clears the debt this bump had not covered: tokens.css, components.css, nav-hub.js, connectivity-widget.js and voice-handler.js were all committed after the v232 worker.
// const CACHE_NAME  = 'workhive-shell-v232';  // bump 2026-08-03: credits economy close-out - marketplace.html (receipt OCR logging + iOS-zoom input sizes + copy), marketplace-seller.html (truth-view read + OCR logging), platform-actions.html (feedback triage lifted here, CLS fix, contrast, safe-area), plus components.css / wh-persona.js / voice-handler.js restored after the conflict-marker incident. Without this bump a PWA user keeps the pre-fix shell.
// const CACHE_NAME  = 'workhive-shell-v231';  // bump 2026-08-03: the MONEY SCREEN and the identity fix — marketplace.html gains 'Confirm payment & release' (the settle button had been DEAD since the money spine made a payment record mandatory and svcSettle never wrote one), its Filipino strings, and the distinct online-provider count; utils.js fixes restoreIdentityFromSession, which was bouncing every multi-hive worker to the sign-in screen on cold load; alert-hub.html settles the JWT before the identity read. ALSO clears a pre-existing staleness debt this bump had not covered: report-sender.html and voice-handler.js were committed 2026-07-31 against a worker last bumped 2026-07-30, so installed PWAs were serving stale copies of both. Without this bump a PWA user keeps a settle button that cannot work.
// const CACHE_NAME  = 'workhive-shell-v230';  // bump 2026-07-29: SERVICE_HAILING close-out — SHELL pages changed: marketplace-seller.html (P6 second-direction "Rate client" on finished jobs + L-layer error capture + ledger read moved to v_service_credit_ledger_truth), marketplace.html (D14 tab relabel Jobs->Hiring), founder-console.html (top-up queue reads v_service_credit_topups_truth, N+1 provider lookup dropped), achievements.html (§1c provider-tier card). Without this bump installed PWAs keep the stale pages and never see the second review direction.
// const CACHE_NAME  = 'workhive-shell-v229';  // bump 2026-07-29: SERVICE_HAILING P5-P9 — sw.js gains the Web Push handlers (push → showNotification, notificationclick → focus the provider console); SHELL pages pm-scheduler.html (P9 recurring-contract Hail-a-specialist CTA) also changed this commit. Without this bump installed PWAs keep the handler-less worker and stale pages.
// const CACHE_NAME  = 'workhive-shell-v228';  // bump 2026-07-28: SERVICE_HAILING P3+P4 — SHELL pages hive.html (hive-provider home card + TL dict) and asset-hub.html ("Hail a specialist" asset-context CTA, moat #1). Without this bump PWA users keep the stale board/detail and never see the provider doors.
// const CACHE_NAME  = 'workhive-shell-v227';  // bump: a severity-9 safety failure mode is no longer ranked below a low-severity nuisance by RPN, and an expired parts recommendation can no longer be staged - without this bump an installed user keeps an FMEA list that buries the electrocution risk under the alignment fault, and a Stage button on a risk assessment the system already considers stale
// const CACHE_NAME  = 'workhive-shell-v226';  // bump: on a shared tablet one worker's queued PM no longer drains under another worker's name - without this bump an installed user keeps the misattribution
// const CACHE_NAME  = 'workhive-shell-v225';  // bump: creating a PM asset is supervisor-gated at the database and the RCM push routes through an RPC - without this bump an installed user keeps a direct insert the database now refuses
// const CACHE_NAME  = 'workhive-shell-v224';  // bump: filtering the PM list to nothing no longer tells a 31-asset hive it has no assets - without this bump an installed user keeps the wrong empty state
// const CACHE_NAME  = 'workhive-shell-v223';  // bump: asset renames propagate through an RPC so pm_assets can be supervisor-gated - without this bump an installed user keeps a direct write the database now refuses, and renames stop reaching PM Scheduler
// const CACHE_NAME  = 'workhive-shell-v222';  // bump: the hive board's overdue count says assets, which is what it counts - without this bump an installed user keeps copy that under-states the work
// const CACHE_NAME  = 'workhive-shell-v221';  // bump: the at-the-asset completion control is a 44px target and the summary row no longer shifts - without this bump an installed user keeps the 36px button
// const CACHE_NAME  = 'workhive-shell-v220';  // bump: an offline PM completion retried after a lost response is no longer dead-lettered as stuck - without this bump an installed user keeps a queue that reports saved work as stuck
// const CACHE_NAME  = 'workhive-shell-v219';  // bump: deleting a PM asset is supervisor-gated at the database and confirms its own write - without this bump an installed user keeps a page that reports a refused delete as done
// const CACHE_NAME  = 'workhive-shell-v218';  // bump: analytics no longer claims a saved snapshot was recomputed live - without this bump an installed user keeps a chip that overstates how fresh the numbers are
// const CACHE_NAME  = 'workhive-shell-v217';  // bump: one shared interval->frequency mapping in utils.js - without this bump an installed user keeps the import that turns a daily PM into a weekly one
// const CACHE_NAME  = 'workhive-shell-v216';  // bump: the PM card now shows on-time delivery beside SMRP compliance - without this bump an installed user keeps the shell that shows only the flattering number
// const CACHE_NAME  = 'workhive-shell-v215';  // bump: the offline queue no longer reports a lost edit as synced, and logbook stops offering writes the database refuses - without this bump the PWA would keep serving the stale offline-queue.js and none of it would reach an installed user
// const CACHE_NAME  = 'workhive-shell-v214';  // bump: rename is single-flight locked and its failures are now LOGGED as well as shown (three gates caught my own new code: P7 double-submit, Layer-L show-but-do-not-log, and an em dash in user copy)
// const CACHE_NAME  = 'workhive-shell-v213';  // bump: hive RENAME ships (supervisor-only, RLS already allowed it) and the supervisor menu now RETRACTS when you switch into a hive where you are a worker - it used to stay on screen, invite-code button included
// const CACHE_NAME  = 'workhive-shell-v212';  // bump: a supervisor who was PROMOTED (or signed in on a new device) saw an empty invite-code panel that still said 'share this code with your team' - the code is now fetched from v_hives_truth when the local cache is empty
// const CACHE_NAME  = 'workhive-shell-v211';  // bump: entering the code of a hive you are ALREADY in no longer shows the new-member welcome screen - it says so and lands you on your board
// const CACHE_NAME  = 'workhive-shell-v210';  // bump: role adoption is now centralized in applyHiveRole() - seven places set the role and only two repainted, so joining a hive where you are a worker while holding supervisor paint kept the supervisor layout (4th door onto the same defect)
// const CACHE_NAME  = 'workhive-shell-v209';  // bump: switching hive now re-derives the role from the SERVER (it adopted the cached role and never repainted, so switching into a hive where you are a worker kept supervisor chrome and hid your own work card); a switch into a hive you were removed from is refused and drops the stale entry
// const CACHE_NAME  = 'workhive-shell-v208';  // bump: the supervisor paint marker no longer outlives the role (a demoted worker was losing their own work card + PM/stock alerts), and wh-roles.js now understands the 'worker' role it was silently treating as permissive
// const CACHE_NAME  = 'workhive-shell-v207';  // bump: hive board now reconciles the MEMBERSHIP LIST on every load - a hive you were added to after sign-in was invisible in the switcher until you signed out
// const CACHE_NAME  = 'workhive-shell-v206';  // bump: J21 lens walk of the new review form - the sentence explaining how the score works moved 0.68rem -> 0.72rem, since it is load-bearing for the decision to post, not an incidental hint
// const CACHE_NAME  = 'workhive-shell-v205';  // bump: the review flow ships - buyers with a real inquiry can now write a review, so a seller can finally EARN a rating in-product; unverified reviews are shown but never move the score
// const CACHE_NAME  = 'workhive-shell-v204';  // bump: MK13 - the seller profile no longer promises 'Reviews will appear here after buyers submit them' when no review-submission UI exists anywhere in the app
// const CACHE_NAME  = 'workhive-shell-v203';  // bump: MK11 - an error no longer tells you to 'try again' when the write failed because your session expired; central whIsAuthFailure/whWriteError in utils.js, adopted across marketplace + admin surfaces (12 sites -> 2)
// const CACHE_NAME  = 'workhive-shell-v202';  // bump: saved-search badge refreshes on save (the toast said saved while the counter still read 0 until reload) + the disputes empty state stops implying a capability the contact-only marketplace does not have
// const CACHE_NAME  = 'workhive-shell-v201';  // bump: moderation receipts now name what happened (a rejection tells the admin the seller can see the reason and resubmit) and an expired admin session no longer says 'try again' - platform-actions + founder-console
// const CACHE_NAME  = 'workhive-shell-v200';  // bump: MK3 - the Contact Seller step now gates on the live session and discloses WHY an account is needed BEFORE opening the inquiry form (an anon used to type name+phone+message and get 'Failed to send inquiry. Try again.' from a 42501), and an auth failure no longer invites a doomed retry
// const CACHE_NAME  = 'workhive-shell-v199';  // bump: the post-sheet account guard now decides on the LIVE SESSION (wh_hive_id survives sign-out, so the previous HIVE_ID check let a signed-out visitor through) and covers BOTH doors incl. the ?post=1&from_inventory= deep link
// const CACHE_NAME  = 'workhive-shell-v198';  // bump: tokens.css + components.css gained the general `.hidden` utility (6 pages were rendering class="hidden" elements permanently visible). A CSS shell file changed AFTER the v197 bump, so PWA users would have kept the cached copy and never received the fix — caught by validate_pwa sw_cache_staleness.
// const CACHE_NAME  = 'workhive-shell-v197';  // bump: unbacked-trust-signal sweep (rating reads the canonical verified-only column, no client recompute; honest "Not rated"; Certified badge requires actual certifications on all 3 surfaces) + anon post discloses the account requirement before the form + nav-hub reconciles identity unconditionally
// const CACHE_NAME  = 'workhive-shell-v196';  // bump: MK7 per-listing Product/Offer JSON-LD (availability from real status) + status added to listing selects
// const CACHE_NAME  = 'workhive-shell-v188';  // bump: marketplace deepwalk fixes — P7 load-error grid state + admin-link fail-closed gate + restoreIdentityFromSession reconciles stale identity cache
// const CACHE_NAME  = 'workhive-shell-v187';  // bump: E4 shift-brain -> reflowIdDump (utils.js) wraps crammed asset-code runs onto scannable rows (lens-blessed multi-line)
// const CACHE_NAME  = 'workhive-shell-v186';  // bump: C5 last 3 pages -> 100 (banner/heading content-floor calibration + engineering-design tab/pill orange -text)
// const CACHE_NAME  = 'workhive-shell-v185';  // bump: C5 accent status-captions (small-text class + inline orange/blue) -> -text tokens
// const CACHE_NAME  = 'workhive-shell-v184';  // bump: C5 orange/blue ghost-button text -> -text tokens (Load More etc.)
// const CACHE_NAME  = 'workhive-shell-v183';  // bump: C5 per-page --muted CSS var defs lifted to APCA-safe 0.80
// const CACHE_NAME  = 'workhive-shell-v182';  // bump: C5 accent-text - small orange/blue text -> --wh-orange-text/--wh-blue-text (tokens.css) to clear APCA
// const CACHE_NAME  = 'workhive-shell-v181';  // bump: C5 lens gradient-button calibration + survey_ufai_rubric shell
// const CACHE_NAME  = 'workhive-shell-v180';  // bump: C5 wh-tw.css muted text-white tiers /45-75 -> APCA-safe .8/.85
// const CACHE_NAME  = 'workhive-shell-v179';  // bump 2026-07-24: C5(APCA) fix - lifted muted text-color (white+cloud alpha) across all pages + components.css/.sc-label/.sc-sub/.wh-disclose + utils.js chrome to clear APCA Lc75 on the dark theme. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v178';  // bump 2026-07-24: report-sender now marks AI-drafted report summaries (AI6 principle on a FORWARDABLE artefact - they sat under a neutral 'Recent Reports' heading with a Resend button). Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v177';  // bump 2026-07-24: M1 visible-label sweep - 29 aria-label-only data-entry fields resolved across 11 shell pages (auth modal, handover, API key, permit-ref + custom-interval now toggle label+input together). Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v176';  // bump 2026-07-24: whPrompt now renders a VISIBLE <label for> (live approval-chain walk found the reject-reason box labelled ONLY by aria-label - a sighted supervisor saw an unexplained input; axe passed = the axe-0-violations false 100). utils.js is SHELL chrome on ~30 pages and 18 whPrompt call sites inherit the fix. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v175';  // bump 2026-07-23: D12 per-surface AI quota adopted across all 19 AI edge fns (observe-mode). Edge-only change, but bumped so the shell and fns re-prime together. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v174';  // bump 2026-07-23: rejection-reason (asset-hub reject now captures WHY via the shared whPrompt and renders it to the submitter) + the 3 edge fns swapped off hand-rolled rate limiters. asset-hub is a SHELL page. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v173';  // bump 2026-07-23: JA3 BACK-DISMISSES-OVERLAY - utils.js now makes every .sheet-overlay/.modal-overlay history-aware (Back closes the sheet instead of ejecting the user off the page; page-close keeps history balanced). utils.js is SHELL chrome on ~30 pages. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v172';  // bump 2026-07-23: D21 FRONTEND OBSERVABILITY - utils.js whLogError now REPORTS to our own client_errors table (mig 20260723000001) instead of console-only, so a field tech's production crash is finally visible. utils.js is SHELL chrome on ~30 pages. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v171';  // bump 2026-07-23: §12 loop 2-3 - the Q2 closed-overlay focus guard CENTRALIZED into utils.js (skillmatrix does not load tokens.css, so the shared-CSS route could not reach it) + per-page duplicates removed from community/skillmatrix. utils.js is SHELL chrome on ~30 pages. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v170';  // bump 2026-07-23: §12 flywheel loop 2 - JA2 return-promise (utils.js stamps ?return= on every #hive-gate CTA + hive.html validated "Continue to X" banner) + W2 recalibration in survey_ufai_rubric.js. utils.js is SHELL chrome on ~30 pages; without this bump PWA users keep the stale broken-promise gate. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v169';  // bump 2026-07-23: §12 Q2 no-phantom-focus (WCAG 2.2 SC 2.4.11) - visibility:hidden on CLOSED overlays so their controls leave the tab order: nav-hub.js (#wh-hub-panel, 28 controls) + companion-launcher.js (#wh-ai-widget) = shared chrome on ~30 pages, plus community.html (.sheet-overlay + #undo-toast) and skillmatrix.html (.modal-overlay). Without this bump PWA users keep the stale keyboard-trap chrome. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v168';  // bump 2026-07-23: §12 DIMENSION EXPANSION - JA1 arrival-fidelity fixes touched SHELL pages (asset-hub ?tag= prefill+miss-message, alert-hub ?focus= miss-message, marketplace-seller-profile ?worker= seller-not-found) + survey_ufai_rubric.js (new DP class). Without this bump PWA users keep the stale silent-drop pages. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v167';  // bump 2026-07-23: §11 UFAI U/A DEEPWALK touched shared tokens.css (44px form-control + button field floor, all pages) + heading-order fixes on marketplace/skillmatrix/alert-hub/marketplace-admin/agentic-rag-observability. Without this bump PWA users keep the stale tokens.css/pages. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v166';  // bump 2026-07-23: Y1b OFFLINE-QUEUE ADOPTION + Z1b autofill touched SHELL pages (asset-hub/dayplanner/skillmatrix/community offline-write-queue wiring; marketplace/report-sender autocomplete) + offline-queue.js (upsert/onConflict). Without this bump PWA users keep the stale pages/queue. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v165';  // bump 2026-07-22: REDUNDANT-WIDGET consolidation touched shared-chrome JS (utils.js whFreshnessFooter retired; nav-hub.js "Online" pill silence-when-healthy). Without this bump PWA users keep the stale utils.js/nav-hub.js. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v164';  // bump 2026-07-21: PLATFORM_CENTRALIZATION — storage/RBAC/head convergence touched shared-chrome JS
                                            // (Axis-3 behavioural idioms) + Axis-2 chrome purity wave (nav-hub/companion/
                                            // feedback/connectivity/etc. brand literals → var(--wh-*); tokens.css component
                                            // tier). Without this bump PWA users keep the stale chrome JS. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v162';  // bump 2026-07-19: EMOJI-FIRST — utils.js walker disabled (Arc W W5
                                            // reversed), nav-hub.js emoji nav + wh-icons.css central icon library
                                            // (see feedback_centralized_icon_library_emoji_first); re-prime shell
                                            // so PWA users do not keep the stale cached copies.
// const CACHE_NAME  = 'workhive-shell-v160';  // 2026-07-15 (rubric class S): offline-fallback.html gains the tokens.css <link>; tokens.css precached (L67).
// const CACHE_NAME  = 'workhive-shell-v159';  // bump 2026-07-03 (Arc P turn 2): SHELL portrait precache fixed — legacy james-256.jpg/rosa-256.jpg (404, never existed, failed SW install addAll) → real hezekiah.png/zaniah.png; PLUS the em-dash P4 sweep (685 displayed em dashes → colon/comma/parens across 43 files incl. utils.js + worker-critical SHELL HTML) + FUSION 5 meta-caption disclosure. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v158';  // bump 2026-07-02 (Arc P Wave 1 — Pareto revamp): components.css gains .ac-cta (shared "one primary action" button) + .wh-disclose (shared progressive-disclosure) — both SHELL_FILEs. hive.html: verdict hoisted above presence/focus + ss-action CTA + 6 ghost buttons → overflow menu + Network-Benchmark/Pattern-Alerts/Activity-Feed/Supervisor-Log collapsed (8.5→3.2 screens). pm-scheduler/analytics/shift-brain/inventory/alert-hub/asset-hub: "What to do next" now ends in a primary CTA button. index.html: home first role-action = solid primary + Secure-account nudge demoted. Wave 2: skillmatrix radar chart layout.padding fix + grammar/clarity copy; shift-brain carry-forward list capped + "Show all"; voice-journal + inventory initial list slice cut to 8 (glance-first, Load More); analytics OEE table → top-8 "Show all" helper. Wave 3: skillmatrix radar layout.padding + grammar; assistant empty-chat starter-prompt chips; resume AI-helpers card hidden until non-empty; index mobile hero logo 260→150px (headline/CTA above fold). Without this bump PWA users keep the stale flat/dense markup + missing shared CSS. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v157';  // bump 2026-06-25 (Arc W W1 elevation + W3 hero + W5 icons): components.css + utils.js (both SHELL_FILEs). components.css: --wh-shadow-*/--wh-elev-*/--wh-z-* tokens + global card/panel/overlay box-shadow + :active/:focus-visible + .simple-card.hero. utils.js: wh-elevation :where() injection (depth on non-components.css pages) + window.whIcon + an emoji->inline-SVG replacer (one icon system platform-wide). Without this bump PWA users keep the stale flat/coplanar CSS + emoji glyphs. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v156';  // bump 2026-06-24 (Arc S D-lens D-003): precache /offline-fallback.html + SW navigation fallback so a non-precached page opened offline shows a branded "you're offline" shell instead of a blank tab. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v155';  // bump 2026-06-21: SHELL_FILEs changed since v154 — voice-handler.js (in-flight) + index.html (login fetch now fetchWithTimeout-bounded + auth-copy em-dash scrub). Without this bump PWA users keep the stale cached login JS/markup. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v153';  // bump 2026-06-17: re-prime after SHELL_FILE changes committed since v152 (voice-handler.js + alert-hub.html escHtml-scope fix) — without this, PWA users keep the stale cached JS/markup.
// const CACHE_NAME  = 'workhive-shell-v152';  // bump 2026-06-14: STREAMLINE E2 + E4 ROLLOUTS. E2: utils.js now SELF-INJECTS the .wh-skeleton/.wh-list-error CSS (id="wh-list-states-css") so whListSkeleton()/whListError() render on ANY page that loads utils.js, not just the 11 with components.css (16 list pages wired). E4 (design-token consolidation): NEW /tokens.css = the SINGLE brand-palette source (precached above); components.css now @imports it (its :root keeps only -rgb/spacing/radius/type) and ~22 non-components.css pages <link> tokens.css in <head> (render-blocking, no FOUC); the temporary utils.js token injection was REMOVED. raw brand-hex → var(--wh-*) migrated in <style> across 33 pages (1452→916). Value-preserving (token === hex). tokens.css + components.css + utils.js + all these HTML pages are SHELL_FILES — without this bump PWA users keep stale CSS/JS/markup (or 404 on tokens.css = no brand colors). Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v151';  // bump 2026-06-14: STREAMLINE E2 consistent states — components.css gains .wh-skeleton shimmer + .wh-list-error/retry; utils.js gains whListSkeleton/whListError; inventory.html wires a skeleton-on-load + inline error+retry. Both components.css + utils.js are SHELL_FILES — without this bump PWA users keep stale CSS/JS and never get the loading/error states. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v150';  // bump 2026-06-14: STREAMLINE S10+S11 — NEW /components.css (shared .simple-card/.sc-*/.action-card/.details-toggle CSS, was inline-duplicated on ~15 pages) + ~17 shell pages edited (S10 shared wireDetailToggle replaces the per-page toggle IIFE; S11 verbatim pages now <link> components.css with the inline block removed). Without this bump PWA users keep stale cached pages + never fetch the new shared CSS. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v149';  // bump 2026-06-10: DRIFT-49 closure + deep-link fixes re-prime — SHELL_FILES changed: voice-handler.js (digest helpers rewritten: .execute()/.group_by() removed, adoption→risk_tier, asset selects to real columns), pm-scheduler.html, shift-brain.html, hive.html (deep-walk fixes), asset-hub.html (?tag= deep-link reader). Without this bump PWA users keep the stale cached voice digest that silently returns ''. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v148';  // bump 2026-06-09: full-platform deep-walk fixes re-prime — SHELL_FILES committed after v147 (hive.html PM-overdue asset roll-up + dashboard h1, logbook.html stat-pill count queries, inventory.html, pm-scheduler.html, shift-brain.html, asset-hub.html, + analytics/marketplace/skillmatrix/achievements/predictive a11y + alert-hub PM canonical). Without this bump PWA users keep the stale cached pages and never see the fixes. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v147';  // bump 2026-06-07: COMPANION STEP 6 (proactive companion) — re-prime cache so PWA users get the latest committed SHELL_FILES (logbook/inventory/hive/asset-hub/shift-brain/pm-scheduler/report-sender + voice-handler.js were committed after the v146 sw.js, staleness FAIL). Step 6 itself edits companion-launcher.js (NOT a precached shell file) to proactively surface DUE agent_followups; bundling the bump here clears the carried-over PWA staleness. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v146';  // bump 2026-06-07: GROUNDED SWEEP C7 modal-a11y debt RETIRED (18->0) — SHELL_FILEs changed: logbook.html (7 modals) + inventory.html (4) + hive.html (3) + report-sender.html (1) all get role=dialog+aria-modal+aria-label + whModalA11y ESC/focus-trap/restore via utils.js. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v145';  // bump 2026-06-07: GROUNDED SWEEP W2 modal a11y — SHELL_FILE pm-scheduler.html changed: its 3 overlays (#pm-edit-modal/#completion-sheet/#add-task-sheet) get role=dialog+aria-modal+ESC/focus-trap/restore via the new utils.js whModalA11y helper. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v144';  // bump 2026-06-07: GROUNDED SWEEP W1 platform tap-target floor — SHELL_FILES changed: nav-hub.js (.wh-hub-mode-btn 26->44 + new .wh-tappable base) + companion-launcher.js (wh-ai send/mic 36->44, close ->44) + dayplanner/shift-brain/pm-scheduler/voice-journal/index/inventory/resume tap-target classes ->44px. Re-prime cache so PWA users get the 44px controls.
// const CACHE_NAME  = 'workhive-shell-v143';  // bump 2026-06-07: SHELL_FILES committed in 312f6d5 (definer-hardening broad commit) without a cache bump → PWA Integrity FAIL. Shell diffs re-primed: founder-console.html (+152), resume.html (+68), dayplanner.html, inventory.html, logbook.html, pm-scheduler.html, shift-brain.html, voice-journal.html (grounded-MCP-sweep mobile/a11y fixes + companion FAB offset). Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v142';  // bump 2026-06-07: FAN-OUT RPC COLLAPSE Phase 3 — hive.html folds worker own-inventory + readiness/adoption snapshots + team-stock into get_hive_board_dashboard (37->15 calls). Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v141';  // bump 2026-06-07: FAN-OUT RPC COLLAPSE — SHELL_FILES changed: index.html (get_hive_dashboard loader rewire, 14->3 calls) + hive.html (get_hive_board_dashboard loader rewire across Phase 1+2, 37->21 calls). Re-prime cache so PWA users get the RPC-first loaders + legacy fallback.
// const CACHE_NAME  = 'workhive-shell-v140';  // bump 2026-06-04: RESUME BUILDER GATE PAYDOWN - resume.html registered across guardian validators; SHELL_FILES changed: index.html (resume stage entry + em-dash fix), companion-launcher.js + assistant.html (resume in AI knowledge), nav-hub.js (Resume Builder nav entry). Re-prime cache. PRIOR v139 2026-05-26: P1 ROADMAP TURNS 1-4 — all four P1 validators at baseline 0 (truth-view contract / envelope conformance / health endpoint / render budget). 56 edge fns adopted envelope. /health on every load-bearing fn. agentic-rag-loop Router/Grader/Checker cache via _shared/cache.ts. voice-handler.js mints x-wh-trace. Sentinel multi-scenario 63→0. Per-user rate limit. 4 substrate tables registered in canonical_sources. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v138';  // bump 2026-05-24: MEGA GATE 10-REGRESSION PAYDOWN — registered validate_rag_flywheel.py + validate_rag_flywheel_locks.py in run_platform_checks.py auto-discovery; declared WH_RATE_LIMIT_OVERRIDE + WH_RATE_LIMIT_RESET in .env.example + OPTIONAL_VARS allowlist; migrated inventory.html line 1452 confirm('Remove part') -> whConfirm; cleared U+2014 em-dashes from agentic-rag-loop GENERATOR_SYSTEM prompt rules 7+8 (replaced with colon + parenthetical); extended validate_ux_contract A3 destructive_confirm regex to accept whConfirm/whPrompt (was only matching native confirm()); whitelisted 20260521000001_fk_on_delete_hardening.sql in ALLOWED_MULTI_COMMIT (idempotency guards added across 2 commits, no prod deploy between). Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v137';  // bump 2026-05-21: MEGA GATE FULL PAYDOWN — fixes 13 regressions surfaced by `python -u run_platform_checks.py --fast` (the -u was the actual fix that made the gate visibly streamable in 10.5 min). Registers 4 new agentic-RAG tables (agentic_rag_traces / canonical_period_summaries / agent_episodic_memory / unified_events) in reset.py + canonical_sources. Adds 9 voice-companion infra tables (ai_audit_log / ai_knowledge_gap / ai_quality_escalation / asset_watchlist / companion_handoff / mentor_relay_queue / shared_voice_notes / wh_feature_flags / wh_voice_presence) referenced by voice-handler.js Phase A wiring but missing from schema. Adds ai_cost_log.quality_rating column. Wires sessionStorage read for wh_voice_session_id (was set-without-get). Classifies agentic-rag-observability.html as NON_TOOL (also adds to validate_schema/performance/timers LIVE_PAGES). Registers 5 bug-class L0 validators (empty_catch / settimeout_string / document_write / tabindex_positive / viewport_user_scalable) in run_platform_checks.py. Fixes validate_xss.py false-positive on _rewriteQueryForRetrieval (Retrieval contains 'eval(' substring — switched to word-boundary regex). Re-baselines sentinel_baseline.json at new higher coverage (241/179 vs 191/173). Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v136';  // bump 2026-05-21: PHASE A2 ORPHAN CLOSEOUT — 3 more per-turn anchors plumbed: BUDDY SET (T153 _detectBuddySet + auto-_setBuddy persistence), DIALECT NOTE (T205 _isCebuanoLeaning OR T206 _isIlonggoLeaning — fires when ≥2 dialect markers appear without an explicit T59 switch request). Closes the 4-orphan audit gap (3 wired here; _classifySemanticRoute deferred — needs architectural review of router vs anchor placement). Audit script confirms 51/64 transcript-detectors now wired in perTurnAnchors, remaining 13 are short-circuit handlers that fire BEFORE the prompt assembly (greeting/goodbye/thanks/repeat-request/affirmation-bypass/etc). validate_ai_companion_team_coordination.py + validate_ai_companion_multilang.py extended with new wires; both 11/11 PASS. Phase C spec extended to 8 tests (added dialect-detection scenario) — 8/8 PASS. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v135';  // bump 2026-05-21: PHASE A COMPREHENSIVE WIRING — turn-level prompt-anchor wiring across 9 flywheel batches. 24 new per-turn anchors total. SAFETY (T175-T184): INCIDENT GATE + LOTO GATE + HOT WORK GATE + CONFINED SPACE GATE + PPE MATRIX + NEAR-MISS CAPTURE + JSA OFFER. INTEGRATION+AUDIT (T95-T104): SESSION TAG (T100) + STT MANGLED (T102) + SHIFT END HORIZON (T104) + QUIET HOURS (T96). LEARNING (T105-T114): MENTOR HANDOFF (T114). COMPLIANCE (T115-T124): PII SCRUBBED (T115) + CONSENT CHANGE (T116) + ERASURE REQUEST (T118) + SUSPICIOUS ACTIVITY (T120). ACCESSIBILITY (T125-T134): VOICE-ONLY TOGGLE (T133). OPERATIONAL (T135-T144): MEMORY PRESSURE (T140). TEAM COORDINATION (T145-T154): HANDOFF (T146) + SHARED NOTE (T147) + WATCHLIST (T149) + RESOLUTION CAPTURE (T151). SUSTAINABILITY (T195-T204): ENERGY QUERY (T204). MULTI-LANG NLU (T205-T214): TAGALOG IMPERATIVE (T207) + POLITENESS REGISTER (T209). All 9 batch validators extended with wire_* ratchets — 105 checks PASS, 26 AI-companion + dialog validators rc=0. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v134';  // bump 2026-05-21: PHASE A WIRING — turn-level prompt-anchor wiring for the SAFETY + PERMIT-TO-WORK batch (turns #175-#184). Seven new per-turn anchors live in voice-handler.js: INCIDENT GATE (T182, fires first inside the safety block), LOTO GATE (T175, references the energy isolation checklist + zero-energy verification), HOT WORK GATE (T176, requires hot-work permit + fire watch + flammables-cleared radius), CONFINED SPACE GATE (T177, requires 4-gas PH OSHS reading + attendant + rescue plan), PPE MATRIX (T178, flagged authoritative — no LLM improvisation), NEAR-MISS CAPTURE (T179, routes to safety_near_miss), JSA OFFER (T180, 4-step structure). Validator extended with 7 wire_* ratchets (17/17 PASS). Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v133';  // bump 2026-05-21: voice-handler.js Phase 4.207-4.216 twenty-first 10-turn flywheel (turns #205-#214, MULTI-LANGUAGE NLU): Cebuano markers (unsa/asa/kinsa/lagi/bitaw), Ilonggo markers (gid/bala/manami/damo gid), Tagalog imperative detector (i-X mo / X-an mo / pakisuyo), code-switch ratio (PH word coverage of last 10 turns), politeness register classifier (formal po/ho vs casual tol/pre/bro vs mixed), PH time phrases (umaga/tanghali/hapon/gabi/madaling araw), bilingual number words 0-20 (isa/dalawa/usa/duha/one/two), filler suppression (uh/um/eto kasi/ano ba), bilingual stop-word list for retrieval, shop-floor slang→canonical (sira→broken / nag-init→overheat / umiyak→leak). Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v132';  // bump 2026-05-21: voice-handler.js Phase 4.187-4.206 nineteenth + twentieth 10-turn flywheel batches (turns #185-#204). KNOWLEDGE GRAPH (T185-T194): entity extraction (asset_tags + failure_modes + worker mentions), relation extraction (caused/feeds), KG triple builder with allow-listed predicates, RAG context block with citation markers, FNV-1a 32-bit embedding hash + Hamming distance, document chunking (400/50 default), citation build+parse (<view>:<row>:<column>), query rewriter (strips fillers, injects entities), reasoning trace (8-hop bounded localStorage), KB version tracking. ENERGY + SUSTAINABILITY (T195-T204): EnPI (ISO 50001), PH grid carbon factor 0.717 kgCO2e/kWh, peak demand breach + near-miss, 5σ energy anomaly, standby waste, water use breach, compressed-air leak loss estimator (dB→cfm), motor efficiency vs IE3 baseline, sustainability KPI bundle, energy query detector. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v130';  // bump 2026-05-21: voice-handler.js Phase 4.167-4.186 seventeenth + eighteenth 10-turn flywheel batches (turns #165-#184). ADVANCED ANALYTICS (T165-T174): 3σ anomaly detection, Weibull moment fit (Justus closed-form approximation), Pareto top-80%, linear trend regression (rising/falling/flat), seasonal peak index, outlier-trimmed mean, z-score primitive, Pearson correlation, Weibull failure-probability CDF, availability calc. SAFETY + PERMIT-TO-WORK (T175-T184): LOTO intent detector (lockout-tagout / isolation / padlock / de-energize / PH variants), hot-work detector (welding/grinding/cutting torch/brazing), confined-space detector (tank entry / sump / vessel / PH variants), PPE query + matrix (hot_work/confined_space/chemical/electrical/height/default), near-miss capture (close call / muntik na), JSA template builder (4-step task-hazard-control-PPE), gas-test validator (PH OSHS O2 19.5-23.5 / LEL ≤10 / CO ≤35 / H2S ≤10), incident reporter, energy-isolation checklist (electrical/mechanical/hydraulic/pneumatic/chemical/thermal/gravitational), permit expiry check. Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v128';  // bump 2026-05-21: voice-handler.js Phase 4.157-4.166 sixteenth 10-turn flywheel (turns #155-#164, EXTERNAL INTEGRATION): SAP PM webhook receiver (PM01-PM04 validation), Maximo REST poll (oslc.where + oslc.select for COMP work orders), OPC-UA tag parser (Plant1.P203.Vibration_RMS → P-203 + vibration_rms), MQTT topic builder (workhive/<hive>/<asset>/<metric>) + JSON payload parser, Slack webhook sender, email digest body builder (5-line format), Microsoft Teams Adaptive Card builder, calendar ICS event builder, webhook signature constant-time compare (XOR via charCodeAt), outbound retry queue (wh_voice_outbound_queue, capped at 20, drain on online). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v127';  // bump 2026-05-21: voice-handler.js Phase 4.147-4.156 fifteenth 10-turn flywheel (turns #145-#154, TEAM COORDINATION + CROSS-WORKER): active voice worker list (wh_voice_presence query, 5-min activity window), cross-worker handoff ('send this to Mike' + 'ipasa kay Kuya Ben' → companion_handoff table), shared note thread (shared_voice_notes for team broadcast), high-concurrency alert (>5 voice sessions → 'team busy go async'), watchlist subscriptions ('watch P-203' / 'notify me on MX-12' → asset_watchlist), supervisor-only voice broadcast (not_supervisor gate + __broadcast__ marker), resolution detector ('fixed it' / 'ayos na' / 'gumana na' → knowledge sharing nudge), cross-shift continuity (prior-shift open items from v_logbook_truth), buddy mode (per-device wh_voice_buddy_<worker> + 'buddy up with Juan' / 'kasama ko sa shift si Romeo' detector), mention notifications (extends T38 → companion_handoff with status='mention'). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v126';  // bump 2026-05-21: voice-handler.js Phase 4.137-4.146 fourteenth 10-turn flywheel (turns #135-#144, OPERATIONAL EXCELLENCE): health-check ping every 5min to /functions/v1/voice-health (sw_version + ctx), self-test on mount (10 critical helpers verified with console.info), feature flag system (wh_feature_flags table pulled with 5-min cache, per-hive override of build defaults), browser-support banner (mediaDevices/AudioContext/fetch/Promise capability checks + yellow alert banner), network condition adaptation (navigator.connection.effectiveType → lite-payload on slow-2g/2g), memory pressure handler (navigator.deviceMemory + performance.memory with high/medium/low thresholds), server clock drift check (Date header compare, >2min drift exceeded flag), background tab pause (visibilitychange listener), auto-recovery on JS exception (window.onerror catcher scoped to voice-handler / wh-tts), presence heartbeat (60s wh_voice_presence upsert). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v125';  // bump 2026-05-21: voice-handler.js Phase 4.127-4.136 thirteenth 10-turn flywheel (turns #125-#134, MULTI-MODAL + ACCESSIBILITY): camera still capture (getUserMedia environment-facing with no_media_devices fallback), file attachment (image/PDF, 8MB cap, base64 dataUrl), reduced-motion accessibility (prefers-reduced-motion media query + wh_voice_reduced_motion override key), screen-reader aria-live region (polite + atomic + role=status mirroring every reply), keyboard navigation (Escape/Space/Enter/ArrowUp/ArrowDown/Ctrl+H bindings with editable-target guard), color-blind safe palette (red→blue critical, orange→amber high, swappable via data-palette attribute), large-text mode (data-text-size attribute, 1.5x scale), haptic feedback patterns (confirm/success/warning/critical via navigator.vibrate), voice-only mode (UI fades, audio + AT only, PH-aware toggle detector), live captions (visible caption bar overlay, distinct from AT aria-live). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v124';  // bump 2026-05-21: voice-handler.js Phase 4.117-4.126 twelfth 10-turn flywheel (turns #115-#124, COMPLIANCE + DATA GOVERNANCE): PII scrubber ([PHONE]/[EMAIL]/[ID] markers, PH mobile + email + 11-15 digit ID), consent capture (PH Data Privacy Act, wh_voice_consent key, grant/revoke detector), retention enforcement (configurable days, default 180), right-to-erasure (delete-history detector + scoped DELETE + audit log entry), audit CSV export (RFC 4180 quoting + escape), suspicious activity detector (rapid_fire 5-same-intent-in-60s + off_hours_bulk 10+-events-in-quiet-hours), AI disclosure policy (flag + per-session shown tracking + disclosure line), locale-aware date formatting (PH DD/MM/YYYY vs ISO), per-hive monthly cost cap (ai_cost_log aggregate), voice drift advisory (signature record + drift detect — ADVISORY ONLY, never auth). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v123';  // bump 2026-05-21: voice-handler.js Phase 4.107-4.116 eleventh 10-turn flywheel (turns #105-#114, PROACTIVE ASSISTANCE + LEARNING): adaptive PM sync drift detector (logged-PM vs scheduled-next diff), skill-level adaptation (apprentice/standard/senior vocab tiers with RPN/FMEA depth), cross-asset failure-mode pattern detection (>=2 assets in <7d), per-worker intent history (wh_voice_intent_hist_<worker>, 30d rolling, top-3 recurring), session sentiment over time (positive/neutral/negative, 14-day log, persistent-negative escalation), anticipatory asset warm-up (60s cache against v_asset_truth), symptom→failure-mode normalizer (vibration_anomaly/overheat/noise_anomaly/leak/smell/no_start with PH variants), shift-boundary context reset (06/14/22 PHT detector), knowledge-gap logging (ai_knowledge_gap table), mentor-mode handoff (mentor_relay_queue). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v122';  // bump 2026-05-21: voice-handler.js Phase 4.97-4.106 tenth 10-turn flywheel (turns #95-#104, INTEGRATION + AUDIT): audit log emission (ai_audit_log insert on confirmed write actions), quiet hours (22:00-06:00 PHT, non-critical alerts only), action preflight (no_intent / missing_asset_tag / malformed_asset_tag / voice_execute_lock blockers), idle session cleanup (5-min auto-pause via setTimeout), companion-error analytics (per-hive 7-day error counts in wh_voice_errors_<hive>), session tag (per-session label, wh_voice_session_tag_<id>, detector for 'tag this as X'), cross-page deep-link shorthand (<wh-link page=X asset=Y> token build + parse), STT grammar-mangled guess (heuristic flag for 'did you mean'), persona phrase pool (ack/encourage/concern/closing categories, no-repeat-in-a-row), shift-end handover trigger (UTC+8 math against worker shift_end_hour, 30-min margin). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v121';  // bump 2026-05-21: voice-handler.js Phase 4.87-4.96 ninth 10-turn flywheel (turns #85-#94, INPUT NORMALIZATION + ONBOARDING): numeric precision rule (units + 1-decimal cap), asset-tag normalization (pee-two-oh-three → P-203 via _DIGIT_WORDS + _LETTER_WORDS), time-range normalization (this week / yesterday / kahapon / last N days → ISO span), ack-style preference (terse vs warm, persisted to wh_voice_ack_style), forbidden-topic redirect (competitor names + office politics / chismis), mic noise-floor classifier (quiet/normal/spotty/noisy from p50/p90 peaks), conversation pin (per-worker localStorage, capped at 20), help command shortcut (/help and tulungan mo ako), multi-language KPI labels (mtbf/mttr/oee/compliance/availability in Tagalog + Cebuano), new-worker onboarding cue (_isFirstTimeWorker checks voice_journal_entries count + _firstTimeWelcomeLine with 3 sample commands). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v120';  // bump 2026-05-21: voice-handler.js Phase 4.77-4.86 eighth 10-turn flywheel (turns #75-#84, TRUST DEPLOYMENT): toxicity guard (severity 0-1 with severe/mild PH-aware terms, de-escalate anchor), question shape classifier (data/how_to/opinion/troubleshoot/social → reply structure), freshness disclosure ('is this fresh' → last_updated stamp), rate-limit cooldown (per-hive localStorage timestamp, 10-min cap), conversation share link (/voice-journal.html#session=<id>), readback request (TTS replay of prior reply, distinct from T14), scope disclosure (capability list grounded, no inventing), multi-turn correction handler (distinct from T2 negation — redo answer with new info), confidence label tier (high/medium/low from row count + day count), crisis escalation extension (T4 + workplace_violence kind, Safety Officer / HR routing). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v119';  // bump 2026-05-21: flywheel turns 16-25 — index.html auth-form wrapper (password-manager autofill) + 3 explicit button types; achievements.html back-button <a href=javascript:> -> <button>; parts-tracker.html meta-refresh-allow marker; integrations.html Bearer-token password-input-allow; project-manager.html timer-cleanup-allow. Re-prime cache so PWA users get the auth-form + a11y fixes.
// const CACHE_NAME  = 'workhive-shell-v118';  // bump 2026-05-21: voice-handler.js Phase 4.67-4.76 seventh 10-turn flywheel (turns #65-#74, ORCHESTRATION + INTEGRATION): PDF export detector points to Report Sender, per-device pronunciation library, voice-execute safety lock (default OFF), persona portrait animation (idle/listening/thinking/speaking/urgent), cross-hive benchmark RPC fn_cross_hive_benchmark wiring (5-min cache), daily-digest mode (5-line briefing), push notification readiness (capability + permission request), multi-worker concurrency lock (per-hive advisory), accent / voice signature adaptation (tagalog density estimate + persisted pref), streaming SSE indicator. Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v117';  // bump 2026-05-21: voice-handler.js Phase 4.54-4.66 sixth 10-turn flywheel (turns #55-#64, WORKFLOW + PERSONALIZATION): proactive companion turn (open() accepts alert payload), maturity-stair gating (Stair <2 → no predictive promises), per-slot expiry windows (asset_tag 60m / machine_status 30m / time_window 2h), action replay ('same fix on P-205'), language opt-in (tagalog / english / cebuano persisted), brevity preference (brief / full mode), timer follow-up ('remind me in 20 min'), URL-context pre-fill (?asset=P-203 → context_slots), mic quality meter (AnalyserNode warns on low volume), multi-step action queue ('log entry then start PM then notify'). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v116';  // bump 2026-05-21: voice-handler.js Phase 4.44-4.53 fifth 10-turn flywheel (turns #45-#54, RESILIENCE + MEMORY + TRUST OPS): offline degradation tracker, 10-min reply cache (LRU 16), feedback escalation (3+ thumbs-down in 7d → ai_quality_escalation upsert), custom plant terminology fuzzy-match against v_asset_truth, conversation branching stack ('back to the X thing'), multi-modal photo intent (offers Visual Defect Capture), avatar emotion state (urgent/celebratory/concerned/helpful → data-avatar-state attribute), cross-hive anonymised benchmark anchor, summary-on-demand mode, identity drift tracker (warns on worker_name change mid-session). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v115';  // bump 2026-05-21: voice-handler.js Phase 4.34-4.43 fourth 10-turn flywheel (turns #35-#44, COLLABORATION + WELLBEING): action-confirmation detector (write-verb utterances require yes/no before voice-action-router executes), wellbeing nudge on graveyard shift, encouragement anchor for completed PMs / closed logbooks, skill-gap nudge from v_worker_skill_truth, shift-handover mode (structured 4-line block), batch-action parser (log X, Y, Z), explainability anchor (source view + row count + timestamp), co-worker mention detector for logbook tagging, fatigue signal detector (pagod / ayoko / frustrated → softer tone), transcript export detector routes to Report Sender. Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v114';  // bump 2026-05-21: flywheel turns 8 + 12 — logbook.html + inventory.html + dayplanner.html JSON.parse safety wrappers (corrupt localStorage no longer crashes the page); platform-health.html setInterval cleanup on beforeunload + 2 fetch() chains given .catch fallbacks; project-manager.html documented timer-cleanup-allow marker. Re-prime cache so PWA users get the new try/catch wrappers + error handlers.
// const CACHE_NAME  = 'workhive-shell-v113';  // bump 2026-05-21: voice-handler.js Phase 4.24-4.33 third 10-turn flywheel (turns #25-#34, CONTEXT AWARENESS + INTELLIGENCE): shift-context anchor (06:00 / 14:00 / 22:00 PHT with UTC+8 math), repeated-issue surface (chronic machines from v_logbook_truth), standards lookup detector (ISO/SAE/SMRP/IEC/ASHRAE/NFPA), voice command shortcuts (open logbook / show analytics / schedule PM → page nav), AI quality thumbs UI on every reply (persisted to ai_cost_log.quality_rating), worker-discipline biasing in prompt, goodbye detector ('tapos na' / 'yun lang' → clean session end), confidence-calibration anchor (hedge on small samples), long-session pacing (>=10 turns nudges break), proactive-alerts override (critical alerts FIRST sentence). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v112';  // bump 2026-05-20: voice-handler.js + wh-tts.js Phase 4.19-4.23 second 10-turn flywheel (turns #15-#24, TRUST + AUDIO QUALITY + OBSERVABILITY + CROSS-SURFACE): hallucination guard prompt anchor, citation rule, mic-tap interrupts in-flight audio, TTS latency ratchet, ai-gateway rate-limit + fallback UX, acronym SSML spell-out (MTBF/OEE/PM/RPN read as letters), assistant.html cross-surface journal pull, ai_cost_log surfaced, conversation-end ack on overlay close. Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v111';  // bump 2026-05-20: voice-handler.js Phase 4.9-4.18 10-turn flywheel expansion (turns #5-#14): persona-switch utterance, stale-state guard (15-min threshold), topic-interruption signal, thanks/ack short-circuit, asset-context auto-priming from logbook, first-turn greeting, code-switch anchor in prompt, sensitive-topic redirect (HR/legal/financial → supervisor), worker-name personalization with 'kapatid' fallback, repeat-that handler ("ulit nga" replays last reply). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v110';  // bump 2026-05-20: voice-handler.js Phase 4.7 clarification-recovery routing — bare "logbook" / "PM" / "analytics" / "asset hub" replies after the streak-ceiling "what page would help?" prompt now route DIRECTLY to that intent (high confidence, clarification_pending cleared) instead of dead-ending in another clarify loop. Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v109';  // bump 2026-05-20: voice-handler.js Phase 4.5/4.6 dialog continuity — PRIOR TOPIC HANDLE block in the system prompt (pronoun resolution: 'it' / 'that' / 'yan' / 'yun' resolved to the prior intent) + natural-language SLOT ENUMERATION ('You already know: asset tag = P-203') replacing the raw JSON dump. Multi-turn continuity now deterministic. Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v108';  // bump 2026-05-20: voice-handler.js Phase 4.2/4.3/4.4 sister handlers — negation bypass (no / cancel / wala / hindi exits the topic and clears dialog state), noise transcript guard (empty / 1-2 char / "uh" / "um" skips the LLM call and renders "didn't catch that"), clarification-loop ceiling (after 2 consecutive clarifies, switch prompt shape + hard reset). Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v107';  // bump 2026-05-20: voice-handler.js Phase 4.1 follow-up affirmation detector ("Yes, the details" bypasses topic-switch UI) + hive.html realtime listeners moved from dead `assets` table to `asset_nodes` + signal-trust fixes (pm-scheduler/index/logbook) + 33 L0 bug-class validators wired. Re-prime cache for all PWA users.
// const CACHE_NAME  = 'workhive-shell-v106';  // bump 2026-05-20: canonical drift flywheel turn 11 — 27 v_*_truth views shipped + 70 consumer SELECTs migrated to view reads (HTML + edge fns); inventory.html stockStatus refactored to trust is_low_stock from the view; agent_memory phase-2 collision fixed; voice-handler.js cleared. Re-prime cache.
// const CACHE_NAME  = 'workhive-shell-v105';  // bump 2026-05-20: AI Prompt Regression L4 — voice-handler.js system prompt now carries the Platform Metric Anchors block (MTBF/MTTR -> ISO 14224, OEE -> ISO 22400-2 / Nakajima, PM -> SMRP, RPN -> IEC 60812, RCM -> SAE JA1011, anomaly -> Z-Score). Re-prime cache for voice answers to be standards-anchored.
// const CACHE_NAME  = 'workhive-shell-v104';  // bump 2026-05-20: Tier-S citation visibility 52% -> 100% — 8 pages now cite their registered standard short_name (marketplace + marketplace-seller-profile + marketplace-seller + skillmatrix + achievements + founder-console + hive maturity-stair). Re-prime cache for the chip text.
// const CACHE_NAME  = 'workhive-shell-v103';  // bump 2026-05-20: massive L2 expansion — 6 dashboards added manifest link (analytics/analytics-report/platform-health/achievements/founder-console/ph-intelligence); asset-hub FMEA cites IEC 60812:2018; hive adoption-risk cites WorkHive Adoption Risk; platform-health verdict cites WorkHive Platform Health. Re-prime cache so PWA users see the chip + manifest fixes.
// const CACHE_NAME  = 'workhive-shell-v102';  // bump 2026-05-20: drift wiring — index.html ops-home Today's One Thing now reads v_amc_truth + v_sensor_truth + v_alert_truth; hive.html pattern-alerts panel + asset-hub anomaly banner now read truth views. Re-prime cache so PWA users see the canonical-wired renderers.
// const CACHE_NAME  = 'workhive-shell-v101';  // 3 truth-view wrappers + OEE RPC
// const CACHE_NAME  = 'workhive-shell-v100';  // bump 2026-05-19: Calm Dashboard hideZeroStat wiring pass — stat-update sites now dim 0/— values across hive (welcome + members + pulse), alert-hub (AMC briefing setStat), asset-hub (asset-360 strip), predictive (4 risk-tier counts), achievements (3 XP stats), founder-console (setStat), platform-health (health-num + streak)
const SHELL_FILES = [
  // Original report-sender shell
  '/report-sender.html',
  '/report-sender-manifest.json',
  // Shared chrome
  '/tokens.css',              // E4: the single brand-palette source (every page <link>s it; components.css @imports it). Precache or offline pages lose all var(--wh-*) colors.
  '/components.css',          // S11: shared component CSS (was inline-duplicated on ~15 pages)
  '/wh-icons.css',            // 2026-07-19: central emoji icon library (.ic ic-*); nav-hub.js also injects the <link>
  '/nav-hub.js',
  '/wh-patterns.js',          // 2026-07-20: centralized behavioural idioms (Axis-3), loaded early by nav-hub
  '/wh-roles.js',             // 2026-07-20: canonical client RBAC SSOT (window.WHRoles), loaded early by nav-hub
  '/button-lock.js',
  '/offline-banner.js',
  '/browser-floor.js',        // T119: the ES5 old-browser canary every page now loads first - precached so offline shell pages can load it
  '/offline-fallback.html',   // Arc S D-003: SW navigation fallback shell for offline non-precached pages
  '/brand_assets/workhive-logo-transparent.png',
  // Phase 2 resilience helpers (shared across worker-critical surfaces)
  '/offline-queue.js',
  '/connectivity-widget.js',
  '/form-autosave.js',
  '/session-timeout.js',
  '/device-fingerprint.js',
  '/onboarding.js',
  '/wh-help.js',
  // Persona Contract Phase 3+4 shared helpers
  '/wh-persona.js',
  '/wh-tts.js',
  // Voice Companion handler (Phase 1-11 orchestrator)
  '/voice-handler.js',
  // Companion persona portraits. 2026-07-03: the legacy james-256.jpg / rosa-256.jpg
  // precache entries 404'd (those files never existed), which fails the SW install
  // addAll. Point at the real renamed portraits that DO exist in brand_assets.
  '/brand_assets/hezekiah-256.jpg',
  '/brand_assets/zaniah-256.jpg',
  // Worker-critical pages (offline-capable on cached page-shell)
  '/logbook.html',
  '/inventory.html',
  '/pm-scheduler.html',
  // parts-tracker.html DELETED 2026-06-10 (Phase 4 consolidation: zombie page —
  // assistant notes declared it retired; inventory.html is the canonical surface).
  // Removing it here is mandatory: a precached missing file fails the whole SW install.
  '/shift-brain.html',
  '/asset-hub.html',
  '/hive.html',
];

self.addEventListener('install', e => {
  e.waitUntil(
    caches.open(CACHE_NAME).then(cache => cache.addAll(SHELL_FILES))
  );
  self.skipWaiting();
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k)))
    )
  );
  self.clients.claim();
});

// Network-first for API and font requests; cache-first for shell
self.addEventListener('fetch', e => {
  const url = e.request.url;
  if (url.includes('supabase.co') || url.includes('fonts.goog') || url.includes('fonts.gstatic')) {
    e.respondWith(fetch(e.request).catch(() => new Response('', { status: 503 })));
    return;
  }
  e.respondWith(
    caches.match(e.request).then(cached => cached || fetch(e.request).catch(() => {
      // Arc S D-lens (D-003): offline AND not precached. For a page navigation, serve
      // the branded offline shell instead of a blank tab; for sub-resources, a 503.
      if (e.request.mode === 'navigate') {
        return caches.match('/offline-fallback.html').then(f => f || new Response('', { status: 503 }));
      }
      return new Response('', { status: 503 });
    }))
  );
});

// ── Web Push (SERVICE_HAILING P5/G3) ─────────────────────────────────────────
// notify-push (edge fn, VAPID) sends { title, body, url }. Without these handlers a
// delivered push silently no-ops; the click handler focuses an existing tab on the
// target page or opens one — the provider lands on the job-offer console in one tap.
self.addEventListener('push', e => {
  let data = { title: 'WorkHive', body: 'You have a new notification.', url: '/workhive/marketplace-seller.html?tab=services' };
  try { data = Object.assign(data, e.data ? e.data.json() : {}); } catch (_) { /* empty-catch-allow: malformed payload falls back to the generic notification */ }
  e.waitUntil(self.registration.showNotification(data.title, {
    body: data.body,
    icon: '/workhive/brand_assets/workhive-logo-transparent.png',
    badge: '/workhive/brand_assets/workhive-logo-transparent.png',
    data: { url: data.url },
  }));
});

self.addEventListener('notificationclick', e => {
  e.notification.close();
  const target = (e.notification.data && e.notification.data.url) || '/workhive/marketplace-seller.html?tab=services';
  e.waitUntil(clients.matchAll({ type: 'window', includeUncontrolled: true }).then(list => {
    for (const c of list) {
      if (!c.url.includes(target.split('?')[0]) || !('focus' in c)) continue;
      // T105 (2026-08-26): MATCHING ON THE PATH ALONE DROPPED THE DESTINATION. A push's whole
      // point is where it sends you, and every url this worker receives carries that in the
      // QUERY (?tab=services, ?asset=, ?post=). With an existing tab open on the same page at a
      // different tab/record, the old code focused it and returned - so a job-offer push landed
      // the provider on whatever they had been looking at, with nothing to say a destination had
      // been promised and missed. Focus the tab AND navigate it when the query differs.
      var sameTarget = false;
      try { sameTarget = new URL(target, c.url).href === c.url; } catch (_) { sameTarget = c.url.endsWith(target); }
      if (sameTarget || !('navigate' in c)) return c.focus();
      return c.navigate(target).then(cl => (cl && 'focus' in cl) ? cl.focus() : cl).catch(() => c.focus());
    }
    return clients.openWindow(target);
  }));
});
