"""
RAG Flywheel — per-tile L0 locks (auto-generated by rag_flywheel_processor.py)
============================================================================
Each entry is a tile that the walk has observed answering a grounding-probe
question with checker_passed=true at least once. The validator REQUIRES the
locked tile attribute to still be present on its page (regression catches
deletions). It does NOT re-run the AI question on every CI run — the walk
spec does that on its own cadence.

Generated entries: do not hand-edit. Append via tools/rag_flywheel_processor.py.
"""

from __future__ import annotations
import os, sys, re

if sys.platform == "win32":
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

from validator_utils import read_file, format_result


# {tile_key: {"page": "...", "label": "...", "first_seen": "turn N", "route": "..."}}
TILE_LOCKS: dict = {    "analytics:oee": {"page": "analytics", "label": "OEE (avg, partial)", "first_seen": "turn 3", "route": "semantic"},
    "analytics:mtbf": {"page": "analytics", "label": "Worst MTBF (partial)", "first_seen": "turn 3", "route": "semantic"},
    "analytics:pm_compliance": {"page": "analytics", "label": "PM compliance (30d approx)", "first_seen": "turn 3", "route": "semantic"},
    "alert-hub:high_severity_alerts": {"page": "alert-hub", "label": "High-severity alerts", "first_seen": "turn 3", "route": "semantic"},
    "alert-hub:anomaly_signals": {"page": "alert-hub", "label": "Anomaly signals", "first_seen": "turn 3", "route": "semantic"},
    "alert-hub:amc_daily_brief": {"page": "alert-hub", "label": "AMC daily brief", "first_seen": "turn 3", "route": "semantic"},
    "asset-hub:total_assets": {"page": "asset-hub", "label": "Total assets", "first_seen": "turn 3", "route": "semantic"},
    "asset-hub:critical_assets": {"page": "asset-hub", "label": "Critical assets", "first_seen": "turn 3", "route": "semantic"},
    "asset-hub:pending_approval": {"page": "asset-hub", "label": "Pending approval", "first_seen": "turn 3", "route": "semantic"},
    "pm-scheduler:overdue": {"page": "pm-scheduler", "label": "Overdue PMs", "first_seen": "turn 3", "route": "semantic"},
    "pm-scheduler:due_soon": {"page": "pm-scheduler", "label": "Due this week", "first_seen": "turn 3", "route": "semantic"},
    "pm-scheduler:on_track": {"page": "pm-scheduler", "label": "On track", "first_seen": "turn 3", "route": "semantic"},
    "inventory:out_of_stock": {"page": "inventory", "label": "Out of stock", "first_seen": "turn 3", "route": "semantic"},
    "inventory:low_stock": {"page": "inventory", "label": "Low stock", "first_seen": "turn 3", "route": "semantic"},
    "inventory:pending_approval": {"page": "inventory", "label": "Pending approval", "first_seen": "turn 3", "route": "semantic"},
    "skillmatrix:on_target": {"page": "skillmatrix", "label": "On target workers", "first_seen": "turn 3", "route": "semantic"},
    "skillmatrix:quizzes_available": {"page": "skillmatrix", "label": "Quizzes available", "first_seen": "turn 3", "route": "semantic"},
    "skillmatrix:total_badges": {"page": "skillmatrix", "label": "Total badges earned", "first_seen": "turn 3", "route": "semantic"},
    "hive:maturity_stair": {"page": "hive", "label": "Hive maturity stair", "first_seen": "turn 3", "route": "semantic"},
    "hive:adoption_health": {"page": "hive", "label": "Adoption health", "first_seen": "turn 3", "route": "semantic"},
    "hive:open_issues": {"page": "hive", "label": "Open issues", "first_seen": "turn 3", "route": "semantic"},
    "predictive:hot_assets": {"page": "predictive", "label": "Hot assets", "first_seen": "turn 17", "route": "semantic"},
    "predictive:healthy_assets": {"page": "predictive", "label": "Healthy assets", "first_seen": "turn 17", "route": "semantic"},
    "predictive:earliest_forecast": {"page": "predictive", "label": "Earliest forecast failure", "first_seen": "turn 17", "route": "semantic"},
    "achievements:xp_this_week": {"page": "achievements", "label": "XP this week", "first_seen": "turn 24", "route": "cold_archive"},
    "achievements:active_domains": {"page": "achievements", "label": "Active domains", "first_seen": "turn 24", "route": "semantic"},
    "achievements:total_level": {"page": "achievements", "label": "Total level", "first_seen": "turn 24", "route": "semantic"},
    "dayplanner:today_count": {"page": "dayplanner", "label": "Tasks today", "first_seen": "turn 24", "route": "semantic"},
    "dayplanner:week_count": {"page": "dayplanner", "label": "Tasks this week", "first_seen": "turn 24", "route": "semantic"},
    "dayplanner:overdue_count": {"page": "dayplanner", "label": "Overdue tasks", "first_seen": "turn 24", "route": "semantic"},
    "integrations:active": {"page": "integrations", "label": "Active integrations", "first_seen": "turn 24", "route": "semantic"},
    "integrations:stale": {"page": "integrations", "label": "Stale syncs", "first_seen": "turn 24", "route": "semantic"},
    "integrations:disabled": {"page": "integrations", "label": "Disabled integrations", "first_seen": "turn 24", "route": "semantic"},
    "marketplace:listings_in_view": {"page": "marketplace", "label": "Listings in view", "first_seen": "turn 24", "route": "semantic"},
    "marketplace:my_listings": {"page": "marketplace", "label": "My listings", "first_seen": "turn 24", "route": "semantic"},
    "marketplace:current_tab": {"page": "marketplace", "label": "Current tab", "first_seen": "turn 24", "route": "simple_recency"},
    "ph-intelligence:plants_in_network": {"page": "ph-intelligence", "label": "Plants in network", "first_seen": "turn 24", "route": "semantic"},
    "ph-intelligence:top_failure_cause": {"page": "ph-intelligence", "label": "Top failure cause", "first_seen": "turn 24", "route": "semantic"},
    "ph-intelligence:report_freshness": {"page": "ph-intelligence", "label": "Report freshness", "first_seen": "turn 24", "route": "semantic"},
    "project-manager:active_projects": {"page": "project-manager", "label": "Active projects", "first_seen": "turn 24", "route": "semantic"},
    "project-manager:past_end_date": {"page": "project-manager", "label": "Past end date", "first_seen": "turn 24", "route": "semantic"},
    "project-manager:on_hold_planning": {"page": "project-manager", "label": "On hold or planning", "first_seen": "turn 24", "route": "semantic"},
    "report-sender:reports_selected": {"page": "report-sender", "label": "Reports selected", "first_seen": "turn 24", "route": "semantic"},
    "report-sender:recipients": {"page": "report-sender", "label": "Recipients", "first_seen": "turn 24", "route": "semantic"},
    "report-sender:saved_contacts": {"page": "report-sender", "label": "Saved contacts", "first_seen": "turn 24", "route": "semantic"},
    "shift-brain:top_risk_this_shift": {"page": "shift-brain", "label": "Top risk this shift", "first_seen": "turn 24", "route": "semantic"},
    "shift-brain:pms_due": {"page": "shift-brain", "label": "PMs due", "first_seen": "turn 24", "route": "semantic"},
    "shift-brain:carry_forward": {"page": "shift-brain", "label": "Carry-forward", "first_seen": "turn 24", "route": "semantic"},
    "analytics:detail_panel": {"page": "analytics", "label": "Analytics detail breakdown", "first_seen": "turn 30", "route": "semantic"},
    "analytics:results_panel": {"page": "analytics", "label": "Per-machine analytics results", "first_seen": "turn 30", "route": "semantic"},
    "alert-hub:detail_panel": {"page": "alert-hub", "label": "Alert detail breakdown", "first_seen": "turn 30", "route": "None"},
    "alert-hub:amc_assets": {"page": "alert-hub", "label": "AMC assets checked", "first_seen": "turn 30", "route": "None"},
    "alert-hub:amc_pms": {"page": "alert-hub", "label": "AMC PMs flagged", "first_seen": "turn 30", "route": "None"},
    "alert-hub:amc_parts": {"page": "alert-hub", "label": "AMC parts at risk", "first_seen": "turn 30", "route": "None"},
    "alert-hub:amc_crew": {"page": "alert-hub", "label": "AMC crew alerts", "first_seen": "turn 30", "route": "None"},
    "asset-hub:detail_panel": {"page": "asset-hub", "label": "Asset detail breakdown", "first_seen": "turn 30", "route": "None"},
    "asset-hub:logbook_count": {"page": "asset-hub", "label": "Asset logbook entries", "first_seen": "turn 30", "route": "None"},
    "asset-hub:pm_count": {"page": "asset-hub", "label": "Asset PM completions", "first_seen": "turn 30", "route": "None"},
    "asset-hub:last_failure": {"page": "asset-hub", "label": "Asset last failure", "first_seen": "turn 30", "route": "None"},
    "asset-hub:rcm_edges": {"page": "asset-hub", "label": "Asset RCM edges", "first_seen": "turn 30", "route": "None"},
    "pm-scheduler:detail_panel": {"page": "pm-scheduler", "label": "PM detail breakdown", "first_seen": "turn 30", "route": "None"},
    "predictive:detail_panel": {"page": "predictive", "label": "Predictive detail breakdown", "first_seen": "turn 30", "route": "None"},
    "predictive:risk_ranking": {"page": "predictive", "label": "Risk ranking table", "first_seen": "turn 30", "route": "None"},
    "predictive:risk_heatmap": {"page": "predictive", "label": "Risk heatmap", "first_seen": "turn 30", "route": "None"},
    "predictive:mtbf_trend": {"page": "predictive", "label": "MTBF trend panel", "first_seen": "turn 30", "route": "None"},
    "inventory:detail_panel": {"page": "inventory", "label": "Inventory detail breakdown", "first_seen": "turn 30", "route": "None"},
    "skillmatrix:detail_panel": {"page": "skillmatrix", "label": "Skill matrix detail", "first_seen": "turn 30", "route": "None"},
    "hive:detail_panel": {"page": "hive", "label": "Hive supervisor detail", "first_seen": "turn 30", "route": "None"},
    "achievements:detail_panel": {"page": "achievements", "label": "Achievements detail", "first_seen": "turn 30", "route": "None"},
    "achievements:composite_score": {"page": "achievements", "label": "Composite skill score", "first_seen": "turn 30", "route": "None"},
    "achievements:active_domains_stat": {"page": "achievements", "label": "Active domains stat", "first_seen": "turn 30", "route": "None"},
    "achievements:top_domain": {"page": "achievements", "label": "Top skill domain", "first_seen": "turn 30", "route": "None"},
    "dayplanner:detail_panel": {"page": "dayplanner", "label": "Day planner detail", "first_seen": "turn 30", "route": "None"},
    "integrations:detail_panel": {"page": "integrations", "label": "Integrations detail", "first_seen": "turn 30", "route": "None"},
    "integrations:api_config": {"page": "integrations", "label": "API configuration", "first_seen": "turn 30", "route": "None"},
    "integrations:sync_log": {"page": "integrations", "label": "Sync log", "first_seen": "turn 30", "route": "None"},
    "marketplace:detail_panel": {"page": "marketplace", "label": "Marketplace detail", "first_seen": "turn 30", "route": "None"},
    "marketplace:listing_grid": {"page": "marketplace", "label": "Marketplace listing grid", "first_seen": "turn 30", "route": "None"},
    "ph-intelligence:detail_panel": {"page": "ph-intelligence", "label": "PH Intelligence detail", "first_seen": "turn 30", "route": "None"},
    "project-manager:project_list": {"page": "project-manager", "label": "Project list view", "first_seen": "turn 30", "route": "None"},
    "project-manager:project_cards": {"page": "project-manager", "label": "Project card grid", "first_seen": "turn 30", "route": "None"},
    "report-sender:detail_panel": {"page": "report-sender", "label": "Report sender detail", "first_seen": "turn 30", "route": "None"},
    "shift-brain:detail_panel": {"page": "shift-brain", "label": "Shift brain detail", "first_seen": "turn 30", "route": "None"},
}


def check_locked_tiles_present() -> list[dict]:
    issues = []
    for tile_key, meta in TILE_LOCKS.items():
        page_file = meta.get("page", "") + ".html"
        if not os.path.isfile(page_file):
            issues.append({"check": "page_exists", "reason": f"locked page missing: {page_file} (tile {tile_key})"})
            continue
        src = read_file(page_file) or ""
        needle = f'data-rag-tile="{tile_key}"'
        if needle not in src:
            issues.append({"check": "tile_present", "reason": f"locked tile attribute missing: {needle} in {page_file}"})
    return issues


CHECKS = [
    ("tile_present", "RAG flywheel tile-lock invariants (auto-generated)", check_locked_tiles_present),
]


def main() -> int:
    print("\033[1m\nRAG Flywheel L0 Locks Validator\033[0m")
    print("=" * 60)
    print(f"  Locked tiles: {len(TILE_LOCKS)}")
    all_issues = []
    keys = [c[0] for c in CHECKS]
    labels = {c[0]: c[1] for c in CHECKS}
    for key, _label, fn in CHECKS:
        for issue in fn():
            issue.setdefault("check", key)
            all_issues.append(issue)
    n_pass, n_skip, n_fail = format_result(keys, labels, all_issues)
    print()
    if n_fail == 0:
        print(f"  \033[92mAll {n_pass} checks passed.\033[0m")
    else:
        print(f"  \033[91m{n_pass} PASS  {n_skip} SKIP  {n_fail} FAIL\033[0m")
    return 1 if n_fail else 0


if __name__ == "__main__":
    sys.exit(main())
