"""
RAG Flywheel Harness Validator
==============================
Layer-0 ratchet that locks the FLYWHEEL HARNESS itself (not individual
tile-walks — that's `validate_rag_flywheel_locks.py`, auto-generated by
the processor).

  W01  Walk spec exists: tests/journey-rag-flywheel-walk.spec.ts
  W02  Walk spec enumerates [data-rag-tile] selectors
  W03  Walk spec writes per-turn JSONL to .tmp/rag_observations_turn_<N>.jsonl
  W04  Processor exists: tools/rag_flywheel_processor.py
  W05  Processor auto-seeds canonical_sources for new tiles
  W06  Processor writes per-turn report + L2 review queue (manual gate)
  W07  At least 1 of the 5 priority pages exposes ≥1 [data-rag-tile]
  W08  All tiles use the convention data-rag-tile="<page>:<key>"
  W09  RAG flywheel uses LOCAL endpoint (no remote URL hardcoded)
  W10  Walk targets the canonical agentic-rag-loop fn (Phase 1)
"""

from __future__ import annotations
import os
import sys
import re
from pathlib import Path

if sys.platform == "win32":
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

from validator_utils import read_file, format_result

WALK_SPEC      = Path("tests/journey-rag-flywheel-walk.spec.ts")
PROCESSOR      = Path("tools/rag_flywheel_processor.py")
PRIORITY_PAGES = ["analytics.html", "alert-hub.html", "asset-hub.html", "pm-scheduler.html", "predictive.html"]


def _walk() -> str:    return read_file(str(WALK_SPEC)) or ""
def _proc() -> str:    return read_file(str(PROCESSOR)) or ""


def check_walk_exists() -> list[dict]:
    if not WALK_SPEC.is_file():
        return [{"check": "walk_exists", "reason": f"{WALK_SPEC} missing"}]
    return []


def check_walk_enumerates(src: str) -> list[dict]:
    if "data-rag-tile" not in src:
        return [{"check": "walk_enumerates", "reason": "walk spec must enumerate [data-rag-tile] selectors"}]
    return []


def check_walk_writes_jsonl(src: str) -> list[dict]:
    if "rag_observations_turn_" not in src or ".jsonl" not in src:
        return [{"check": "walk_jsonl", "reason": "walk spec must write per-turn JSONL to .tmp/rag_observations_turn_<N>.jsonl"}]
    return []


def check_processor_exists() -> list[dict]:
    if not PROCESSOR.is_file():
        return [{"check": "processor_exists", "reason": f"{PROCESSOR} missing"}]
    return []


def check_processor_seeds(src: str) -> list[dict]:
    if "canonical_sources" not in src or "seed_canonical" not in src:
        return [{"check": "processor_seeds", "reason": "processor must auto-seed canonical_sources for new tiles"}]
    return []


def check_processor_writes_report(src: str) -> list[dict]:
    if "flywheel_turn_" not in src or "build_report" not in src:
        return [{"check": "processor_report", "reason": "processor must build a per-turn flywheel_turn_<N>_report.md"}]
    if "l2_review" not in src.lower():
        return [{"check": "processor_l2_queue", "reason": "processor must write an L2 review queue (manual gate per user decision)"}]
    return []


def check_at_least_one_page_tagged() -> list[dict]:
    tagged = []
    for p in PRIORITY_PAGES:
        if not os.path.isfile(p): continue
        src = read_file(p) or ""
        if "data-rag-tile" in src: tagged.append(p)
    if not tagged:
        return [{"check": "page_tagged", "reason": f"None of the priority pages have data-rag-tile attributes yet: {PRIORITY_PAGES}"}]
    return []


def check_tile_attr_convention() -> list[dict]:
    issues = []
    pat = re.compile(r'data-rag-tile="([^"]+)"')
    for p in PRIORITY_PAGES:
        if not os.path.isfile(p): continue
        src = read_file(p) or ""
        for m in pat.finditer(src):
            val = m.group(1)
            if ":" not in val:
                issues.append({"check": "tile_convention", "reason": f'{p}: data-rag-tile="{val}" must follow "<page>:<key>" convention'})
    return issues


def check_uses_local_endpoint(src: str) -> list[dict]:
    # Walk spec must target local (127.0.0.1:54321), never a remote URL.
    if "127.0.0.1:54321" not in src:
        return [{"check": "local_endpoint", "reason": "walk spec must use 127.0.0.1:54321 (local Supabase) per local-first rule"}]
    if re.search(r"https://[a-z0-9-]+\.supabase\.co/functions", src):
        return [{"check": "local_endpoint", "reason": "walk spec references a REMOTE Supabase URL — must be local-only"}]
    return []


def check_targets_agentic_loop(src: str) -> list[dict]:
    if "/functions/v1/agentic-rag-loop" not in src:
        return [{"check": "targets_agentic", "reason": "walk spec must POST to the agentic-rag-loop edge fn (Phase 1 canonical entrypoint)"}]
    return []


CHECKS = [
    ("walk_exists",        "W01 Walk spec exists",                                 check_walk_exists),
    ("walk_enumerates",    "W02 Walk enumerates [data-rag-tile]",                  lambda: check_walk_enumerates(_walk())),
    ("walk_jsonl",         "W03 Walk writes per-turn JSONL",                       lambda: check_walk_writes_jsonl(_walk())),
    ("processor_exists",   "W04 Processor exists",                                  check_processor_exists),
    ("processor_seeds",    "W05 Processor auto-seeds canonical_sources",            lambda: check_processor_seeds(_proc())),
    ("processor_report",   "W06 Processor writes report + L2 review queue",         lambda: check_processor_writes_report(_proc())),
    ("page_tagged",        "W07 ≥1 priority page has [data-rag-tile]",              check_at_least_one_page_tagged),
    ("tile_convention",    "W08 Tile attrs follow <page>:<key> convention",         check_tile_attr_convention),
    ("local_endpoint",     "W09 Walk uses LOCAL endpoint (127.0.0.1:54321)",        lambda: check_uses_local_endpoint(_walk())),
    ("targets_agentic",    "W10 Walk targets /functions/v1/agentic-rag-loop",       lambda: check_targets_agentic_loop(_walk())),
]


def main() -> int:
    print("\033[1m\nRAG Flywheel Harness Validator\033[0m")
    print("=" * 60)
    all_issues = []
    keys = [c[0] for c in CHECKS]
    labels = {c[0]: c[1] for c in CHECKS}
    for key, _label, fn in CHECKS:
        for issue in fn():
            issue.setdefault("check", key)
            all_issues.append(issue)
    n_pass, n_skip, n_fail = format_result(keys, labels, all_issues)
    print()
    if n_fail == 0:
        print(f"  \033[92mAll {n_pass} checks passed.\033[0m")
    else:
        print(f"  \033[91m{n_pass} PASS  {n_skip} SKIP  {n_fail} FAIL\033[0m")
    return 1 if n_fail else 0


if __name__ == "__main__":
    sys.exit(main())
