/**
 * achievements.html — UI smoke.
 * Auto-generated by tools/gen_smoke_specs.py. Add page-specific
 * form/flow tests in a separate describe block if needed.
 */
import { test, expect } from './_fixtures';
import { smokePage } from './_smoke-template';

test.describe('achievements.html smoke', () => {
  test('loads and renders without page errors', async ({ whPage }) => {
    await smokePage(whPage, '/achievements.html', {});
  });
});
