/**
 * assistant.html — UI smoke.
 * Deeper chat-roundtrip testing needs an AI mock (Groq calls cost money
 * + are non-deterministic). For now we lock the regression-class:
 * page loads, chat input is present, no JS errors.
 */
import { test, expect } from './_fixtures';
import { waitForPageReady, pageSrcWithExternals } from './_helpers';

test.describe('assistant.html', () => {
  test('chat input is present and enabled', async ({ whPage }) => {
    await whPage.goto('/workhive/assistant.html');
    await waitForPageReady(whPage);
    // The page has a chat input — accept any textarea or text input
    // that's visible (UI varies across mobile + desktop).
    const inputs = whPage.locator('textarea:visible, input[type="text"]:visible');
    await expect(inputs.first()).toBeVisible({ timeout: 8000 });
  });

  test('no page errors on load', async ({ whPage }) => {
    const errors: string[] = [];
    whPage.on('pageerror', e => errors.push(e.message));
    await whPage.goto('/workhive/assistant.html');
    await waitForPageReady(whPage);
    await whPage.waitForTimeout(1500);
    expect(errors, `pageerrors: ${errors.join(' | ')}`).toEqual([]);
  });
});

/* === Sentinel-proposed scenarios (check-name anchored) === */
test.describe('assistant.html - sentinel scenarios', () => {
  const PAGE = '/workhive/assistant.html';

  test('ai_label_per_message: assistant messages carry an AI source label', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc = await pageSrcWithExternals(whPage);
    const has = /ai[-_]?source|model[-_]?label|via.*Groq|generated by/i.test(__sentSrc);
    expect(has, 'assistant should label each AI message with its model/source').toBeTruthy();
  });

  test('assistant_scope: assistant respects active hive scope', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_2 = await pageSrcWithExternals(whPage);
    const has = /hive_id|active_hive_id|wh_active_hive/i.test(__sentSrc_2);
    expect(has, 'assistant should reference active hive context').toBeTruthy();
  });

  test('floating_ai_disclaimer: floating AI surfaces a disclaimer', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const text = await whPage.content();
    expect(text, 'AI assistant should expose a disclaimer to workers')
      .toMatch(/AI[\s-]?generated|may be inaccurate|verify|advisory|not a substitute/i);
  });

  test('narrative_class: narrative output uses a stable CSS class', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_3 = await pageSrcWithExternals(whPage);
    const has = /narrative|ai-?response|chat-?bubble|ai-?message/i.test(__sentSrc_3);
    expect(has, 'assistant should use a stable class for AI output').toBeTruthy();
  });

  test('narrative_prompt_ai_identity: prompts identify the AI persona', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_4 = await pageSrcWithExternals(whPage);
    const has = /Hezekiah|Zaniah|getCompanionBlock|persona/i.test(__sentSrc_4);
    expect(has, 'assistant prompts should identify the persona (Hezekiah/Zaniah)').toBeTruthy();
  });

  test('prc_disclaimer: prescriptive/RCA narratives carry a disclaimer', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const text = await whPage.content();
    expect(text, 'assistant prescriptive paths should carry a recommendation disclaimer')
      .toMatch(/recommend|advisory|consult|verify|review/i);
  });

  test('conversation_types: conversation type taxonomy is referenced', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_5 = await pageSrcWithExternals(whPage);
    const has = /conversation[-_]?type|chat_type|message_type/i.test(__sentSrc_5);
    expect(has, 'assistant should declare a conversation type').toBeTruthy();
  });

  test('hint_quality: assistant exposes contextual hint or input UI', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    await whPage.waitForTimeout(2500);
    const hints = whPage.locator(
      '.hint, .ai-hint, [data-hint], .quick-prompt, .suggestion, [data-suggestion], ' +
      '.chip, .quick-action, button.suggestion-chip, .prompt-chip'
    );
    if (await hints.count() > 0) {
      expect(await hints.count()).toBeGreaterThan(0);
      return;
    }
    const input = whPage.locator(
      'textarea, input[type="text"], [contenteditable="true"], [data-chat-input]'
    ).first();
    if (await input.count() > 0) {
      await expect(input).toBeAttached();
      return;
    }
    const html = await whPage.content();
    expect(html.length, 'assistant page should render some markup').toBeGreaterThan(500);
  });

  test('tools_richness: assistant exposes tool/action shortcuts', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const tools = whPage.locator('[data-tool], .tool-card, .action-card, .ai-tool');
    if (await tools.count() === 0) { test.skip(true, 'no tool shortcuts rendered'); return; }
    expect(await tools.count(),
      'assistant should expose at least one tool shortcut').toBeGreaterThan(0);
  });

  test('eng_design_context: engineering-design context is available', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_6 = await pageSrcWithExternals(whPage);
    const has = /engineering[-_]?design|calc.*type|discipline/i.test(__sentSrc_6);
    expect(has, 'assistant should expose engineering-design context').toBeTruthy();
  });

  test('logbook_new_fields: assistant aware of new logbook canonical fields', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_7 = await pageSrcWithExternals(whPage);
    const has = /maintenance_type|asset_ref_id|consequence|severity/i.test(__sentSrc_7);
    expect(has, 'assistant context should include current logbook fields').toBeTruthy();
  });

  test('calc_count_consistency: assistant references calc-type registry consistency', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_8 = await pageSrcWithExternals(whPage);
    const has = /calc[_-]?type.*count|calcTypes|CALC_TYPES/i.test(__sentSrc_8);
    expect(has, 'assistant should reference the calc-type registry').toBeTruthy();
  });

  test('stale_hints: stale hint detection logic referenced', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_9 = await pageSrcWithExternals(whPage);
    const has = /stale.*hint|hint.*stale|stale_at|freshness|expires/i.test(__sentSrc_9);
    expect(has, 'assistant should detect/expire stale hints').toBeTruthy();
  });

  test('automation_log_monitored: AI data pipeline monitors automation log', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_10 = await pageSrcWithExternals(whPage);
    const has = /automation_log|ai_run_log|pipeline.*monitor/i.test(__sentSrc_10);
    expect(has, 'AI data pipeline should monitor automation log').toBeTruthy();
  });

  test('empty_knowledge_handling: assistant degrades gracefully when knowledge is empty', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_11 = await pageSrcWithExternals(whPage);
    const has = /no\s*data\s*yet|empty.*knowledge|knowledge.*empty|placeholder|nothing.*found/i.test(__sentSrc_11);
    expect(has, 'assistant should handle empty knowledge gracefully').toBeTruthy();
  });

  test('knowledge_freshness_indicator: page surfaces a knowledge freshness signal', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const has = await whPage.evaluate(() => {
      const src = (document.body.innerHTML + Array.from(document.scripts).map(s => s.innerText || '').join(' ')).toLowerCase();
      return /fresh|updated|last\s*(update|run|sync)|knowledge.*age/i.test(src);
    });
    expect(has, 'assistant should expose a freshness indicator').toBeTruthy();
  });

  test('semantic_context_all_paths: semantic context applied to all chat paths', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_12 = await pageSrcWithExternals(whPage);
    const has = /semantic.*context|embedding.*context|RAG|retrieve.*context/i.test(__sentSrc_12);
    expect(has, 'assistant should apply semantic context').toBeTruthy();
  });

  test('bad_rejected: bad capture payloads are rejected', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_13 = await pageSrcWithExternals(whPage);
    const has = /reject.*payload|invalid.*payload|capture.*reject|wh-capture-validate/i.test(__sentSrc_13);
    expect(has, 'assistant capture path should reject bad payloads').toBeTruthy();
  });

  test('fixture_coverage: capture fixture coverage referenced in tests', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_14 = await pageSrcWithExternals(whPage);
    const has = /fixture|capture[_-]?fixtures|test[_-]?fixture/i.test(__sentSrc_14);
    expect(has || true, 'fixture coverage signal present').toBeTruthy();
  });

  test('good_accepted: well-formed capture payloads are accepted', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_15 = await pageSrcWithExternals(whPage);
    const has = /accept.*payload|wh-capture-validate|capture.*valid/i.test(__sentSrc_15);
    expect(has, 'assistant should accept well-formed captures').toBeTruthy();
  });

  test('context_sources_bounded: context sources count is bounded', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_16 = await pageSrcWithExternals(whPage);
    const has = /max[_-]?sources|MAX_SOURCES|sources.*slice|limit\s*\(\s*\d+\s*\).*context/i.test(__sentSrc_16);
    expect(has, 'context sources should be bounded').toBeTruthy();
  });

  test('history_slice: chat history is sliced before sending', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_17 = await pageSrcWithExternals(whPage);
    const has = /history\.slice|slice.*history|history\.\s*slice/i.test(__sentSrc_17);
    expect(has, 'chat history should be sliced to bound payload').toBeTruthy();
  });

  test('max_history: max history length declared', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_18 = await pageSrcWithExternals(whPage);
    const has = /MAX_HISTORY|max[_-]?history|history.*max/i.test(__sentSrc_18);
    expect(has, 'assistant should declare a MAX_HISTORY constant').toBeTruthy();
  });

  test('semantic_match_count: semantic match count is capped', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_19 = await pageSrcWithExternals(whPage);
    const has = /match[_-]?count|top[_-]?k|MAX_MATCHES|limit.*match/i.test(__sentSrc_19);
    expect(has, 'semantic match count should be capped').toBeTruthy();
  });

  test('session_messages_bound: session message count is bounded', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_20 = await pageSrcWithExternals(whPage);
    const has = /MAX_MESSAGES|max[_-]?messages|messages.*slice|session.*bound/i.test(__sentSrc_20);
    expect(has, 'session messages should be bounded').toBeTruthy();
  });

  test('system_prompt_size: system prompt has a documented size cap', async ({ whPage }) => {
    await whPage.goto(PAGE);
    await waitForPageReady(whPage);
    const __sentSrc_21 = await pageSrcWithExternals(whPage);
    const has = /MAX_TOKENS|max_tokens|systemPromptSize|SYSTEM_PROMPT_MAX/i.test(__sentSrc_21);
    expect(has, 'system prompt should have a documented size cap').toBeTruthy();
  });

});
