"""
Phase 3: Semantic RAG Knowledge Base seeder

Populates kb_documents and kb_chunks with sample maintenance documentation.
Used for semantic search and citation in Rosa/James responses.
"""

def seed_kb_documents_and_chunks(client, log, ctx):
    """Seed knowledge base documents and chunks for semantic RAG."""

    log("\n[Voice Companion Phase 3] Seeding KB documents and chunks...")

    # Get first hive for seeding
    hives = ctx.get("hives", [])
    if not hives:
        log("  SKIP: No hives found, cannot seed KB")
        return 0
    hive_id = hives[0]["id"]

    # Sample documents (realistic maintenance manuals)
    documents = [
        {
            "title": "Centrifugal Pump Maintenance Manual",
            "content": """
Centrifugal pumps are critical equipment. Key maintenance items:

CAVITATION PREVENTION:
Cavitation occurs when vapor bubbles form in the pump, causing noise, vibration, and erosion.
To prevent cavitation:
1. Ensure Net Positive Suction Head (NPSH) is adequate
2. Check suction side for blockages or restrictions
3. Verify pump inlet filter is clean (replace every 90 days)
4. Maintain proper flow rate and pressure within design range
5. Monitor seal condition for leakage

SEAL REPLACEMENT:
Replace pump seals every 6 months or every 500 operating hours, whichever comes first.
Use OEM-approved seals only. Improper seal installation causes catastrophic failure.

BEARING LUBRICATION:
Use ISO VG 32 turbine oil. Change every 250 operating hours or annually.
Check bearing temperature: normal range 50-65°C. Above 70°C indicates excessive wear.
""",
            "file_type": "application/pdf",
        },
        {
            "title": "Electric Motor Troubleshooting Guide",
            "content": """
MOTOR VIBRATION ISSUES:
Excessive vibration can indicate:
1. Rotor imbalance - Have motor rebalanced by certified technician
2. Misalignment with pump - Check coupling alignment within 0.05mm tolerance
3. Bearing wear - Replace bearings if play exceeds 0.1mm
4. Loose mounting bolts - Torque all bolts to specification sheet

TEMPERATURE MONITORING:
Normal motor operating temperature: 60-80°C ambient + load.
Shutdown if temperature exceeds 100°C to prevent winding insulation failure.
Use thermal imaging to identify hot spots that indicate internal issues.

PREVENTIVE MAINTENANCE:
- Monitor vibration weekly using ISO 10816 standard
- Thermography monthly on bearing housings
- Megohm test annually on windings (minimum 10 MOhm)
- Lubricant analysis every 500 hours
""",
            "file_type": "text/plain",
        },
        {
            "title": "Reliability Engineering Best Practices",
            "content": """
MTTR IMPROVEMENT STRATEGIES:
To reduce Mean Time To Repair:
1. Stock critical spare parts (bearings, seals, coupling kits)
2. Maintain technician cross-training on all equipment
3. Create and test failure response procedures quarterly
4. Document all repairs with root cause analysis
5. Use condition monitoring to detect failures early

RCM (Reliability Centered Maintenance):
- Criticality: Equipment with risk score > 0.8 requires condition-based maintenance
- Preventive PM intervals based on MTBF, not calendar
- Condition monitoring data (vibration, temperature, oil analysis) guides scheduling
- Deferred maintenance on low-criticality items until planned downtime

ASSET LIFECYCLE:
- Years 0-2: Infant mortality phase (manufacturing defects). Warranty repairs.
- Years 2-8: Useful life. Normal failure rate. Preventive maintenance optimal.
- Years 8+: Wear-out phase. Failure rate increases exponentially. Consider replacement.
""",
            "file_type": "text/markdown",
        }
    ]

    # Insert documents
    doc_rows = []
    for doc in documents:
        try:
            res = client.from_('kb_documents').insert({
                'hive_id': hive_id,
                'title': doc['title'],
                'content_type': doc['file_type'],
                'embedding_status': 'complete',  # Skip embedding for test data
            }).execute()

            if res.data and len(res.data) > 0:
                doc_rows.append(res.data[0])
                log(f"  Created KB document: {doc['title']}")
            else:
                log(f"  WARN: Could not insert KB document {doc['title']}")
        except Exception as e:
            log(f"  ERROR creating KB document {doc['title']}: {e}")

    # Create chunks (text snippets with embeddings for semantic search)
    # Note: In production, chunks are generated by edge function with embeddings
    # For testing, we create pre-made chunks with dummy embeddings

    chunks_data = [
        # Cavitation chunks
        {
            "doc_title": "Centrifugal Pump Maintenance Manual",
            "chunk_text": "Cavitation occurs when vapor bubbles form in the pump, causing noise, vibration, and erosion. To prevent cavitation: ensure NPSH is adequate, check suction side for blockages, verify pump inlet filter is clean (replace every 90 days), maintain proper flow rate and pressure.",
            "chunk_num": 1,
        },
        {
            "doc_title": "Centrifugal Pump Maintenance Manual",
            "chunk_text": "Replace pump seals every 6 months or every 500 operating hours. Use OEM-approved seals only. Improper seal installation causes catastrophic failure.",
            "chunk_num": 2,
        },
        # Vibration chunks
        {
            "doc_title": "Electric Motor Troubleshooting Guide",
            "chunk_text": "Excessive motor vibration can indicate rotor imbalance (have rebalanced by technician), misalignment with pump (check coupling within 0.05mm), bearing wear (replace if play exceeds 0.1mm), or loose mounting bolts (torque to spec).",
            "chunk_num": 1,
        },
        # Temperature chunks
        {
            "doc_title": "Electric Motor Troubleshooting Guide",
            "chunk_text": "Normal motor operating temperature is 60-80°C above ambient load. Shutdown if temperature exceeds 100°C to prevent winding insulation failure. Use thermal imaging to identify hot spots.",
            "chunk_num": 2,
        },
        # MTTR chunks
        {
            "doc_title": "Reliability Engineering Best Practices",
            "chunk_text": "To reduce Mean Time To Repair (MTTR), stock critical spare parts (bearings, seals, coupling kits), maintain technician cross-training, create and test failure response procedures quarterly, document all repairs with root cause analysis, and use condition monitoring to detect failures early.",
            "chunk_num": 1,
        },
        # RCM chunks
        {
            "doc_title": "Reliability Engineering Best Practices",
            "chunk_text": "Reliability Centered Maintenance: Criticality scoring above 0.8 requires condition-based monitoring. Use vibration, temperature, and oil analysis to guide PM scheduling rather than fixed calendar intervals.",
            "chunk_num": 2,
        },
    ]

    # Insert chunks (link to first document for testing)
    if doc_rows:
        doc_id = doc_rows[0]['id']
        chunk_inserted = 0

        for chunk in chunks_data:
            try:
                res = client.from_('kb_chunks').insert({
                    'doc_id': doc_id,
                    'chunk_num': chunk['chunk_num'],
                    'text': chunk['chunk_text'],
                    'embedding': None,  # Dummy: embeddings would be 384-dim vectors
                }).execute()

                if res.data:
                    chunk_inserted += 1
            except Exception as e:
                log(f"  WARN: Could not insert KB chunk: {e}")

        log(f"  Inserted {chunk_inserted} knowledge chunks for semantic search")

    log(f"  Phase 3 seeding complete: {len(doc_rows)} documents, ready for RAG")
    return len(doc_rows)


# Hook for test-data-seeder orchestrator
def run(client, log, ctx):
    """
    Entry point for test-data-seeder.
    Expected signature: run(client, log, ctx) -> int (rows inserted)
    """
    return seed_kb_documents_and_chunks(client, log, ctx)
