#!/usr/bin/env python3
"""
pm_deepwalk_scoreboard.py — the MEASURED anti-drift %-board for the PM SCHEDULER DEEPWALK EXPANSION arc.

Reads asset_hub_deepwalk_state.json and emits two boards (see ASSET_HUB_DEEPWALK_EXPANSION_ROADMAP.md §4):
  1. JOURNEY board — done_phases / (journeys x 5 phases), phase in done / partial (0.5) / todo
  2. CLASS board   — AHK classes x 6 stages (harvest -> define -> detect -> sweep -> fix -> gate)

WHY THIS EXISTS: a % that is asserted in prose drifts; a % computed from state cannot. Same
instrument as the marketplace (11.6% -> 100%) and hive (0 -> 100%) expansion arcs
([[feedback_measured_percent_not_qualitative_done]]).

FORWARD-ONLY: asset_hub_deepwalk_baseline.json holds the floor. A DROP fails the build, so a walked
cell cannot silently revert; `--accept` ratchets the floor UP after real progress.

★ shallow_W GUARD (caught over-crediting twice on the marketplace board): a journey may not claim
W=done without >=2 personas AND >=2 states recorded in `walked`. Without it "walked" quietly
degrades into "opened the page once as myself" — the exact shallowness this arc exists to kill.
A violation is reported and the cell is scored as `partial`, not `done`.

Self-test: `--selftest` (pure arithmetic + the guard, no files).
"""
from __future__ import annotations
import io, json, sys
from pathlib import Path

if sys.platform == "win32":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent
STATE = ROOT / "asset_hub_deepwalk_state.json"
BASELINE = ROOT / "asset_hub_deepwalk_baseline.json"
REPORT = ROOT / "ASSET_HUB_DEEPWALK_SCOREBOARD.md"

GREEN, RED, YELLOW, BOLD, RESET = "\033[92m", "\033[91m", "\033[93m", "\033[1m", "\033[0m"
PHASES = ["G", "W", "O", "H", "R"]
STAGES = ["harvest", "define", "detect", "sweep", "fix", "gate"]
VAL = {"done": 1.0, "partial": 0.5, "todo": 0.0}


def _score(v) -> float:
    return VAL.get(str(v).strip().lower(), 0.0)


def measure(state: dict) -> dict:
    journeys = state.get("journeys", {})
    classes = state.get("dim_classes", {})

    shallow = []
    j_earned = j_total = 0.0
    per_phase = {p: [0.0, 0] for p in PHASES}

    for jid, j in sorted(journeys.items()):
        phases = j.get("phases", {})
        walked = j.get("walked", {}) or {}
        n_pers = len(set(walked.get("personas", []) or []))
        n_stat = len(set(walked.get("states", []) or []))
        for p in PHASES:
            v = _score(phases.get(p, "todo"))
            # The guard: W=done is only credible with >=2 personas AND >=2 states.
            if p == "W" and v == 1.0 and (n_pers < 2 or n_stat < 2):
                shallow.append(f"{jid} (personas={n_pers}, states={n_stat})")
                v = 0.5
            j_earned += v
            j_total += 1
            per_phase[p][0] += v
            per_phase[p][1] += 1

    c_earned = c_total = 0.0
    for cid, c in sorted(classes.items()):
        stages = c.get("stages", {})
        for s in STAGES:
            c_earned += _score(stages.get(s, "todo"))
            c_total += 1

    jp = (j_earned / j_total * 100) if j_total else 0.0
    cp = (c_earned / c_total * 100) if c_total else 0.0
    return {
        "journeys_pct": round(jp, 1),
        "classes_pct": round(cp, 1),
        "overall_pct": round((jp + cp) / 2, 1),
        "n_journeys": len(journeys),
        "n_classes": len(classes),
        "per_phase": {p: round((per_phase[p][0] / per_phase[p][1] * 100), 1) if per_phase[p][1] else 0.0
                      for p in PHASES},
        "shallow_W": shallow,
    }


def _write_report(m: dict, state: dict) -> None:
    lines = [
        "# Asset Hub Deepwalk — MEASURED %-board",
        "",
        "_Generated by `tools/pm_deepwalk_scoreboard.py` from `asset_hub_deepwalk_state.json`._",
        "_Never hand-edit: this file is derived. Change the state, re-run the tool._",
        "",
        f"- **Journeys:** {m['journeys_pct']}%  ({m['n_journeys']} journeys x 5 phases)",
        f"- **Classes:**  {m['classes_pct']}%  ({m['n_classes']} AHK classes x 6 stages)",
        f"- **OVERALL:**  {m['overall_pct']}%",
        "",
        "| Phase | % |",
        "|---|---:|",
    ]
    for p in PHASES:
        lines.append(f"| {p} | {m['per_phase'][p]}% |")
    if m["shallow_W"]:
        lines += ["", "## Shallow W (claimed done without >=2 personas AND >=2 states)", ""]
        lines += [f"- {s}" for s in m["shallow_W"]]
    lines += ["", "## Journeys", "", "| Journey | G | W | O | H | R |", "|---|---|---|---|---|---|"]
    for jid, j in sorted(state.get("journeys", {}).items()):
        ph = j.get("phases", {})
        lines.append("| " + jid + " | " + " | ".join(str(ph.get(p, "todo"))[0].upper() for p in PHASES) + " |")
    lines += ["", "## Classes", "", "| Class | " + " | ".join(STAGES) + " |",
              "|---|" + "---|" * len(STAGES)]
    for cid, c in sorted(state.get("dim_classes", {}).items()):
        st = c.get("stages", {})
        lines.append("| " + cid + " | " + " | ".join(str(st.get(s, "todo"))[0].upper() for s in STAGES) + " |")
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def selftest() -> int:
    ok = True

    def chk(label, got, want):
        nonlocal ok
        good = got == want
        ok &= good
        print(f"  {GREEN+'PASS'+RESET if good else RED+'FAIL'+RESET}  {label}: got {got}, want {want}")

    empty = {"journeys": {"a": {"phases": {p: "todo" for p in PHASES}, "walked": {}}},
             "dim_classes": {"K": {"stages": {s: "todo" for s in STAGES}}}}
    chk("all todo is 0%", measure(empty)["overall_pct"], 0.0)

    full = {"journeys": {"a": {"phases": {p: "done" for p in PHASES},
                              "walked": {"personas": ["x", "y"], "states": ["s1", "s2"]}}},
            "dim_classes": {"K": {"stages": {s: "done" for s in STAGES}}}}
    chk("all done is 100%", measure(full)["overall_pct"], 100.0)

    half = {"journeys": {"a": {"phases": {p: "partial" for p in PHASES}, "walked": {}}},
            "dim_classes": {"K": {"stages": {s: "partial" for s in STAGES}}}}
    chk("all partial is 50%", measure(half)["overall_pct"], 50.0)

    # The guard: W=done with one persona must NOT score as done.
    shallow = {"journeys": {"a": {"phases": {"G": "todo", "W": "done", "O": "todo", "H": "todo", "R": "todo"},
                                 "walked": {"personas": ["only-me"], "states": ["one"]}}},
               "dim_classes": {}}
    r = measure(shallow)
    chk("shallow W is caught", len(r["shallow_W"]), 1)
    chk("shallow W scores 0.5 not 1.0", r["per_phase"]["W"], 50.0)

    deep = {"journeys": {"a": {"phases": {"G": "todo", "W": "done", "O": "todo", "H": "todo", "R": "todo"},
                              "walked": {"personas": ["a", "b"], "states": ["s1", "s2"]}}},
            "dim_classes": {}}
    chk("deep W scores full", measure(deep)["per_phase"]["W"], 100.0)
    print(f"\n  SELFTEST: {GREEN+'PASS'+RESET if ok else RED+'FAIL'+RESET}")
    return 0 if ok else 1


def main() -> int:
    if "--selftest" in sys.argv:
        return selftest()
    if not STATE.exists():
        print(f"{RED}FAIL{RESET}  missing {STATE.name}")
        return 1
    state = json.loads(STATE.read_text(encoding="utf-8"))
    m = measure(state)
    _write_report(m, state)

    base = {}
    if BASELINE.exists():
        try:
            base = json.loads(BASELINE.read_text(encoding="utf-8"))
        except Exception:
            base = {}
    bj, bc = base.get("journeys_pct", 0.0), base.get("classes_pct", 0.0)

    print(f"{BOLD}Asset Hub Deepwalk — anti-drift %-board{RESET}")
    print(f"  journeys : {m['journeys_pct']}%  ({m['n_journeys']} journeys x 5 phases)   baseline {bj}%")
    print(f"  classes  : {m['classes_pct']}%  ({m['n_classes']} AHK classes x 6 stages)   baseline {bc}%")
    print(f"  OVERALL  : {m['overall_pct']}%")
    print("  per phase: " + " · ".join(f"{p} {m['per_phase'][p]}%" for p in PHASES))
    print(f"  -> {REPORT.name}")

    if m["shallow_W"]:
        print(f"  {YELLOW}shallow W{RESET} (needs >=2 personas AND >=2 states): " + "; ".join(m["shallow_W"][:4]))

    if "--accept" in sys.argv:
        # A RATCHET ONLY TURNS ONE WAY (2026-07-28, found on the project-manager board).
        # This used to write the measurement straight to the baseline in EITHER direction, and
        # returned before the drop-check below — so `--accept` would happily LOWER the floor while
        # printing "ACCEPTED". It cost a real regression: a mis-typed state value scored five
        # phases at 0, the board fell, and --accept banked the lower number as the new floor. A
        # ratchet that the advancing command can re-point downward is not protecting anything.
        _dropped = [(n, b, c) for n, b, c in
                    (("journeys", bj, m["journeys_pct"]), ("classes", bc, m["classes_pct"]))
                    if c < b]
        if _dropped:
            for _n, _b, _c in _dropped:
                print(f"  {RED}ACCEPT REFUSED{RESET}  {_n} {_b}% -> {_c}% is a DROP; the floor only "
                      f"moves up. Fix the state (or the walk) rather than re-baselining down.")
            return 1
        BASELINE.write_text(json.dumps(
            {"journeys_pct": m["journeys_pct"], "classes_pct": m["classes_pct"]}, indent=2), encoding="utf-8")
        print(f"  {GREEN}ACCEPTED{RESET}  baseline -> journeys {m['journeys_pct']}% / classes {m['classes_pct']}%")
        return 0

    if m["journeys_pct"] < bj or m["classes_pct"] < bc:
        print(f"  {RED}FAIL{RESET}  board DROPPED below the ratchet "
              f"(journeys {bj}->{m['journeys_pct']}, classes {bc}->{m['classes_pct']})")
        return 1
    print(f"  {GREEN}PASS{RESET}  board held at or above the ratchet")
    return 0


if __name__ == "__main__":
    sys.exit(main())
