#!/usr/bin/env python3
"""emit_expansion_catalog_md.py — regenerate the T201-T500 catalog block in the roadmap.

The full 8-field pain-register skeleton (Story/Route/Layers/Known receipts/Pain probes/Fix
targets/Instrument close/Lock+done) is authored per arc WHEN IT IS WALKED — that is the program,
not this expansion (token economy: 300 full skeletons before a single walk is waste). What the
roadmap carries now is a COMPACT, navigable catalog: one grounded line per trajectory (id · title ·
its real page or its authored story), grouped by wave, GENERATED from the registry so it cannot
drift. Marked block, single writer, exactly like the header scoreboard.

  (default)  rewrite the block in place (inserts it after ##THE TARGET on first run)
  --check    exit 1 if the committed block differs from a regeneration
"""
from __future__ import annotations

import io
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "trajectory_registry.json"
ROADMAP = ROOT / "UFAI_TRAJECTORY_ROADMAP.md"
START = "<!-- EXPANSION_CATALOG_START (generated by tools/emit_expansion_catalog_md.py — do not hand-edit) -->"
END = "<!-- EXPANSION_CATALOG_END -->"
ANCHOR = "## Pain registers (landed)"  # insert the block just before this section on first run

WAVE_NAMES = {
    "T": "Public Learn funnel", "U": "Public Tools funnel", "V": "Edge-function layer",
    "W": "Security & adversarial personas", "X": "Accessibility spectrum",
    "Y": "New human personas", "Z": "Data pathology deep", "AA": "Financial & economic edge",
    "AB": "Federation & multi-org", "AC": "Platform-evolution & longitudinal",
    "AD": "Ops & observability surfaces", "AE": "Compound systemic failures",
    # VEHICLE SEED (2026-09-02): named wave, non-T-numbered ids (★×16: generator grows with the registry)
    "VM": "Vehicle lane: solo + fleet",
    "VD": "Real-document extraction proving ground",
    "VP": "Production deepwalk: personas x every page",
}
WAVE_ORDER = ["T", "U", "V", "W", "X", "Y", "Z", "AA", "AB", "AC", "AD", "AE", "VM", "VD", "VP"]

# ★SECOND PROGRAM P1-P500 (2026-09-05) — rendered as its OWN section below the first program's
# catalog. ★×16: the wave names/sizes are IMPORTED from tools/seed_p_program_catalog.py, the one
# file that declares them, so this generated surface cannot disagree with the seeder or the gate.
try:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from seed_p_program_catalog import WAVES as _P_WAVES
    P_WAVE_NAMES = {w: n for w, n, _ in _P_WAVES}
    P_WAVE_ORDER = [w for w, _, _ in _P_WAVES]
except Exception:
    P_WAVE_NAMES, P_WAVE_ORDER = {}, []


def _idnum(tid: str) -> int:
    digits = "".join(c for c in tid if c.isdigit())
    return int(digits) if digits else 0


def render() -> str:
    reg = json.loads(REGISTRY.read_text(encoding="utf-8"))
    exp = [t for t in reg["trajectories"] if t["wave"] in WAVE_NAMES]
    lines = [START, "",
             "## Expansion catalog — T201–T500 (specced 2026-08-31)", "",
             f"The 300 expansion arcs, all at the honest `specced` (5%) starting status. The three "
             f"mechanical waves (T/U/V, {sum(1 for t in exp if t['wave'] in 'TUV')} arcs) are grounded "
             "one-per-real-file by `tools/seed_expansion_catalog.py`; the eight bespoke families "
             f"(W–AE, {sum(1 for t in exp if t['wave'] not in ('T','U','V'))} arcs) are hand-authored "
             "stories. Each is walked with the existing T1 method, wave by wave, under the momentum "
             "drive. This block is GENERATED from the registry — the header scoreboard above owns the "
             "live percentages.", ""]
    by_wave: dict[str, list[dict]] = {}
    for t in exp:
        by_wave.setdefault(t["wave"], []).append(t)
    for w in WAVE_ORDER:
        rows = sorted(by_wave.get(w, []), key=lambda t: _idnum(t["id"]))
        if not rows:
            continue
        first, last = rows[0]["id"], rows[-1]["id"]
        lines.append(f"### Wave {w} — {WAVE_NAMES[w]} ({first}–{last}, {len(rows)})")
        for t in rows:
            ground = (t["pages"][0] if t.get("pages") else "") or t.get("story", "")
            lines.append(f"- **{t['id']}** · {t['title']}" + (f" — _{ground}_" if ground else ""))
        lines.append("")

    # ── SECOND PROGRAM P1-P500 (2026-09-05) ──────────────────────────────────────────────────
    # Rendered compactly: 500 one-line rows would bury the doc, so each P wave shows its size,
    # its id range, its layers and its named probe LENSES (the axis that actually differs
    # row-to-row), with the per-row detail living in the registry. Same single-writer rule.
    pex = [t for t in reg["trajectories"] if t["wave"] in P_WAVE_NAMES]
    if pex:
        p_by: dict[str, list[dict]] = {}
        for t in pex:
            p_by.setdefault(t["wave"], []).append(t)
        lines += ["## Second program catalog — P1–P500 (specced 2026-09-05)", "",
                  "The second comprehensive program: **issue-driven, matrix-guided** across the "
                  "entire sitemap (156 real pages) + the edge-function layer, spanning all 13 "
                  "full-stack layers and the 102-dim UFAI rubric. Every row is generated as "
                  "*(a real surface on disk)* × *(a named probe lens)* by "
                  "`tools/seed_p_program_catalog.py`, which asserts each referenced page/function "
                  "exists — no phantom surfaces. All 500 enter at the honest `specced` (5%). The "
                  "deepwalk (Phase 2) FILLS the specifics; this catalog is the structure.", "",
                  "| Wave | Arcs | Range | Layers | Probe lenses |", "|---|---|---|---|---|"]
        for w in P_WAVE_ORDER:
            rows = sorted(p_by.get(w, []), key=lambda t: _idnum(t["id"]))
            if not rows:
                continue
            lenses = list(dict.fromkeys(t["title"].rsplit(" - ", 1)[0] for t in rows))
            layers = "/".join(rows[0].get("layers") or [])
            lines.append(f"| **{w}** · {P_WAVE_NAMES[w]} | {len(rows)} | {rows[0]['id']}–"
                         f"{rows[-1]['id']} | {layers} | " + " · ".join(lenses) + " |")
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    block = render()
    text = ROADMAP.read_text(encoding="utf-8")
    if START in text and END in text:
        pre, post = text[: text.index(START)], text[text.index(END) + len(END):]
        new = pre + block + post
    elif ANCHOR in text:
        new = text.replace(ANCHOR, block + "\n\n" + ANCHOR, 1)
    else:
        print("neither the markers nor the anchor found in the roadmap")
        return 1
    if "--check" in sys.argv:
        if new != text:
            print("EXPANSION CATALOG DRIFT — run: python tools/emit_expansion_catalog_md.py")
            return 1
        print("expansion catalog current.")
        return 0
    ROADMAP.write_text(new, encoding="utf-8")
    print("expansion catalog regenerated in UFAI_TRAJECTORY_ROADMAP.md")
    return 0


if __name__ == "__main__":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.exit(main())
