#!/usr/bin/env python3
"""
gen_camera_keys.py - turn the journey's ACTION LOG into a camera script.
========================================================================
Ian, on v5: "you still didn't get the motion, the zoom in zoom out, the
scrolling and clicking." Measured, he is right: inside the sample's product
beats the ink-centroid/bbox trace shows the view repeatedly TIGHTENS onto the
active region (bbox w drops 0.92 -> 0.79-0.83 with the centroid moving to the
action, e.g. cx 0.48 -> 0.73 at t=32.5) and relaxes back. The camera follows
the hand. Mine sat at a fixed inset.

The recorder already logs every click/type with a timestamp AND (since the
coordinate patch) the viewport-fraction position of the element acted on. So
the camera script is DERIVED from the recording itself: for each Remotion
segment, every action inside its window becomes a push-in keyframe centred on
that action, with pull-outs between. No staging, no hand-tuning per cut.

Writes remotion_scenes/src/demoCamera.ts (a generated module - do not edit).

Usage:
    python tools/gen_camera_keys.py .tmp/demo_journey/journey_<ts>.json \
        --segs "5.4:7,20.6:24,61.6:10,80.8:9,121.6:13,138.1:7"
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
ROOT = _HERE.parent

# Measured with OPTICAL FLOW (video_camera_motion.py), which overturned the
# first guess: the sample's camera is STATIC between moves (zoom rate 0.0000
# for seconds at a stretch) punctuated by SNAP zooms - ~0.2-0.3s bursts into a
# tight crop, a locked hold, then a snap back out. Slow eased drifts were MY
# invention and read as "weird". Crop depth from the bbox jump at t=32.5
# (cx 0.48->0.75, w->0.79 = a right-panel crop ~1.8x).
PUSH = 2.0
WIDE = 1.0
PUSH_IN_S = 0.18          # sample zoom bursts measure 0.1-0.2s
HOLD_S = 2.2
PULL_OUT_S = 0.25


def keys_for_segment(steps: list, seg_start: float, seg_dur: float) -> list:
    """Camera keyframes (t_in_segment, scale, fx, fy) for one segment window."""
    acts = [s for s in steps
            if s.get("ok") and "x" in s
            and seg_start - 0.2 <= s["at_s"] <= seg_start + seg_dur]
    keys = [(0.0, WIDE, 0.5, 0.5)]
    # NO synthetic snaps. v10 filled quiet stretches with rotating-focal
    # zooms to chase the sample's event COUNT and Ian felt it instantly:
    # "chaotic... not aligned what you are highlighting to... random and
    # erratic." A zoom is a pointing gesture - it exists only when there is a
    # logged, real target (a click, a typed field, the answer bubble).
    # Alignment beats count; the count follows from richer action logging.
    for a in acts:
        t = max(0.15, a["at_s"] - seg_start)
        # pull the focal 35% toward centre: an off-centre transform-origin
        # halves the zoom's full-frame optical-flow signature (and its felt
        # impact); the sample's crops stay near-central.
        fx = a["x"] + (0.5 - a["x"]) * 0.35
        fy = a["y"] + (0.5 - a["y"]) * 0.35
        # push in just BEFORE the click lands so the click is seen tight
        t_in = max(0.0, t - PUSH_IN_S)
        if keys and t_in <= keys[-1][0] + 0.25:
            # overlapping pushes merge: retarget instead of bouncing out
            keys.append((t, PUSH, fx, fy))
        else:
            keys.append((t_in, WIDE, keys[-1][2], keys[-1][3]))
            keys.append((t, PUSH, fx, fy))
        keys.append((min(seg_dur - 0.3, t + HOLD_S), PUSH, fx, fy))
        keys.append((min(seg_dur - 0.1, t + HOLD_S + PULL_OUT_S), WIDE, fx, fy))
    # always end wide so the outgoing fade reads calm
    if keys[-1][1] != WIDE:
        keys.append((seg_dur, WIDE, keys[-1][2], keys[-1][3]))
    # clamp monotonic time
    out, last_t = [], -1.0
    for t, s, fx, fy in keys:
        t = max(t, last_t + 0.05)
        out.append({"t": round(t, 2), "s": s, "fx": round(fx, 3), "fy": round(fy, 3)})
        last_t = t
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("sidecar")
    ap.add_argument("--segs", required=True,
                    help="comma list of start:dur for each Remotion segment")
    a = ap.parse_args()

    side = json.loads(Path(a.sidecar).read_text(encoding="utf-8"))
    steps = side["steps"]
    segs = []
    for part in a.segs.split(","):
        st, du = part.split(":")
        segs.append((float(st), float(du)))

    all_keys = [keys_for_segment(steps, st, du) for st, du in segs]
    ts = ("// GENERATED by tools/gen_camera_keys.py - do not edit.\n"
          "// Camera keyframes per journey segment, derived from the recorder's\n"
          "// own action log: the camera zooms toward each click as it happens.\n"
          "export type CamKey = {t: number; s: number; fx: number; fy: number};\n"
          f"export const CAMERA_KEYS: CamKey[][] = {json.dumps(all_keys)};\n")
    dest = ROOT / "remotion_scenes" / "src" / "demoCamera.ts"
    dest.write_text(ts, encoding="utf-8")
    n = sum(len(k) for k in all_keys)
    print(f"camera script -> {dest.name}: {len(all_keys)} segments, {n} keyframes")
    for i, k in enumerate(all_keys):
        pushes = sum(1 for x in k if x["s"] > 1.0)
        print(f"  seg{i}: {len(k)} keys, {pushes} pushed frames")
    return 0


if __name__ == "__main__":
    sys.exit(main())
