"""Generate Playwright smoke specs for every live HTML page.

Each spec follows the pattern in tests/_smoke-template.ts: load the page,
capture pageerrors + console.errors, assert basic DOM render. Pages that
already have richer specs (logbook, inventory, pm-scheduler, dayplanner,
assistant) get a smoke add-on only if not already present.

Pages with form-flow tests are flagged in HIGH_RISK so the human-written
spec stays authoritative; the generator just adds the smoke if missing.
"""
import os, glob, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

TESTS_DIR = "tests"

# Pages that already have hand-written specs — don't overwrite
EXISTING = {"logbook", "inventory", "pm-scheduler", "dayplanner", "assistant"}

# Pages that should expect a source chip (canonical-consuming dashboards)
EXPECTS_CHIP = {
    "analytics", "predictive", "asset-hub", "alert-hub",
    "hive", "index",
}

# Pages that are static reference / retired / print-only — relax to basics
STATIC_OR_RETIRED = {
    "architecture", "symbol-gallery", "platform-health", "public-feed",
    "analytics-report", "project-report", "parts-tracker",
}


def short_name(p): return os.path.splitext(os.path.basename(p))[0]

def title_for(name):
    return ' '.join(w.capitalize() for w in name.split('-'))


def gen_spec(page_name: str) -> str:
    expects_chip = page_name in EXPECTS_CHIP
    is_static    = page_name in STATIC_OR_RETIRED
    pretty = title_for(page_name)

    opts = []
    if expects_chip and not is_static:
        opts.append("expectSourceChip: true")
    if is_static:
        opts.append("minDomContent: false")

    opts_str = ", ".join(opts)
    opts_block = f"{{ {opts_str} }}" if opts_str else "{}"

    return f"""/**
 * {page_name}.html — UI smoke.
 * Auto-generated by tools/gen_smoke_specs.py. Add page-specific
 * form/flow tests in a separate describe block if needed.
 */
import {{ test, expect }} from './_fixtures';
import {{ smokePage }} from './_smoke-template';

test.describe('{page_name}.html smoke', () => {{
  test('loads and renders without page errors', async ({{ whPage }}) => {{
    await smokePage(whPage, '/{page_name}.html', {opts_block});
  }});
}});
"""


def main():
    # Enumerate live HTML pages (exclude backups + test variants)
    live = []
    for p in sorted(glob.glob("*.html")):
        n = short_name(p)
        if any(t in n for t in ("backup", "-test")): continue
        if n == "index-v3-test": continue
        if n in ("logbook", "inventory", "pm-scheduler", "dayplanner", "assistant"):
            # Already has a hand-written spec
            continue
        live.append(n)

    print(f"Generating smoke specs for {len(live)} pages...")
    written = skipped = 0
    for name in live:
        out_path = os.path.join(TESTS_DIR, f"{name}.spec.ts")
        if os.path.exists(out_path):
            skipped += 1; continue
        with open(out_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(gen_spec(name))
        written += 1
        print(f"  + {out_path}")
    print(f"\nWritten: {written}, skipped (exists): {skipped}")


if __name__ == "__main__":
    main()
