#!/usr/bin/env python3
"""
marketplace_deepwalk_scoreboard.py — the ANTI-DRIFT COMPASS for the Marketplace Deepwalk
Expansion arc (MARKETPLACE_DEEPWALK_EXPANSION_ROADMAP.md).

WHY THIS EXISTS (framework, not a one-off doc): a roadmap whose % is *vibed* drifts. This reads
`marketplace_deepwalk_state.json` and emits a MEASURED %-board over BOTH expansion denominators:

  BOARD 1 · JOURNEYS  — 20 journeys x 5 phases (G/W/O/H/R). done=1.0, partial=0.5, todo=0.
  BOARD 2 · CLASSES   — 10 MK dimension classes x 6 stages (harvest/define/detect/sweep/fix/gate).

"Done" is defined by BOTH boards (feedback_seed_resolved_is_not_roadmap_done) — a green headline on
one board never ends the arc.

FORWARD-ONLY RATCHET (the teeth): `--check` FAILS if either board's % falls below the accepted
baseline in `marketplace_deepwalk_baseline.json`. Progress may only rise; a regression (someone
downgrades a phase without doing the work, or a journey is dropped) breaks the build.
`--accept` ratchets the baseline UP to the current measurement (never down).

USAGE
  python tools/marketplace_deepwalk_scoreboard.py            # print the board + write the .md
  python tools/marketplace_deepwalk_scoreboard.py --check    # gate mode (forward-only ratchet)
  python tools/marketplace_deepwalk_scoreboard.py --accept   # ratchet the baseline up
  python tools/marketplace_deepwalk_scoreboard.py --selftest # verify the maths
"""
from __future__ import annotations
import json, sys
from pathlib import Path

ROOT     = Path(__file__).resolve().parent.parent
STATE    = ROOT / "marketplace_deepwalk_state.json"
BASELINE = ROOT / "marketplace_deepwalk_baseline.json"
OUT_MD   = ROOT / "MARKETPLACE_DEEPWALK_SCOREBOARD.md"

PHASES = ["G", "W", "O", "H", "R"]
STAGES = ["harvest", "define", "detect", "sweep", "fix", "gate"]
VALUE  = {"done": 1.0, "partial": 0.5, "todo": 0.0}

GREEN, YELLOW, RED, BOLD, RESET = "\033[92m", "\033[93m", "\033[91m", "\033[1m", "\033[0m"


def _pct(earned: float, total: float) -> float:
    return round(100.0 * earned / total, 1) if total else 0.0


def measure(state: dict) -> dict:
    """Compute both boards. Pure function of the state -> unit-testable."""
    journeys = state.get("journeys", {})
    classes  = state.get("dim_classes", {})

    # BOARD 1 — journeys, rolled up per TYPE and per PHASE
    per_type: dict[str, list[float]] = {}
    per_phase: dict[str, list[float]] = {p: [] for p in PHASES}
    j_earned = j_total = 0.0
    j_rows = []
    for jid, j in sorted(journeys.items()):
        ph = j.get("phases", {})
        vals = [VALUE.get(ph.get(p, "todo"), 0.0) for p in PHASES]
        earned, total = sum(vals), float(len(PHASES))
        j_earned += earned
        j_total  += total
        per_type.setdefault(j.get("type", "?"), []).append(_pct(earned, total))
        for p, v in zip(PHASES, vals):
            per_phase[p].append(v)
        # coverage rule: W is only legitimately 'done' with >=2 personas AND >=2 states
        w = j.get("walked", {}) or {}
        shallow = (ph.get("W") == "done"
                   and (len(w.get("personas", [])) < 2 or len(w.get("states", [])) < 2))
        j_rows.append({"id": jid, "type": j.get("type", "?"), "pct": _pct(earned, total),
                       "phases": {p: ph.get(p, "todo") for p in PHASES},
                       "personas": len(w.get("personas", [])), "states": len(w.get("states", [])),
                       "shallow_W": shallow})

    # BOARD 2 — MK classes
    c_earned = c_total = 0.0
    c_rows = []
    for cid, c in sorted(classes.items()):
        st = c.get("stages", {})
        vals = [VALUE.get(st.get(s, "todo"), 0.0) for s in STAGES]
        earned, total = sum(vals), float(len(STAGES))
        c_earned += earned
        c_total  += total
        c_rows.append({"id": cid, "pct": _pct(earned, total),
                       "stages": {s: st.get(s, "todo") for s in STAGES}})

    return {
        "journey_pct": _pct(j_earned, j_total),
        "class_pct":   _pct(c_earned, c_total),
        "overall_pct": _pct(j_earned + c_earned, j_total + c_total),
        "per_type":    {t: round(sum(v) / len(v), 1) for t, v in sorted(per_type.items())},
        "per_phase":   {p: _pct(sum(v), float(len(v))) for p, v in per_phase.items()},
        "journeys":    j_rows,
        "classes":     c_rows,
        "counts":      {"journeys": len(journeys), "classes": len(classes)},
        "shallow_W":   [r["id"] for r in j_rows if r["shallow_W"]],
    }


def _mark(v: str) -> str:
    return {"done": "✅", "partial": "🟡", "todo": "⬜"}.get(v, "⬜")


def write_md(m: dict) -> None:
    L = ["# Marketplace Deepwalk — MEASURED Scoreboard",
         "",
         "> Auto-generated by `tools/marketplace_deepwalk_scoreboard.py` from",
         "> `marketplace_deepwalk_state.json`. Do not hand-edit — edit the STATE, re-run the tool.",
         "> Companion roadmap: `MARKETPLACE_DEEPWALK_EXPANSION_ROADMAP.md`.",
         "",
         f"**OVERALL {m['overall_pct']}%** · journeys **{m['journey_pct']}%** "
         f"({m['counts']['journeys']}) · MK classes **{m['class_pct']}%** ({m['counts']['classes']})",
         "",
         "## Board 1 — Journeys (G/W/O/H/R)", "",
         "| Journey | Type | G | W | O | H | R | personas×states | % |",
         "|---|---|:-:|:-:|:-:|:-:|:-:|:-:|--:|"]
    for r in m["journeys"]:
        ph = " | ".join(_mark(r["phases"][p]) for p in PHASES)
        flag = " ⚠shallow" if r["shallow_W"] else ""
        L.append(f"| {r['id']} | {r['type']} | {ph} | {r['personas']}×{r['states']}{flag} | {r['pct']}% |")
    L += ["", "**Per phase:** " + " · ".join(f"{p} {m['per_phase'][p]}%" for p in PHASES),
          "", "**Per type:** " + " · ".join(f"{t} {v}%" for t, v in m["per_type"].items()),
          "", "## Board 2 — New MK dimension classes", "",
          "| Class | " + " | ".join(s for s in STAGES) + " | % |",
          "|---|" + ":-:|" * len(STAGES) + "--:|"]
    for r in m["classes"]:
        L.append(f"| {r['id']} | " + " | ".join(_mark(r["stages"][s]) for s in STAGES) + f" | {r['pct']}% |")
    if m["shallow_W"]:
        L += ["", "> ⚠ **Shallow W flagged** (marked done but <2 personas or <2 states): "
                  + ", ".join(m["shallow_W"])]
    L += ["", "_Anti-drift: at ANY 'what next / is this done?' doubt → read this board + the roadmap §7 NEXT._", ""]
    OUT_MD.write_text("\n".join(L), encoding="utf-8")


def selftest() -> int:
    """Verify the maths on a synthetic state — the newest instrument is the least trustworthy."""
    fake = {
        "journeys": {
            "Ja": {"type": "T8", "phases": {"G": "done", "W": "done", "O": "done", "H": "done", "R": "done"},
                   "walked": {"personas": ["a", "b"], "states": ["x", "y"]}},          # 100%, not shallow
            "Jb": {"type": "T8", "phases": {"G": "partial", "W": "todo", "O": "todo", "H": "todo", "R": "todo"},
                   "walked": {}},                                                       # 10%
            "Jc": {"type": "T1", "phases": {"G": "done", "W": "done", "O": "todo", "H": "todo", "R": "todo"},
                   "walked": {"personas": ["a"], "states": ["x"]}},                     # 40%, SHALLOW W
        },
        "dim_classes": {
            "MKa": {"stages": {"harvest": "done", "define": "done", "detect": "done",
                               "sweep": "done", "fix": "done", "gate": "done"}},        # 100%
            "MKb": {"stages": {"harvest": "partial"}},                                  # 0.5/6 = 8.3%
        },
    }
    m = measure(fake)
    ok = True

    def chk(label, got, want):
        nonlocal ok
        good = got == want
        ok &= good
        print(f"  {GREEN + 'PASS' + RESET if good else RED + 'FAIL' + RESET}  {label}: got {got}, want {want}")

    # journeys: (5 + 0.5 + 2) / 15 = 7.5/15 = 50.0
    chk("journey_pct", m["journey_pct"], 50.0)
    # classes: (6 + 0.5) / 12 = 6.5/12 = 54.2
    chk("class_pct", m["class_pct"], 54.2)
    # overall: 14/27 = 51.9
    chk("overall_pct", m["overall_pct"], 51.9)
    chk("shallow_W detected", m["shallow_W"], ["Jc"])
    chk("per_type T8", m["per_type"]["T8"], 55.0)     # (100 + 10)/2
    chk("per_phase G", m["per_phase"]["G"], 83.3)     # (1 + 0.5 + 1)/3
    print(f"\n  SELFTEST: {GREEN + 'PASS' + RESET if ok else RED + 'FAIL' + RESET}")
    return 0 if ok else 1


def main() -> int:
    if "--selftest" in sys.argv:
        return selftest()
    if not STATE.exists():
        print(f"{RED}FAIL{RESET}  missing {STATE.name}")
        return 1
    state = json.loads(STATE.read_text(encoding="utf-8"))
    m = measure(state)
    write_md(m)

    base = json.loads(BASELINE.read_text(encoding="utf-8")) if BASELINE.exists() else {}
    b_j, b_c = base.get("journey_pct", 0.0), base.get("class_pct", 0.0)

    print(f"{BOLD}Marketplace Deepwalk — anti-drift %-board{RESET}")
    print(f"  journeys : {m['journey_pct']}%  ({m['counts']['journeys']} journeys x {len(PHASES)} phases)   baseline {b_j}%")
    print(f"  classes  : {m['class_pct']}%  ({m['counts']['classes']} MK classes x {len(STAGES)} stages)   baseline {b_c}%")
    print(f"  OVERALL  : {m['overall_pct']}%")
    print("  per phase: " + " · ".join(f"{p} {m['per_phase'][p]}%" for p in PHASES))
    if m["shallow_W"]:
        print(f"  {YELLOW}shallow W{RESET} (<2 personas or <2 states): {', '.join(m['shallow_W'])}")
    print(f"  -> {OUT_MD.name}")

    if "--accept" in sys.argv:
        BASELINE.write_text(json.dumps(
            {"journey_pct": m["journey_pct"], "class_pct": m["class_pct"],
             "overall_pct": m["overall_pct"],
             "_doc": "Forward-only ratchet baseline for the marketplace deepwalk expansion arc. "
                     "Raised by --accept; a FALL below these numbers FAILs the gate."},
            indent=2), encoding="utf-8")
        print(f"  {GREEN}ACCEPTED{RESET}  baseline -> journeys {m['journey_pct']}% / classes {m['class_pct']}%")
        return 0

    if "--check" in sys.argv:
        drops = []
        if m["journey_pct"] < b_j: drops.append(f"journeys {m['journey_pct']}% < baseline {b_j}%")
        if m["class_pct"]  < b_c: drops.append(f"classes {m['class_pct']}% < baseline {b_c}%")
        if drops:
            print(f"  {RED}FAIL{RESET}  forward-only ratchet regressed: " + "; ".join(drops))
            return 1
        print(f"  {GREEN}PASS{RESET}  forward-only ratchet holds "
              f"(journeys >= {b_j}%, classes >= {b_c}%)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
