// GENERATED by `node tools/phone_fit_audit.mjs --emit-browser` from audit() in tools/phone_fit_audit.mjs (sha 61dd99d8235f). Do not edit.
(function () { window.__W4_AUDIT = function audit(VIS_JS, opts) {
  opts = opts || {};
  const vis = VIS_JS ? (0, eval)(VIS_JS) : ((e) => !!e && (typeof e.checkVisibility === 'function' ? e.checkVisibility({ visibilityProperty: true }) : e.offsetParent !== null));
  const vw = innerWidth, vh = innerHeight;
  const out = { step: opts.step || null, width: vw, lang: (document.documentElement.lang || '').slice(0, 3) || null,
    overflow: document.documentElement.scrollWidth - vw, outside: [], clipped: [], wrapped: [], spill: [], overflowEl: [], occlusion: [] };
  const poster = ((document.querySelector('meta[name="artifact-genre"]') || {}).content || '') === 'poster';
  if (poster) { out.poster = true; return out; }
  const name = (e) => (e.id ? '#' + e.id : e.tagName.toLowerCase() + (typeof e.className === 'string' && e.className ? '.' + e.className.trim().split(/\s+/)[0] : ''));
  const rectOf = (r) => `${Math.round(r.left)},${Math.round(r.top)} ${Math.round(r.width)}x${Math.round(r.height)}`;
  const ownText = (e) => [...e.childNodes].filter((n) => n.nodeType === 3).map((n) => n.textContent).join('').replace(/\s+/g, ' ').trim();
  const clipper = (e) => { let a = e.parentElement; while (a && a !== document.body) { const o = getComputedStyle(a); if (/hidden|clip|auto|scroll/.test(o.overflowX + ' ' + o.overflow)) return a; a = a.parentElement; } return null; };
  // the control's VISIBLE rect: its box intersected with every overflow-clipping ancestor's box and the viewport.
  // A control scrolled partway out of its scroll-parent (the last row of a scrolling list, a card below a panel's
  // fold) has a full rect whose geometric centre lands in the CLIPPED band - where elementFromPoint returns the
  // scroll-parent's chrome, not the control - so probing the raw centre false-flags "covered". Probe the centre of
  // what is actually painted instead; a fully-visible control's visible rect equals its full rect, so a real
  // FAB/pill-over-button is still caught. An empty intersection = scrolled off / off-screen = the walk's scroll job.
  const visibleRect = (e, r0) => { let L = r0.left, T = r0.top, R = r0.right, B = r0.bottom, a = e.parentElement; while (a && a !== document.body) { const o = getComputedStyle(a); if (/hidden|clip|auto|scroll/.test(o.overflowX + ' ' + o.overflowY + ' ' + o.overflow)) { const q = a.getBoundingClientRect(); L = Math.max(L, q.left); T = Math.max(T, q.top); R = Math.min(R, q.right); B = Math.min(B, q.bottom); } a = a.parentElement; } L = Math.max(L, 0); T = Math.max(T, 0); R = Math.min(R, vw); B = Math.min(B, vh); return { left: L, top: T, right: R, bottom: B, width: R - L, height: B - T }; };
  const decorative = (e) => getComputedStyle(e).pointerEvents === 'none' && !e.textContent.trim();
  const srOnly = (e, cs) => e.clientWidth <= 1 || e.clientHeight <= 1 || (cs.clip && cs.clip !== 'auto') || (cs.clipPath && cs.clipPath !== 'none');
  const all = [...document.querySelectorAll('body *')].filter((e) => vis(e) && !e.closest('script,style,svg,[aria-hidden="true"]'));

  // ── OCCLUSION: every visible interactive control must be reachable at its own centre ─────────────────────
  // A control inside an OPEN overlay (dialog, menu, sheet, hub panel, companion panel) is judged against that
  // overlay's own contents; a control UNDER an open overlay is expected to be covered (the overlay is modal) and
  // is not a finding - the finding is a control the person is meant to use right now that something else sits on.
  const OVERLAY = '[aria-modal="true"], [role="dialog"], [role="menu"], [role="listbox"], .modal, .sheet.open, [class*="sheet"][class*="open"], #wh-hub-panel, #wh-ai-panel, #wh-feedback-panel';
  const openOverlays = [...document.querySelectorAll(OVERLAY)].filter((e) => vis(e) && e.getBoundingClientRect().height > 0);
  const inOpenOverlay = (e) => openOverlays.some((o) => o.contains(e));
  const controls = all.filter((e) => e.matches('a[href], button, [role="button"], [role="tab"], [role="menuitem"], input:not([type="hidden"]), select, textarea, summary, [tabindex]:not([tabindex="-1"])'));
  for (const c of controls) {
    if (c.closest('[inert], [disabled]') || c.disabled) continue;
    const r = c.getBoundingClientRect(); if (r.width < 4 || r.height < 4) continue;
    const cs = getComputedStyle(c); if (srOnly(c, cs)) continue;
    // probe the centre of what is actually PAINTED (the box clipped to its scroll-parents + viewport); a control
    // scrolled partway out of a list is the walk's scroll-to job, not an occlusion, and its empty/tiny visible
    // rect skips here rather than false-flagging the scroll-parent's chrome as a coverer
    const vr = visibleRect(c, r); if (vr.width < 4 || vr.height < 4) continue;
    const x = Math.min(vw - 1, Math.max(0, vr.left + vr.width / 2)), y = Math.min(vh - 1, Math.max(0, vr.top + vr.height / 2));
    if (openOverlays.length && !inOpenOverlay(c)) continue;          // under a modal overlay: covered by design
    const hit = document.elementFromPoint(x, y);
    if (!hit || hit === c || c.contains(hit) || hit.contains(c)) continue;
    // a label wrapping its input, or an input's own visual twin, is the same control
    if (hit.closest('label') && hit.closest('label').control === c) continue;
    const hcs = getComputedStyle(hit);
    let cover = hit.closest('[class*="fab"], [id*="fab"], header, [role="banner"], .sticky, [class*="sticky"], [class*="toast"], [role="alert"], [role="status"], [class*="consent"], [class*="cookie"], #wh-hub-panel, #wh-ai-panel, #wh-feedback-panel, [id^="wh-"], [class^="wh-"]') || hit;
    // A COVER THAT CONTAINS THE COVERED THING IS A WRAPPER, NOT A COVER (2026-09-16). The climb above ends on
    // `[id^="wh-"]`, and wayfinding.js gives every page's own <main> the id wh-main-content - so a genuine
    // overlap inside <main> was being reported as "covered by #wh-main-content (static, z auto) @0,0 1274x2558",
    // which names the page wrapper and tells a reader nothing about what is actually on top. pm-scheduler's
    // "Do the recommended next action" button read exactly that. When the resolved cover is an ancestor of the
    // target, fall back to the element elementFromPoint actually returned, which is the thing to go and look at.
    if (cover.contains(c)) cover = hit;
    out.occlusion.push(`${name(c)} "${(c.getAttribute('aria-label') || ownText(c) || c.value || '').slice(0, 24)}" @${rectOf(r)} covered by ${name(cover)} (${hcs.position}, z ${hcs.zIndex}) @${rectOf(cover.getBoundingClientRect())}`);
  }

  for (const e of all) {
    const r = e.getBoundingClientRect(); if (r.width === 0 || r.height === 0) continue;
    const cs = getComputedStyle(e);
    if (srOnly(e, cs)) continue;
    // (1) PARTIALLY outside the viewport (a closed sheet parked fully off-screen is by design; a menu cut at the edge is not)
    const partial = (r.left < vw - 1 && r.right > vw + 2) || (r.left < -2 && r.right > 1);
    if (partial && !decorative(e)) { const c = clipper(e); const scroller = c && /auto|scroll/.test(getComputedStyle(c).overflowX + getComputedStyle(c).overflow); if (!scroller && !(c && c !== document.body && !/menu|dialog|popover|dropdown/.test(e.className + ' ' + e.getAttribute('role')))) out.outside.push(name(e) + ' ' + Math.round(r.left) + '..' + Math.round(r.right) + (c ? ' (cut by ' + name(c) + ')' : '')); }
    const t = ownText(e);
    // (2) text CLIPPED by its own box (overflow hidden + wider content, no ellipsis)
    if (t && /hidden|clip/.test(cs.overflowX + cs.overflow) && e.scrollWidth > e.clientWidth + 2 && cs.textOverflow !== 'ellipsis') out.clipped.push(name(e) + ' ' + e.scrollWidth + '>' + e.clientWidth + ' "' + t.slice(0, 30) + '"');
    // (2b) ELEMENT OVERFLOW INSIDE ITS CONTAINER - any box (not only text) wider than its clipping parent under
    // overflow:hidden/clip: a card spilling under a hidden edge, an image or table wider than its card
    const cp = clipper(e);
    if (cp && cp !== document.body && /hidden|clip/.test(getComputedStyle(cp).overflowX + getComputedStyle(cp).overflow) && cs.position !== 'absolute' && cs.position !== 'fixed') {
      const pr = cp.getBoundingClientRect();
      if (r.right > pr.right + 3 || r.left < pr.left - 3) out.overflowEl.push(name(e) + ' @' + rectOf(r) + ' past ' + name(cp) + ' @' + rectOf(pr));
    }
    // (3) a CONTROL LABEL wrapped inside its own control
    const isControl = e.matches('button, [role="button"], [role="tab"], .pill, .badge, .chip, .tag, .kpi-label, .sc-label, .simple-label, .stat-label, th, .btn, a.btn, [class*="btn-"], [class*="pill"], [class*="chip"], [class*="badge"]');
    if (isControl && !e.matches('.wh-source-chip') && !e.closest('.wh-source-chip') && !e.querySelector('br') && cs.whiteSpace !== 'pre-line') {
      const shortLabel = e.textContent.trim().split(/\s+/).length <= 4;
      const carriers = [e, ...(shortLabel ? [...e.querySelectorAll('*')].filter((c) => vis(c) && ownText(c).length > 3 && !c.matches('svg, svg *')) : [])];
      const linesOf = (el) => { const rg = document.createRange(); rg.selectNodeContents(el); const rects = [...rg.getClientRects()].filter((q) => q.width > 0 && q.height > 0).sort((x, y) => x.top - y.top); let lines = 0, bottom = -1e9; for (const q of rects) { if (q.top >= bottom - 2) { lines++; bottom = q.bottom; } else bottom = Math.max(bottom, q.bottom); } return lines; };
      for (const el of carriers) {
        const t2 = el === e ? t : ownText(el); if (t2.length <= 3) continue;
        if (el !== e && [...el.children].some((c) => getComputedStyle(c).display === 'block' && c.textContent.trim())) continue;
        if (el === e && e.children.length && [...e.children].some((c) => getComputedStyle(c).display === 'block' && c.textContent.trim())) continue;
        const lines = linesOf(el); const rr = el.getBoundingClientRect();
        const words = t2.split(/\s+/).length; const isTh = e.tagName === 'TH';
        const isLabel = e.matches('.kpi-label, .sc-label, .simple-label, .stat-label, p, div:not([role])') && !e.matches('button, [role="button"], [role="tab"], .btn, a.btn, [class*="btn-"]');
        const isPillish = e.matches('.pill, .badge, .chip, .tag, [class*="pill"], [class*="chip"], [class*="badge"]') && !e.matches('button, [role="button"], [role="tab"]');
        const squeeze = (isTh || isLabel) ? lines >= 3 : isPillish ? (lines >= 2 && words <= 4) : (lines >= 2 && (r.width < 240 || words <= 3));
        if (squeeze) { out.wrapped.push(name(e) + (el === e ? '' : ' > ' + name(el)) + ' ' + lines + ' lines @' + Math.round(rr.width) + 'px "' + t2.slice(0, 34) + '"'); break; }
      }
    }
    // (4) text SPILLING past its parent's box (an unbroken id / email / url / number wider than the card)
    if (t.length > 6 && cs.position !== 'absolute' && cs.position !== 'fixed') { const pr = e.parentElement.getBoundingClientRect(); const po = getComputedStyle(e.parentElement); const negM = Math.max(0, -parseFloat(cs.marginRight) || 0);
      if (r.right > pr.right + 3 + negM && pr.width > 0 && !/auto|scroll/.test(po.overflowX + po.overflow)) out.spill.push(name(e) + ' right ' + Math.round(r.right) + ' > parent ' + Math.round(pr.right) + ' "' + t.slice(0, 30) + '"'); }
  }
  // ── CONFUSION DETECTORS (Ian, 2026-09-14: "any other kinds and types" of confusion, not sign-in alone) ────
  // The walks meet confusion the same way a person does. Two kinds a record can measure on every step:
  //   ambiguity    - two or more VISIBLE controls of the same role announce the same name inside one landmark
  //                  (the sign-in wall's two "Sign In"s: a screen reader hears one name twice, a walker's role
  //                  locator resolves both, a person picks the wrong one). Repeats inside separate list items,
  //                  table rows or cards are the ordinary shape of a list and are not counted.
  //   unactionable - a VISIBLE alert / status / error region carrying the transport's own words ("name
  //                  resolution failed", "failed to fetch", "ECONN", "undefined", "[object Object]", a bare
  //                  HTTP code) - a sentence a person cannot act on.
  // Both are RECORDED, never auto-filed: the walk reads them and appends the real ones to w4_confusions.json.
  {
    const groups = {};
    for (const c of controls) {
      if (c.closest('li, tr, [class*="card"], [class*="tile"], [class*="row"], [role="listitem"], [role="row"], [role="option"]')) continue;
      const r = c.getBoundingClientRect(); if (r.width < 4 || r.height < 4) continue;
      const cs = getComputedStyle(c); if (srOnly(c, cs)) continue;
      if (openOverlays.length && !inOpenOverlay(c)) continue;          // under a modal: not announced, not confusable
      const role = c.getAttribute('role') || c.tagName.toLowerCase() + (c.type ? ':' + c.type : '');
      const nm = (c.getAttribute('aria-label') || (c.labels && c.labels[0] && c.labels[0].textContent) || c.textContent || c.value || c.getAttribute('title') || '').replace(/\s+/g, ' ').trim().toLowerCase();
      if (!nm || nm.length > 40) continue;
      const land = c.closest('main, nav, header, footer, aside, [role="dialog"], [role="region"], form') || document.body;
      const key = (land.id || land.tagName.toLowerCase()) + '|' + role + '|' + nm;
      (groups[key] = groups[key] || []).push(name(c));
    }
    out.ambiguity = Object.entries(groups).filter(([, v]) => v.length > 1).map(([k, v]) => `${k.split('|')[2]} (${k.split('|')[1]}) x${v.length} in ${k.split('|')[0]}: ${v.slice(0, 3).join(', ')}`).slice(0, 8);
    const RAW = /name resolution|failed to fetch|networkerror|econn|etimedout|socket hang up|\bundefined\b|\bnull\b|\[object object\]|\bnan\b|^\s*(?:error|err)[:\s]|status(?:code)?\s*[45]\d\d|\b5\d\d\b(?!\s*(?:px|ms|%))|internal server error|bad gateway|service (?:temporarily )?unavailable|exception|stack ?trace|traceback|typeerror|referenceerror/i;
    out.unactionable = [...document.querySelectorAll('[role="alert"], [role="status"], [aria-live], [class*="error"], [id*="error"], [class*="toast"], [class*="alert"]')]
      .filter((e) => vis(e) && e.getBoundingClientRect().height > 0 && !e.closest('script,style'))
      .map((e) => (e.innerText || e.textContent || '').replace(/\s+/g, ' ').trim())
      .filter((t) => t && t.length < 400 && RAW.test(t))
      .map((t) => t.slice(0, 120)).slice(0, 4);
  }
  for (const k of ['outside', 'clipped', 'wrapped', 'spill', 'overflowEl', 'occlusion']) out[k] = [...new Set(out[k])].slice(0, 12);
  out.findings = (out.overflow > 2 ? 1 : 0) + out.outside.length + out.clipped.length + out.wrapped.length + out.spill.length + out.overflowEl.length + out.occlusion.length;
  out.confusions = (out.ambiguity || []).length + (out.unactionable || []).length;
  return out;
}; window.__W4_AUDIT_SHA = "61dd99d8235f"; })();
