#!/usr/bin/env python3
"""prove_w4_layer_av.py - the W4 layer-AV stories, proven at source (no browser).

The wave-4 AV-layer story is "The platform must keep this page truthful when the model or the pipeline behind it is
wrong." It applies only to a page that presents MODEL / AI / PREDICTION output - an answer, a forecast, a
recommendation, an AI-quality read - because only there can a wrong pipeline mislead a reader who cannot see the
error. Such a page owes an honesty marker: it grounds the output (a source chip, "based on your ..."), qualifies it
(confidence / estimated / may vary / a range), or degrades honestly when the model fails - never a bare assertion of
a machine guess. A page with no model behind it (a form, a static doc, a deterministic calculator, a plain list) has
no pipeline that could be wrong.
  - static document (tools/page_kind) or a page with no model/AI/prediction output -> n/a (no pipeline to be wrong)
  - it presents model output AND marks its honesty (grounding / confidence / caveat / honest fallback) -> ok
  - it presents model output as bare fact with no honesty marker -> BAD (a wrong model reads as truth)
Source-level and axis-independent (the markers are the same bytes on every axis), so the three axis-rows of a page
share one witness; writes a `witness` receipt per row.

  python tools/prove_w4_layer_av.py            # every AV-layer row, print + write receipts
  python tools/prove_w4_layer_av.py --check    # the gate: exit 1 if any AV row's page presents a model guess as bare fact
"""
from __future__ import annotations

import datetime as _dt
import io
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from page_kind import is_static_doc  # noqa: E402
from prove_w4_layer_headers import _first_root_page  # noqa: E402

REGISTRY = ROOT / "trajectory_registry.json"
OUT_DIR = ROOT / ".tmp" / "mcp_walks"
GREEN, RED, RST = "\033[92m", "\033[91m", "\033[0m"
COMMENT = re.compile(r"<!--.*?-->", re.S)
# the page presents MODEL / AI / PREDICTION output (not a deterministic calc, not a plain list)
MODEL = re.compile(r"functions\.invoke\(\s*['\"][a-z0-9-]*(ai|assist|companion|agent|intent|narrativ|reply|brief)|"
                   r"ai_cost_log|ai_reply_feedback|agentic_rag|\bai_chain|floating-ai|renderAnswer|aiReply|"
                   r"AI-generated|AI-drafted|generated by (the )?AI|predicted|prediction|forecast|"
                   r"recommend(ed|ation)|risk score|anomaly|model (says|output|confidence)", re.I)
# honesty about a machine guess: grounding, a qualifier, a caveat, or an honest failure
HONESTY = re.compile(r"wh-source-chip|based on your|grounded|renderSourceChip|_whFriendlySource|citation|"
                     r"confidence|estimated|\bmay vary\b|approximate|assumption|indicative|projected|"
                     r"\brange\b|not a substitute|verify|review before|double-?check|caveat|"
                     r"could ?n['o]?t|unavailable|try again|low confidence|±|~", re.I)


def av_rows() -> list[dict]:
    reg = json.loads(REGISTRY.read_text(encoding="utf-8"))
    return [t for t in reg["trajectories"]
            if (t.get("w4") or {}).get("kind") == "layer" and (t.get("w4") or {}).get("layer") == "AV"
            and t.get("status") != "descoped"]


def check_page(page: str) -> tuple[str, str]:
    if is_static_doc(page):
        return "n/a", f"{page} ships no data client - it presents no model output that could be wrong"
    try:
        own = (ROOT / page).read_text(encoding="utf-8", errors="replace")
    except OSError:
        return "n/a", f"{page} could not be read from disk"
    if 'id="wh-retired-overlay"' in own:
        return "n/a", f"{page} is retired behind the overlay - its content is not shown to anyone"
    body = COMMENT.sub(" ", own)
    if not MODEL.search(body):
        return "n/a", f"{page} presents no model / AI / prediction output (a form, a deterministic calc, or a plain list) - no pipeline that could be wrong"
    if HONESTY.search(body):
        return "ok", f"{page} marks the honesty of its model output (grounding / confidence / caveat / honest fallback) - a wrong pipeline does not read as truth"
    return "BAD", f"{page} presents model / AI / prediction output as bare fact with no grounding, confidence or caveat - a wrong model reads as truth"


def write_receipt(row: dict, verdict: str, witness: str) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    ax = row.get("axis") or {}
    ok = verdict in ("ok", "n/a")
    doc = {
        "_doc": "A W4 AV-layer story proven at source (no browser) - tools/prove_w4_layer_av.py.",
        "generated": _dt.datetime.now().isoformat(timespec="seconds"),
        "instrument": "playwright",
        "results": [{
            "id": row["id"], "ok": ok, "unbuilt": False, "instrument": "playwright",
            "condition": "the model or pipeline is wrong", "cast": "the page's model-output honesty markers (source-level)",
            "problems": [] if ok else [witness], "note": witness,
            "metrics": {"arrived": 1, "steps": len(row.get("pages") or []), "idKept": True},
            "w4": {"axis": f"{ax.get('device')} {ax.get('language')}", "layer": "AV", "witness": witness},
            "steps": [{"page": p, "chars": 1000, "identityKept": True} for p in (row.get("pages") or [])],
        }],
    }
    tmp = OUT_DIR / f"{row['id']}.json.tmp"
    tmp.write_text(json.dumps(doc, indent=1, ensure_ascii=False), encoding="utf-8")
    (OUT_DIR / f"{row['id']}.json").unlink(missing_ok=True)
    tmp.replace(OUT_DIR / f"{row['id']}.json")


def main() -> int:
    rows = av_rows()
    if not rows:
        print("PASS w4-layer-model-honesty - no W4 layer-AV row (nothing to prove)")
        return 0
    check_only = "--check" in sys.argv
    page_cache: dict[str, tuple[str, str]] = {}
    bad = 0
    for row in rows:
        page = _first_root_page(row)
        if not page:
            continue
        if page not in page_cache:
            page_cache[page] = check_page(page)
        verdict, witness = page_cache[page]
        if verdict == "BAD":
            bad += 1
        if not check_only:
            write_receipt(row, verdict, witness)
    n, uniq = len(rows), len(page_cache)
    na = sum(1 for v, _w in page_cache.values() if v == "n/a")
    okp = sum(1 for v, _w in page_cache.values() if v == "ok")
    print(f"{(GREEN + 'PASS') if not bad else (RED + 'FAIL')}{RST} w4-layer-model-honesty - "
          f"{n - bad}/{n} AV-layer row(s) hold ({uniq} pages: {okp} mark model honesty, {na} n/a - no pipeline to be wrong)"
          + (f"; {sum(1 for v, _w in page_cache.values() if v == 'BAD')} page(s) present a model guess as bare fact" if bad else ""))
    for page, (v, w) in sorted(page_cache.items()):
        if v in ("ok", "BAD") and (v == "BAD" or "--verbose" in sys.argv):
            tag = f"{GREEN}ok {RST}" if v == "ok" else f"{RED}BAD{RST}"
            print(f"  {tag} {page:<40} {w[:100]}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.exit(main())
