#!/usr/bin/env python3
"""quota_board.py — FREE_TIER_QUOTA_ROADMAP Q5 unified quota board.

Q5 DoD: "unify all limits into one measured quota coverage board (the way Arc R unified
security), with a gate that FAILs if a new high-write table ships without a cap." This
aggregates the three per-dimension ratchet gates + the AI daily-ceiling presence into ONE
measured board, writes FREE_TIER_QUOTA_BOARD.md, and exits non-zero if any dimension is red.

Dimensions:
  - per-day row caps      (validate_quota_coverage.py)         every high-write table
  - text-field caps       (validate_text_cap_coverage.py, text rows)
  - upload caps           (validate_text_cap_coverage.py, upload rows)
  - logbook pilot         (validate_logbook_quota.py)
  - AI rate limits         hourly (checkAIRateLimit) + daily (Q4 day_count columns)

USAGE:  python tools/quota_board.py            # print board + write artifact
        python tools/quota_board.py --check    # gate mode: exit 1 if any dimension red
"""
from __future__ import annotations
import re
import subprocess
import sys
from pathlib import Path

if sys.platform == "win32" and sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    import io
    sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent
TOOLS = ROOT / "tools"
GREEN, RED, YEL = "\033[92m", "\033[91m", "\033[93m"
RST = "\033[0m"


def run_gate(script: str) -> tuple[int, str]:
    try:
        r = subprocess.run([sys.executable, str(TOOLS / script)],
                           capture_output=True, text=True, timeout=120)
        return r.returncode, (r.stdout or "") + (r.stderr or "")
    except Exception as e:
        return 99, str(e)


def coverage(out: str) -> str:
    m = re.search(r"coverage:\s*([0-9]+/[0-9]+)", out)
    if m:
        return m.group(1)
    m = re.search(r"all\s+(\d+)\s+Q0 checks", out)
    return f"{m.group(1)}/{m.group(1)}" if m else "?"


def text_upload_split(out: str) -> tuple[int, int, int, int]:
    text_ok = len(re.findall(r"ok.{0,4}\s+text:", out))
    text_all = len(re.findall(r"\s+text:", out))
    up_ok = len(re.findall(r"ok.{0,4}\s+upload:", out))
    up_all = len(re.findall(r"\s+upload:", out))
    return text_ok, text_all, up_ok, up_all


def ai_daily_present() -> bool:
    """AI daily ceiling = day_count columns in a migration AND limitPerDay in the gate fn."""
    migs = "\n".join(p.read_text(encoding="utf-8", errors="replace")
                     for p in (ROOT / "supabase" / "migrations").glob("*.sql"))
    rl = (ROOT / "supabase" / "functions" / "_shared" / "rate-limit.ts")
    rl_txt = rl.read_text(encoding="utf-8", errors="replace") if rl.exists() else ""
    return ("day_count" in migs and "day_window_start" in migs
            and "limitPerDay" in rl_txt and "DEFAULT_RATE_LIMIT_PER_DAY" in rl_txt)


def main() -> int:
    check = "--check" in sys.argv[1:]

    cov_rc, cov_out = run_gate("validate_quota_coverage.py")
    txt_rc, txt_out = run_gate("validate_text_cap_coverage.py")
    lb_rc,  lb_out  = run_gate("validate_logbook_quota.py")
    t_ok, t_all, u_ok, u_all = text_upload_split(txt_out)
    ai_daily = ai_daily_present()

    dims = [
        ("Per-day row caps (every high-write table)", cov_rc == 0, coverage(cov_out)),
        ("Text-field caps (server-side left() triggers)", t_all > 0 and t_ok == t_all, f"{t_ok}/{t_all}"),
        ("Upload caps (photo/audio/file size+duration)", u_all > 0 and u_ok == u_all, f"{u_ok}/{u_all}"),
        ("Logbook pilot (reference impl, deep gate)", lb_rc == 0, coverage(lb_out)),
        ("AI rate limits (hourly + daily ceiling)", ai_daily, "hourly+daily" if ai_daily else "hourly-only"),
    ]

    lines = ["# FREE-TIER QUOTA BOARD — measured coverage", "",
             "One board over every free-tier bound. Generated by `tools/quota_board.py`.", "",
             "| Dimension | Status | Coverage |", "|---|:--:|:--:|"]
    print("=" * 74)
    print("  FREE-TIER QUOTA BOARD (Q5 unified) — every free-tier bound in one place")
    print("=" * 74)
    all_green = True
    for name, ok, cov in dims:
        all_green = all_green and ok
        tag = f"{GREEN}ok{RST}  " if ok else f"{RED}FAIL{RST}"
        print(f"  {tag} {name:46s} {cov}")
        lines.append(f"| {name} | {'✅' if ok else '❌'} | {cov} |")

    lines += ["", f"**Verdict: {'ALL GREEN — free but bounded' if all_green else 'RED — an uncapped surface exists'}**",
              "", "_Ratchet: this board FAILs if a new high-write table ships without a per-day cap "
              "(via validate_quota_coverage) or a text/upload surface loses its cap._"]
    (ROOT / "FREE_TIER_QUOTA_BOARD.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print()
    if all_green:
        print(f"  {GREEN}PASS{RST} — all {len(dims)} quota dimensions green; board written to FREE_TIER_QUOTA_BOARD.md")
        return 0
    print(f"  {RED}FAIL{RST} — a quota dimension is red (see above); board written to FREE_TIER_QUOTA_BOARD.md")
    return 1 if check else 0


if __name__ == "__main__":
    raise SystemExit(main())
