#!/usr/bin/env python3
"""ai-render-provenance - T87/AI6: the render half of machine authorship (2026-08-26).

validate_ai_write_provenance.py proves the WRITE half at 6/6: every AI write into a
human-read domain table declares machine authorship ON THE ROW. That is necessary and
it is not sufficient, because a row can carry its provenance faithfully and the page
can throw it away on the way to the screen.

★THAT IS EXACTLY WHAT WAS HAPPENING. logbook.html's "past repairs on this machine"
panel - the one a technician reads before opening a machine - queried fault_knowledge
with `.select('problem, root_cause, action, knowledge, worker_name, created_at')` and
rendered each row attributed by NAME. fault_knowledge is a table the AI also writes
into (visual-defect-capture), so a machine-captured observation would have appeared as
a repair a named colleague performed. The write was accountable; the READ discarded the
accountability. Fixed: the select now fetches `source, ai_model` and the render appends
"AI-captured (<model>)" beside the name. Verified live - one badge among five rows, the
four human entries untouched.

★THE BADGE TESTS `source LIKE 'ai_%'`, NOT `!== 'manual'`, because that is the contract
the DATABASE enforces: CHECK ((source ~~ 'ai\\_%') = (ai_model IS NOT NULL)), over a
closed vocabulary of manual / ai_visual_capture / cmms_import. Reading a row by the same
rule the write is held to means the badge cannot drift from the guarantee - and
cmms_import, which is an import rather than a machine author, is correctly left alone.

THE ASSERTION: for every AI-written domain table with a provenance column, any client
page that QUERIES it must select a provenance field and carry a disclosure string.

Scope is honest and narrow: only tables with a real client-side read. The others
(knowledge_graph_facts, asset_risk_scores, failure_signature_alerts) reach the glass
through RPCs and edge functions, whose surfaces T87 evidenced live instead - alert-hub,
the AMC brief, engineering-design and shift-brain each render their disclosure. A gate
should assert what it can actually see.

Usage: python tools/validate_ai_render_provenance.py
"""
import glob
import io
import re
import sys
from pathlib import Path

if sys.platform == "win32" and sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parent.parent
SKIP = re.compile(r"backup|test|^index-", re.I)

# table -> the provenance columns its rows carry (mirrors validate_ai_write_provenance.PROV_KEYS)
AI_TABLES = {
    "fault_knowledge": ("source", "ai_model", "ai_confidence"),
    "rcm_fmea_modes": ("source", "ai_confidence"),
    "shift_plans": ("generated_by", "model_version"),
    "knowledge_graph_facts": ("source_type",),
    "asset_risk_scores": ("model_version",),
    "failure_signature_alerts": ("detail_source", "source"),
}
DISCLOSURE = re.compile(
    r"AI[- ]?(?:captured|drafted|generated|suggested|written|composed)|from AI |generated by|"
    r"composed by|machine[- ]generated|AI logbook scan|model [a-z0-9.\-]*v?\d", re.I)


# ★THE NEGATIVE LOOKAHEAD IS LOAD-BEARING. `accept="image/*"` contains a literal /* , and a
# naive block-comment strip treated it as a comment OPENER - on logbook.html that swallowed 58,551
# characters up to the next real */, blanking an entire modal including an onclick. A census built
# on that reported a live, recently-hardened Save handler as dead code. A real comment opener is
# never immediately followed by a quote; a MIME wildcard in an attribute always is.
def strip_comments(src: str) -> str:
    def blank(m):
        # ★KEEP THE NEWLINES. Replacing a multi-line comment with plain spaces preserves byte
        # offsets but destroys LINE counts, and the first version did exactly that: it reported the
        # asset-hub finding at line 2774, which is an Escape-key handler. The real query is at 2584.
        # A gate that names the wrong line sends the reader hunting and gets disbelieved.
        return "".join(c if c == "\n" else " " for c in m.group(0))
    s = re.sub(r"<!--.*?-->", blank, src, flags=re.S)
    # (?!quote) below: accept="image/*" is NOT a comment opener
    s = re.sub(r"/\*(?![\"']).*?\*/", blank, s, flags=re.S)
    return re.sub(r"(?m)^[ \t]*//[^\n]*$", blank, s)


def _select_args(tail: str, sel_start: int) -> str:
    """The text INSIDE this .select(...) call, paren-balanced.

    Bounded to the call's OWN parentheses on purpose. A fixed character window would happily
    read the next query's options object, and on a page that renders a list and then counts it
    the two queries sit a few lines apart - so the window would exempt the DISPLAY read using
    the COUNT read's `head: true`, which is the precise inverse of this gate's job.
    """
    i = tail.find("(", sel_start)
    if i < 0:
        return ""
    depth = 0
    for j in range(i, len(tail)):
        if tail[j] == "(":
            depth += 1
        elif tail[j] == ")":
            depth -= 1
            if depth == 0:
                return tail[i + 1:j]
    return tail[i + 1:i + 200]


def scan_source(src: str, name: str):
    """Return (checked, gaps) for one already-comment-stripped source."""
    checked, gaps = 0, []
    for table, prov in AI_TABLES.items():
        for m in re.finditer(r"\.from\(\s*['\"]" + re.escape(table) + r"(?:_truth|_view)?['\"]\s*\)", src):
            # the select list of THIS query: the chained .select(...) that follows
            # ★2000, NOT 600, AND THE TEETH TEST IS WHY. At 600 the window ended before
            # logbook's .select(), because the explanatory comment above that line is ~700
            # characters - so the gate silently stopped seeing the very query it was built for
            # and reported PASS with the fix reverted. A scan window sized to today's code is a
            # gate that quietly narrows every time someone documents something.
            tail = src[m.end():m.end() + 2000]
            sel = re.search(r"\.select\(\s*(['\"`])(.*?)\1", tail, re.S)
            if not sel:
                continue                     # count(*) with no select list renders nothing
            # ★A HEAD/COUNT QUERY SHIPS NO ROWS, and the exemption above misses it because it
            # DOES carry a select list. logbook's fault-history panel pairs a display read (which
            # correctly selects source + ai_model) with a separate
            # .select('id', { count: 'exact', head: true }) whose only job is to say "showing 10
            # of 47" - and this gate charged that COUNT with the DISPLAY's obligation, reporting
            # a page that had already been fixed. A query that renders no rows cannot drop
            # provenance; asking it to carry a provenance column would be asking for a column
            # nobody will ever see, which is how a gate teaches people to add noise.
            if re.search(r"\bhead\s*:|count\s*:", _select_args(tail, sel.start())):
                continue
            # ★A .select() AFTER A MUTATION IS NOT A DISPLAY READ, and mistaking one for the
            # other produced this gate's only false accusation. asset-hub's approve path runs
            # .update({approved_by...}).eq(id).is('approved_at', null).select('id') - the select
            # exists to DETECT A 0-ROW NO-OP under optimistic concurrency, so a second supervisor
            # cannot silently overwrite the first one's approval. It renders nothing; the page
            # re-reads through loadDetailFmea(), whose display query does select provenance.
            if re.search(r"\.(update|insert|upsert|delete)\s*\(", tail[:sel.start()]):
                continue
            checked += 1
            cols = sel.group(2)
            if not any(p in cols for p in prov):
                line = src[:m.start()].count("\n") + 1
                gaps.append(f"{name}:{line} reads {table} for display but selects no provenance "
                            f"column ({'/'.join(prov)}) - the row knows who wrote it, the screen "
                            f"will not")
            elif not DISCLOSURE.search(src):
                line = src[:m.start()].count("\n") + 1
                gaps.append(f"{name}:{line} selects provenance from {table} but the page never "
                            f"discloses machine authorship anywhere")
    return checked, gaps


def main() -> int:
    files = [f for f in sorted(glob.glob(str(ROOT / "*.html"))) if not SKIP.search(Path(f).name)]
    if not files:
        print("SKIP ai-render-provenance - no pages found")
        return 0

    checked, gaps = 0, []
    for f in files:
        c, g = scan_source(strip_comments(io.open(f, encoding="utf-8", errors="replace").read()),
                           Path(f).name)
        checked += c
        gaps += g

    print(f"  display queries into AI-written tables: {checked} | missing provenance: {len(gaps)}")
    if gaps:
        print(f"FAIL ai-render-provenance - {len(gaps)} read(s) that drop machine authorship:")
        for x in gaps[:10]:
            print("    - " + x)
        print("    The write gate proves the ROW declares its author; this one asks whether the SCREEN")
        print("    still says so. An AI-captured observation rendered beside a colleague's name reads")
        print("    as that colleague's work - and this is the panel people consult before opening a")
        print("    machine. Select the provenance column and show it.")
        return 1
    print(f"PASS ai-render-provenance - all {checked} display reads of AI-written tables carry their "
          f"provenance through to the screen.")
    return 0


def selftest() -> int:
    """Teeth. This gate had none, and shipped a false accusation because of it.

    Case 1 IS the bug that prompted these: logbook's fault-history panel had already been fixed -
    its display read selects source and ai_model - and the gate still failed the page, because the
    COUNT query beside it also carries a .select() and the old exemption only skipped queries with
    no select at all. A gate whose only witness is the live tree cannot tell 'the page is wrong'
    from 'I am wrong about the page'.
    """
    DISCLOSED = "\n// AI-captured by model v2\n"
    cases = [
        ("head/count query is exempt (renders no rows)",
         "db.from('fault_knowledge').select('id', { count: 'exact', head: true }).eq('machine', m)",
         0),
        ("display read with no provenance is caught",
         "db.from('fault_knowledge').select('problem, root_cause, worker_name').eq('machine', m)",
         1),
        ("display read carrying provenance + disclosure passes",
         "db.from('fault_knowledge').select('problem, source, ai_model').eq('machine', m)" + DISCLOSED,
         0),
        ("select after a mutation is not a display read",
         "db.from('fault_knowledge').update({ x: 1 }).eq('id', i).select('id')",
         0),
        ("provenance selected but the page never discloses it is caught",
         "db.from('fault_knowledge').select('problem, source, ai_model').eq('machine', m)",
         1),
    ]
    bad = 0
    for label, src, want in cases:
        _, gaps = scan_source(src, "case.html")
        got = len(gaps)
        ok = got == want
        bad += 0 if ok else 1
        print(f"  {'ok  ' if ok else 'FAIL'} {label} (want {want} gap(s), got {got})")
    print("PASS ai-render-provenance selftest" if not bad
          else f"FAIL ai-render-provenance selftest - {bad} case(s) wrong")
    return 0 if not bad else 1


if __name__ == "__main__":
    sys.exit(selftest() if "--selftest" in sys.argv else main())
