#!/usr/bin/env python3
"""
validate_onconflict_index.py - PER_PAGE_BUGHUNT P3/P4 gate: every supabase-js `.upsert(rows,{onConflict})`
must have a MATCHING unique index (2026-07-19).
=====================================================================================================
ROOT BUG this locks (found live 2026-07-19): integrations.html's CMMS inventory import upserted
`inventory_items` with `onConflict:'part_number,hive_id'`, but NO unique index on those columns existed
(only the pkey). Postgres rejects such an upsert at RUNTIME with "there is no unique or exclusion
constraint matching the ON CONFLICT specification" -> the supervisor's whole inventory import CRASHED.
Nothing static caught it because the SQL is generated by supabase-js and the index lives in a migration.
The same missing index left submitPart's client-only "already exists" check as a double-submit RACE.
Fixed by migration 20260719000001 (unique index on inventory_items(part_number, hive_id)).

METHOD: parse every `.from('TABLE').upsert( ... onConflict: 'colA,colB' )` in the page HTML (the onConflict
may sit up to ~600 chars after the .from, across newlines). For each (table, cols), assert the live DB has
a UNIQUE index whose column SET == the onConflict set (Postgres ON CONFLICT arbiter inference is
set-based, order-insensitive). Any onConflict with no matching unique index FAILs — that upsert would
throw at runtime. Skips cleanly (exit 0) if docker/DB is unreachable. `--selftest` proves teeth.
"""
from __future__ import annotations
import io, sys, re, subprocess
from pathlib import Path

if sys.platform == "win32" and sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding="utf-8", errors="replace")

G = "\033[92m"; R = "\033[91m"; B = "\033[1m"; X = "\033[0m"
CHECK_NAMES = ["validate_onconflict_index"]
DB = "supabase_db_workhive"
ROOT = Path(__file__).resolve().parent.parent

# .from('table').upsert( <up to 600 chars, any newlines> onConflict: 'colA,colB' )
UPSERT_RE = re.compile(
    r"""\.from\(\s*['"](?P<tbl>\w+)['"]\s*\)\s*\.upsert\((?P<body>[\s\S]{0,600}?onConflict:\s*['"](?P<cols>[^'"]+)['"])""",
    re.MULTILINE,
)


def find_onconflicts() -> list[tuple[str, str, frozenset, Path]]:
    """Return (table, raw_cols, colset, file) for every upsert-with-onConflict in the page HTML."""
    hits = []
    for html in sorted(ROOT.glob("*.html")):
        txt = html.read_text(encoding="utf-8", errors="ignore")
        for m in UPSERT_RE.finditer(txt):
            cols = m.group("cols")
            colset = frozenset(c.strip() for c in cols.split(",") if c.strip())
            hits.append((m.group("tbl"), cols, colset, html.name))
    return hits


def db_unique_indexes() -> dict[str, list[frozenset]] | None:
    """table -> list of unique-index column SETS from the live DB. None if unreachable."""
    sql = (
        "select t.relname, ix.relname, "
        "string_agg(a.attname, ',') "
        "from pg_index i "
        "join pg_class ix on ix.oid=i.indexrelid "
        "join pg_class t on t.oid=i.indrelid "
        "join pg_namespace n on n.oid=t.relnamespace "
        "join pg_attribute a on a.attrelid=t.oid and a.attnum = any(i.indkey) "
        "where i.indisunique and n.nspname='public' "
        "group by t.relname, ix.relname;"
    )
    try:
        r = subprocess.run(["docker", "exec", "-i", DB, "psql", "-U", "postgres", "-d", "postgres", "-t", "-A"],
                           input=sql, capture_output=True, text=True, timeout=30)
    except Exception:
        return None
    out = (r.stdout or "") + (r.stderr or "")
    if r.returncode != 0 or "could not" in out.lower() or "no such container" in out.lower():
        return None
    idx: dict[str, list[frozenset]] = {}
    for ln in out.splitlines():
        parts = ln.split("|")
        if len(parts) != 3:
            continue
        tbl, _idxname, cols = parts
        idx.setdefault(tbl, []).append(frozenset(c.strip() for c in cols.split(",") if c.strip()))
    return idx


def evaluate() -> tuple[list[str], int]:
    hits = find_onconflicts()
    idx = db_unique_indexes()
    if idx is None:
        return (["SKIP: local DB not reachable — onConflict-index gate not evaluated."], 0)
    failures = []
    for tbl, raw, colset, fname in hits:
        matches = idx.get(tbl, [])
        if colset not in matches:
            failures.append(
                f"{fname}: .from('{tbl}').upsert(onConflict:'{raw}') has NO matching unique index "
                f"(the upsert would throw at runtime). Add a UNIQUE index on ({raw})."
            )
    return (failures, len(hits))


def selftest() -> int:
    """Prove the parser + set-matcher have teeth on a synthetic case."""
    ok = True
    # a fake onConflict set with no matching index must be flagged
    fake_idx = {"widgets": [frozenset({"id"})]}
    colset = frozenset({"a", "b"})
    if colset in fake_idx.get("widgets", []):
        print(f"{R}selftest FAIL: false-match{X}"); ok = False
    # order-insensitivity: (b,a) index must satisfy (a,b) onConflict
    idx2 = {"widgets": [frozenset({"b", "a"})]}
    if frozenset({"a", "b"}) not in idx2["widgets"]:
        print(f"{R}selftest FAIL: set-match not order-insensitive{X}"); ok = False
    # the real parser must find the known integrations inventory upsert
    hits = find_onconflicts()
    if not any(t == "inventory_items" and cs == frozenset({"part_number", "hive_id"}) for t, _, cs, _ in hits):
        print(f"{R}selftest FAIL: parser missed inventory_items onConflict{X}"); ok = False
    print(f"{G}selftest PASS{X}" if ok else f"{R}selftest FAILED{X}")
    return 0 if ok else 1


def main() -> int:
    if "--selftest" in sys.argv or "--self-test" in sys.argv:
        return selftest()
    failures, n = evaluate()
    print(f"{B}onConflict-index gate{X} — {n} upsert(onConflict) site(s) across page HTML")
    if failures and failures[0].startswith("SKIP"):
        print(f"  {failures[0]}")
        return 0
    if failures:
        print(f"{R}  {len(failures)} onConflict without a matching unique index:{X}")
        for f in failures:
            print(f"   - {f}")
        return 1
    print(f"{G}  PASS — every onConflict has a matching unique index.{X}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
