-- Engineering Design Tier D-f: register 58 calc handler
-- formulas in canonical_formulas (2026-05-12).
--
-- Each row is generated from the corresponding python-api/calcs/<name>.py
-- handler. The library_source field points at the actual Python function
-- that implements the formula. standard_ids are the cited bodies/numbers
-- from the docstring (already registered in canonical_standards).
--
-- Skills consulted: maintenance-expert (formula taxonomy), data-engineer
-- (canonical registry pattern), platform-guardian (forward-only ratchet).

BEGIN;

INSERT INTO public.canonical_formulas (formula_id, name, domain, standard_ids, library_source, inputs, outputs, formula_text, description) VALUES
  ('ahu_sizing_ashrae_62', 'Ahu Sizing', 'hvac', ARRAY['ashrae_62','ashrae_90','ashrae_2021'], 'python:python-api/calcs/ahu_sizing.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'AHU Sizing - Phase 2b Standards: ASHRAE 62.1, ASHRAE 90.1, ASHRAE 2021 Fundamentals Ch.1 (Psychrometrics), SMACNA HVAC Systems Duct Design, PNS/PSME'),
  ('beam_column', 'Beam Column', 'mechanical', ARRAY[]::text[], 'python:python-api/calcs/beam_column.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Beam / Column Structural Design - Phase 7a Standards: NSCP 2015 Vol.1 (National Structural Code of the Philippines), AISC 360-22 (Steel), ACI 318-19 (Concrete),'),
  ('bearing_life_iso_281_2007', 'Bearing Life', 'mechanical', ARRAY['iso_281_2007','iso_281'], 'python:python-api/calcs/bearing_life.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Bearing Life (L10) — Phase 9i (Option B port from TypeScript) Standards: ISO 281:2007 (Rolling Bearings — Dynamic Load Ratings), ABMA Std 11 (Load Ratings Ball Bearings),'),
  ('boiler_steam', 'Boiler Steam', 'plumbing', ARRAY[]::text[], 'python:python-api/calcs/boiler_steam.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Boiler / Steam System - Phase 9d Standards: ASME BPVC Section I (Power Boilers), ASME BPVC Section IV (Heating Boilers),'),
  ('boiler_system', 'Boiler System', 'plumbing', ARRAY[]::text[], 'python:python-api/calcs/boiler_system.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Boiler System — Mechanical (unifies with Python, was TypeScript-only) Standards: ASME BPVC Section I/IV, ASME B31.1, PD 8 (Philippines), DOLE OSHS Rule 1230, PSME Code'),
  ('bolt_torque_iso_898_1', 'Bolt Torque', 'mechanical', ARRAY['iso_898_1'], 'python:python-api/calcs/bolt_torque.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Bolt Torque & Preload — Phase 9j (Option B port from TypeScript) Standards: ISO 898-1:2013 (Mechanical Properties of Fasteners), VDI 2230:2015 (Systematic Calculation of Bolted Joints),'),
  ('cable_tray_sizing_nec_2023', 'Cable Tray Sizing', 'electrical', ARRAY['nec_2023','nec_392'], 'python:python-api/calcs/cable_tray_sizing.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Cable Tray Sizing — Phase 4h (Option B port from TypeScript) Standards: NEMA VE 1-2017 (Cable Tray Systems), NEC 2023 Article 392, PEC 2017 Article 3.92'),
  ('chiller_ashrae_90', 'Chiller', 'hvac', ARRAY['ashrae_90','ashrae_2021'], 'python:python-api/calcs/chiller.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Chiller System - Phase 3c (Water-Cooled and Air-Cooled) Standards: ASHRAE 90.1-2019 Table 6.8.1 (minimum efficiency), AHRI 550/590 (performance rating), ASHRAE 2021 Fundamentals Ch.2, PSME Code'),
  ('clean_agent_suppression_nfpa_2001_2022', 'Clean Agent Suppression', 'fire', ARRAY['nfpa_2001_2022','iso_14520_2015','nfpa_2001','iso_14520','nfpa_12','iso_14520_7'], 'python:python-api/calcs/clean_agent_suppression.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Clean Agent Suppression — Fire Protection (Phase 5d) Standards: NFPA 2001:2022 (Clean Agent Fire Extinguishing Systems), ISO 14520:2015 (Gaseous Fire-Extinguishing Systems),'),
  ('compressed_air_iso_1217', 'Compressed Air', 'pneumatic', ARRAY['iso_1217'], 'python:python-api/calcs/compressed_air.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Compressed Air System - Phase 1c Standards: ISO 1217, PSME Code, ASME B31.3, CAGI (Compressed Air & Gas Institute) Libraries: fluids (Darcy-Weisbach, pipe sizing), numpy (iteration)'),
  ('cooling_tower_ashrae_2021', 'Cooling Tower', 'hvac', ARRAY['ashrae_2021','ashrae_90'], 'python:python-api/calcs/cooling_tower.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Cooling Tower Sizing - Phase 2c Standards: CTI STD-201 (Cooling Technology Institute), ASHRAE 2021 Fundamentals Ch.39, ASHRAE 90.1, PSME Code, ASME PTC 23'),
  ('domestic_water_ashrae_2021', 'Domestic Water', 'plumbing', ARRAY['ashrae_2021'], 'python:python-api/calcs/domestic_water.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Domestic Water System - Phase 6a Standards: PSME Code (Philippine Society of Mechanical Engineers), ASHRAE 2021 Fundamentals Ch.50, ASPE Data Book Vol.2,'),
  ('drainage_pipe_sizing', 'Drainage Pipe Sizing', 'plumbing', ARRAY[]::text[], 'python:python-api/calcs/drainage_pipe_sizing.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Drainage Pipe Sizing — Plumbing (unifies with Python, was TypeScript-only) Standards: Philippine Plumbing Code (PPC), UPC Table 7-5, Manning''s Formula for self-cleansing velocity'),
  ('duct_sizing_ashrae_2021', 'Duct Sizing', 'hvac', ARRAY['ashrae_2021','ashrae_62'], 'python:python-api/calcs/duct_sizing.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Duct Sizing - Phase 2d (Equal Friction Method) Standards: ASHRAE 2021 Fundamentals Ch.21 (Duct Design), SMACNA HVAC Systems Duct Design 4th Ed., ASHRAE 62.1, PNS/PSME'),
  ('earthing_grounding_iec_60364_5', 'Earthing Grounding', 'electrical', ARRAY['iec_60364_5'], 'python:python-api/calcs/earthing_grounding.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Earthing / Grounding System — Phase 7b (Option B port from TypeScript) Standards: PEC 2017 Art. 2.50 (Grounding), IEC 60364-5-54, IEEE Std 142 (Green Book), OSHS PD 856 (Philippines)'),
  ('elevator_traffic_iso_4190_6', 'Elevator Traffic', 'mechanical', ARRAY['iso_4190_6'], 'python:python-api/calcs/elevator_traffic.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Elevator Traffic Analysis — Vertical Transport (Option B port from TypeScript) Standards: CIBSE Guide D:2015 (Transportation Systems in Buildings), ASME A17.1:2019 (Safety Code for Elevators),'),
  ('expansion_tank_ashrae_2023', 'Expansion Tank', 'hvac', ARRAY['ashrae_2023'], 'python:python-api/calcs/expansion_tank.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Expansion Tank Sizing — Phase 3d (Option B port from TypeScript) Standards: ASHRAE 2023 HVAC Systems & Equipment Ch.12, ASME Section VIII (Pressure Vessels), ASME B31.9'),
  ('fcu_selection_ashrae_62', 'Fcu Selection', 'hvac', ARRAY['ashrae_62','ashrae_90','ashrae_2021'], 'python:python-api/calcs/fcu_selection.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'FCU Selection - Phase 3b Standards: ASHRAE 62.1, ASHRAE 90.1, ASHRAE 2021 Fundamentals Ch.1, PSME Code, ARI 440 (Fan Coil Units)'),
  ('fire_alarm_battery_nfpa_72_2022', 'Fire Alarm Battery', 'fire', ARRAY['nfpa_72_2022','nfpa_72'], 'python:python-api/calcs/fire_alarm_battery.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Fire Alarm Battery Standby — Phase 5d (Option B port from TypeScript) Standards: NFPA 72:2022 §10.6.7 (battery standby), NFPA 72 §10.6.9.3, UL 864 (Control Units), PEC 2017 Art. 7'),
  ('fire_pump_nfpa_20_2022', 'Fire Pump', 'mechanical', ARRAY['nfpa_20_2022','nfpa_13_2022','nfpa_20','nfpa_25'], 'python:python-api/calcs/fire_pump.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Fire Pump Sizing - Phase 5b Standards: NFPA 20:2022 (Installation of Stationary Pumps for Fire Protection), NFPA 13:2022 (demand basis), PNS NFPA 20 (Philippine adoption),'),
  ('fire_sprinkler_nfpa_13_2022', 'Fire Sprinkler', 'fire', ARRAY['nfpa_13_2022','nfpa_13'], 'python:python-api/calcs/fire_sprinkler.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Fire Sprinkler Hydraulic Calculation - Phase 5a Standards: NFPA 13:2022 (Installation of Sprinkler Systems), NFPA 13R:2022 (Residential), PNS NFPA 13 (Philippine adoption),'),
  ('fluid_power_iso_4413_2010', 'Fluid Power', 'hydraulic', ARRAY['iso_4413_2010'], 'python:python-api/calcs/fluid_power.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Fluid Power / Hydraulics - Phase 9b Standards: ISO 4413:2010 (Hydraulic fluid power - safety requirements), NFPA T2.12.10 (Hydraulic systems - design),'),
  ('gear_belt_drive_iso_6336', 'Gear Belt Drive', 'mechanical', ARRAY['iso_6336'], 'python:python-api/calcs/gear_belt_drive.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Gear / Belt Drive - Phase 8b Standards: AGMA 2001-D04 (Fundamental Rating Factors for Involute Spur/Helical Gears), AGMA 6006-A03 (Design of Worm Gearings),'),
  ('generator_sizing_iso_8528_1', 'Generator Sizing', 'electrical', ARRAY['iso_8528_1','ieee_446','nfpa_110','iso_3046_1'], 'python:python-api/calcs/generator_sizing.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Generator Sizing - Phase 4d Standards: ISO 8528-1:2018 (Reciprocating IC engine driven AC generators), IEEE 446 (Emergency/Standby Power), PEC 2017, NFPA 110,'),
  ('grease_trap', 'Grease Trap', 'plumbing', ARRAY[]::text[], 'python:python-api/calcs/grease_trap.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Grease Trap Sizing — Phase 6g (Option B port from TypeScript) Standards: PDI G-101 (Plumbing & Drainage Institute), ASME A112.14.3, PPC §P-1001 to §P-1007, DENR DAO 2016-08'),
  ('harmonic_distortion_ieee_519_2022', 'Harmonic Distortion', 'electrical', ARRAY['ieee_519_2022','iec_61000_3'], 'python:python-api/calcs/harmonic_distortion.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Harmonic Distortion Analysis — Electrical: Power Quality (Phase 9f) Standards: IEEE 519-2022 (Recommended Practice for Harmonic Control), IEC 61000-3-2:2018 (Limits for Harmonic Current Emissions),'),
  ('heat_exchanger', 'Heat Exchanger', 'hvac', ARRAY[]::text[], 'python:python-api/calcs/heat_exchanger.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Heat Exchanger Design - Phase 8d Standards: TEMA (Tubular Exchanger Manufacturers Association) 10th Ed., ASME Sec. VIII Div.1 (pressure parts),'),
  ('hoist_capacity', 'Hoist Capacity', 'mechanical', ARRAY[]::text[], 'python:python-api/calcs/hoist_capacity.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Hoist Capacity — Vertical Transport (Option B port from TypeScript) Standards: ASME B30.2 (Overhead and Gantry Cranes), ASME HST-4 (Hand Chain Lever Hoists),'),
  ('hot_water_demand', 'Hot Water Demand', 'plumbing', ARRAY[]::text[], 'python:python-api/calcs/hot_water_demand.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Hot Water Demand — Plumbing (unifies with Python, was TypeScript-only) Standards: ASHRAE HVAC Applications Handbook Ch.50, Philippine Plumbing Code (PPC), DOH Sanitation Code'),
  ('hvac_cooling_load_ashrae_62', 'Hvac Cooling Load', 'hvac', ARRAY['ashrae_62','ashrae_90','ashrae_55','ashrae_2021'], 'python:python-api/calcs/hvac_cooling_load.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'HVAC Cooling Load - Phase 2a Standards: ASHRAE 62.1, ASHRAE 90.1, ASHRAE 55, ASHRAE Fundamentals 2021 Ch.18 Libraries: psychrolib (psychrometrics), numpy'),
  ('lighting_design_ashrae_90', 'Lighting Design', 'lighting', ARRAY['ashrae_90'], 'python:python-api/calcs/lighting_design.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Lighting Design - Phase 7b Standards: IESNA (Illuminating Engineering Society of North America) Handbook 10th Ed., IES RP-1 (Offices), IES RP-7 (Industrial), IES RP-28 (Parking),'),
  ('lightning_protection_iec_62305_1', 'Lightning Protection', 'lightning_protection', ARRAY['iec_62305_1','iec_62305_2','iec_62305_3','iec_62305_4'], 'python:python-api/calcs/lightning_protection.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Lightning Protection System (LPS) Design - Phase 7c Standards: IEC 62305-1:2010 (General principles), IEC 62305-2:2010 (Risk management),'),
  ('load_estimation_iec_60364', 'Load Estimation', 'electrical', ARRAY['iec_60364'], 'python:python-api/calcs/load_estimation.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Load Estimation — Electrical (unifies with Python, was TypeScript-only) Standards: PEC 2017 Article 2.10 / 2.20, IEC 60364 Libraries: math'),
  ('load_schedule_nec_2020', 'Load Schedule', 'electrical', ARRAY['nec_2020','ieee_141'], 'python:python-api/calcs/load_schedule.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Load Schedule - Phase 4c Standards: PEC 2017 (Philippine Electrical Code), NEC 2020, IEEE 141 (Red Book), DOLE/OSHC, PEEP (Philippine Energy Efficiency)'),
  ('noise_acoustics_iso_9613_2', 'Noise Acoustics', 'acoustics', ARRAY['iso_9613_2','osha_29','iec_61672_1','ashrae_2019'], 'python:python-api/calcs/noise_acoustics.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Noise / Acoustics - Phase 9c Standards: ISO 9613-2:1996 (Attenuation of sound - outdoor propagation), OSHA 29 CFR 1910.95 (Occupational noise exposure),'),
  ('pipe_sizing_ashrae_2021', 'Pipe Sizing', 'plumbing', ARRAY['ashrae_2021','iso_4427'], 'python:python-api/calcs/pipe_sizing.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Pipe Sizing - Phase 1b Standards: ASHRAE 2021 Fundamentals Ch. 22, PSME Code, PNS/ISO 4427 Libraries: fluids (Darcy-Weisbach, Colebrook-White), iapws (water properties)'),
  ('power_factor_correction_ieee_18_2012', 'Power Factor Correction', 'electrical', ARRAY['ieee_18_2012','ieee_1036_2010','ieee_18'], 'python:python-api/calcs/power_factor_correction.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Power Factor Correction — Phase 4f (Option B port from TypeScript) Standards: IEEE 18-2012 (Shunt Capacitors), IEEE 1036-2010 (Application Guide), PEC 2017 Article 4.60, Meralco PF surcharge policy (threshold 0.85)'),
  ('pressure_vessel', 'Pressure Vessel', 'mechanical', ARRAY[]::text[], 'python:python-api/calcs/pressure_vessel.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Pressure Vessel Design - Phase 8c Standards: ASME Boiler and Pressure Vessel Code (BPVC) Section VIII Division 1, ASME Section II Part D (Material properties),'),
  ('pump_tdh_iso_9906', 'Pump Tdh', 'mechanical', ARRAY['iso_9906','ashrae_2021'], 'python:python-api/calcs/pump_tdh.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Pump Sizing (TDH) - Phase 1 Standards: ISO 9906, PSME Code, ASHRAE 2021 Fundamentals Ch. 22 Libraries: fluids (Darcy-Weisbach, Colebrook-White), iapws (water properties)'),
  ('refrigerant_pipe_ashrae_2022', 'Refrigerant Pipe', 'hvac', ARRAY['ashrae_2022','ashrae_90'], 'python:python-api/calcs/refrigerant_pipe.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Refrigerant Pipe Sizing - Phase 3a Standards: ASHRAE 2022 Refrigeration Handbook Ch.1, ASTM B280 (ACR copper), ASHRAE 90.1 (insulation), PSME Code'),
  ('roof_drain', 'Roof Drain', 'plumbing', ARRAY[]::text[], 'python:python-api/calcs/roof_drain.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Roof Drain Sizing — Phase 6l (Option B port from TypeScript) Standards: IPC 2021 §1106, Philippine Plumbing Code §P-915 to §P-918, ASPE Design Handbook Vol. 2, SMACNA Architectural Sheet Metal'),
  ('septic_tank', 'Septic Tank', 'plumbing', ARRAY[]::text[], 'python:python-api/calcs/septic_tank.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Septic Tank Sizing — Phase 6f (Option B port from TypeScript) Standards: Philippine Plumbing Code (PPC) §P-1101 to §P-1107, DOH Sanitation Code P.D. 856, DENR DAO 2016-08 Effluent Standards,'),
  ('sewer_drainage', 'Sewer Drainage', 'plumbing', ARRAY[]::text[], 'python:python-api/calcs/sewer_drainage.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Sewer / Drainage System - Phase 6b Standards: NSCP (National Structural Code of the Philippines) Vol.2 Plumbing, PSME Code (Philippine Society of Mechanical Engineers),'),
  ('shaft_design', 'Shaft Design', 'mechanical', ARRAY[]::text[], 'python:python-api/calcs/shaft_design.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Shaft Design - Phase 8a Standards: ASME B106.1M (Design of Transmission Shafting), ASME B17.1 (Keys and Keyseats),'),
  ('short_circuit_iec_60909_0', 'Short Circuit', 'electrical', ARRAY['iec_60909_0','ieee_141','ieee_242','iec_60909'], 'python:python-api/calcs/short_circuit.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Short Circuit Analysis - Phase 4b Standards: IEC 60909-0:2016 (Short-circuit currents in AC systems), PEC 2017 Article 2.40, IEEE 141 (Red Book), IEEE 242 (Buff Book)'),
  ('solar_pv_iec_62548_2016', 'Solar Pv', 'solar_pv', ARRAY['iec_62548_2016','iec_61215','iec_62109','ieee_929','iec_62548'], 'python:python-api/calcs/solar_pv.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Solar PV System - Phase 4f Standards: IEC 62548:2016 (PV array design requirements), IEC 61215 (Module performance testing at STC),'),
  ('stairwell_pressurization_nfpa_92_2021', 'Stairwell Pressurization', 'hvac', ARRAY['nfpa_92_2021','nfpa_92'], 'python:python-api/calcs/stairwell_pressurization.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Stairwell Pressurization — Phase 5c (Option B port from TypeScript) Standards: NFPA 92:2021 (Smoke Control Systems), PEC 2017, PSME Code Libraries: math'),
  ('storm_drain', 'Storm Drain', 'plumbing', ARRAY[]::text[], 'python:python-api/calcs/storm_drain.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Storm Drain / Stormwater — Phase 6k (Option B port from TypeScript) Standards: DPWH Drainage Design Guidelines (Blue Book), NSCP 2015 Vol.2, PAGASA IDF curves (intensity-duration-frequency), Rational Method'),
  ('transformer_sizing_iec_60076_1', 'Transformer Sizing', 'electrical', ARRAY['iec_60076_1'], 'python:python-api/calcs/transformer_sizing.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Transformer Sizing — Electrical: Supply & Distribution (Phase 4h) Standards: PEC 2017 Art. 4.50, IEC 60076-1:2011 (Power Transformers), IEEE C57.12.00 (General Requirements for Transformers),'),
  ('ups_sizing_ieee_1184_2006', 'Ups Sizing', 'electrical', ARRAY['ieee_1184_2006','iec_62040_3','ieee_446','ieee_1184'], 'python:python-api/calcs/ups_sizing.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'UPS Sizing - Phase 4e Standards: IEEE 1184:2006 (Guide for Batteries for Stationary Applications), IEC 62040-3:2021 (UPS performance and test requirements),'),
  ('ventilation_ach_ashrae_62', 'Ventilation Ach', 'hvac', ARRAY['ashrae_62','ashrae_90'], 'python:python-api/calcs/ventilation_ach.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Ventilation / ACH — Mechanical (Option B port from TypeScript) Standards: ASHRAE 62.1:2022 Ventilation Rate Procedure, ASHRAE 90.1:2022 (energy), PSME Code, PEC 2017'),
  ('vibration_analysis_iso_10816_3', 'Vibration Analysis', 'mechanical', ARRAY['iso_10816_3','iso_10816_1','iso_20816_1','iso_10816'], 'python:python-api/calcs/vibration_analysis.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Vibration Analysis - Phase 9a Standards: ISO 10816-3 (Vibration severity - industrial machines), ISO 10816-1 (General guidelines),'),
  ('voltage_drop_iec_60364_5', 'Voltage Drop', 'electrical', ARRAY['iec_60364_5','ieee_141'], 'python:python-api/calcs/voltage_drop.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Voltage Drop — Phase 4b (Option B port from TypeScript) Standards: PEC 2017 Article 2.10.19 (branch: ≤3%), 2.15 (feeder: ≤2%), IEC 60364-5-52, IEEE 141 (Red Book)'),
  ('wastewater_stp', 'Wastewater Stp', 'plumbing', ARRAY[]::text[], 'python:python-api/calcs/wastewater_stp.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Wastewater Treatment (STP) — Phase 6j (Option B port from TypeScript) Standards: DENR DAO 2016-08 (Effluent Standards: BOD≤30, TSS≤50 mg/L), Metcalf & Eddy "Wastewater Engineering" 5th Ed.,'),
  ('water_softener_ansi_44', 'Water Softener', 'plumbing', ARRAY['ansi_44'], 'python:python-api/calcs/water_softener.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Water Softener Sizing — Phase 6h (Option B port from TypeScript) Standards: WQA (Water Quality Association) standards, NSF/ANSI 44, PNS 1998 / PNSDW (hardness limit 300 mg/L as CaCO3),'),
  ('water_supply_pipe', 'Water Supply Pipe', 'plumbing', ARRAY[]::text[], 'python:python-api/calcs/water_supply_pipe.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Water Supply Pipe Sizing — Phase 6e (Option B port from TypeScript) Standards: Philippine Plumbing Code (PPC) Table A-2/A-3, UPC Table 610.3, ASHRAE Plumbing Design Guide'),
  ('water_treatment_ansi_61', 'Water Treatment', 'plumbing', ARRAY['ansi_61'], 'python:python-api/calcs/water_treatment.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Water Treatment System — Phase 6i (Option B port from TypeScript) Standards: PNS 1998 / PNSDW (Philippine National Standards for Drinking Water), DOH AO 2017-0010, DENR DAO 2016-08, EPA Guidance Manual (UV/CT),'),
  ('wire_sizing_nec_2020', 'Wire Sizing', 'electrical', ARRAY['nec_2020','iec_60364_5','iec_60228'], 'python:python-api/calcs/wire_sizing.py:calculate', '[]'::jsonb, '[]'::jsonb, '', 'Wire Sizing - Phase 4a Standards: PEC 2017 (Philippine Electrical Code), NEC 2020, IEC 60364-5-52, IEC 60228 (conductor cross-sections), DOLE/OSHC')
ON CONFLICT (formula_id) DO UPDATE
  SET name=EXCLUDED.name, domain=EXCLUDED.domain, standard_ids=EXCLUDED.standard_ids,
      library_source=EXCLUDED.library_source, inputs=EXCLUDED.inputs, outputs=EXCLUDED.outputs,
      formula_text=EXCLUDED.formula_text, description=EXCLUDED.description;

COMMIT;
